PHOENIX = [
    'Phoenix, AZ',
    'Mesa, AZ',
    'Chandler, AZ',
    'Gilbert, AZ',
    'Glendale, AZ',
    'Scottsdale, AZ',
    'Peoria, AZ',
    'Tempe, AZ',
    'Surprise, AZ',
    'Goodyear, AZ',
    'Buckeye, AZ',
    'Avondale, AZ',
    'Queen Creek, AZ',
    'Maricopa, AZ',
    'Casa Grande, AZ',
    'Apache Junction, AZ',
    'El Mirage, AZ',
    'Florence, AZ',
    'Fountain Hills, AZ',
    'Eloy, AZ',
    'Coolidge, AZ',
    'Paradise Valley, AZ',
    'Wickenburg, AZ',
    'Tolleson, AZ',
    'Youngtown, AZ',
    'Litchfield Park, AZ',
    'Guadalupe, AZ',
    'Cave Creek, AZ',
    'Carefree, AZ',
    'Superior, AZ',
    'Kearny, AZ',
    'Gila Bend, AZ',
    'Mammoth, AZ',
    'San Tan Valley, AZ',
    'Sun City, AZ',
    'Sun City West, AZ',
    'Anthem, AZ',
    'New River, AZ',
    'Sun Lakes, AZ',
    'Gold Canyon, AZ',
    'Arizona City, AZ',
    'Aguila, AZ',
    'Ak-Chin Village, AZ',
    'Arlington, AZ',
    'Bapchule, AZ',
    'Cactus Forest, AZ',
    'Chuichu, AZ',
    'Circle City, AZ',
    'Eleven Mile Corner, AZ',
    'Komatke, AZ',
    'La Palma, AZ',
    'Liberty, AZ',
    'Morristown, AZ',
    'Olberg, AZ',
    'Palo Verde, AZ',
    'Queen Valley, AZ',
    'Red Rock, AZ',
    'Rio Verde, AZ',
    'Sacaton, AZ',
    'Stanfield, AZ',
    'Tonopah, AZ',
    'Tortilla Flat, AZ',
    'Valley Farms, AZ',
    'Waddell, AZ',
    'Wintersburg, AZ',
    'Wittmann, AZ'
]

TUCSON = [
    "South Tuscon, AZ",
    "Tucson, AZ",
    "Marana, AZ",
    "Ora Valley, AZ",
    "Sahuarita, AZ",
    "Casa Adobes, AZ",
    "Catalina Foothills, AZ",
    "Drexel Heights, AZ",
    "Green Valley, AZ",
    "Tanque Verde, AZ",
    "Flowing Wells, AZ",
    "Tucson Estates, AZ",
    "Vail, AZ",
    "Picture Rocks, AZ",
    "Valencia West, AZ",
    "Catalina, AZ"
    "Avra Valley, AZ",
    "Corona de Tucson, AZ",
    "South Tuscon, AZ",
    "Three Points, AZ",
    "Summit, AZ",
    "Rincon Valley, AZ",
    "Ajo, AZ",
    "Sells, AZ",
    "Arivaca Junction, AZ"
]