FORT_SMITH = [
    'Fort Smith, AR',
    'Van Buren, AR',
    'Alma, AR',
    'Arkoma, OK',
    'Barling, AR',
    'Cedarville, AR',
    'Charleston, AR',
    'Greenwood, AR',
    'Heavener, OK',
    'Lavaca, AR',
    'Mansfield, AR',
    'Mulberry, AR',
    'Muldrow, OK',
    'Ozark, AR',
    'Panama, OK',
    'Pocola, OK',
    'Poteau, OK',
    'Roland, OK',
    'Sallisaw, OK',
    'Spiro, OK',
    'Talihina, OK',
    'Vian, OK',
    'Wister, OK',
    'Bonanza, AR',
    'Brent, OK',
    'Brushy, OK',
    'Carlisle, OK',
    'Central City, AR',
    'Dyer, AR',
    'Gore, OK',
    'Hackett, AR',
    'Hartford, AR',
    'Howe, OK',
    'Huntington, AR',
    'Kibler, AR',
    'Mountainburg, AR',
    'Rock Island, OK',
    'Shady Point, OK',
    'Akins, OK',
    'Altus, AR',
    'Belfonte, OK',
    'Bokoshe, OK',
    'Branch, AR',
    'Cameron, OK',
    'Cecil, AR',
    'Chester, AR',
    'Cowlington, OK',
    'Denning, AR',
    'Dwight Mission, OK',
    'Evening Shade, OK',
    'Fanshawe, OK',
    'Flute Springs, OK',
    'Fort Coffee, OK',
    'Gans, OK',
    'Le Flore, OK',
    'Long, OK',
    'Marble City Community, OK',
    'Marble City, OK',
    'McKey, OK',
    'Midland, AR',
    'Moffett, OK',
    'Notchietown, OK',
    'Paradise Hill, OK',
    'Pinhook Corners, OK',
    'Redbird Smith, OK',
    'Remy, OK',
    'Rudy, AR',
    'Short, OK',
    'Stony Point, OK',
    'Sycamore, Sequoyah County, OK',
    'Wiederkehr Village, AR',
    'Big Cedar, OK',
    'Dora, AR',
    'Hodgen, OK',
    'Monroe, OK',
    'Muse, OK',
    'Skullyville, OK',
    'Whitesboro, OK'
]