ARKANSAS_FORT_SMITH = [
    "Fort Smith",
    "Van Buren",
    "Alma",
    "Barling",
    "Cedarville",
    "Charleston",
    "Greenwood",
    "Lavaca",
    "Mansfield",
    "Mulberry",
    "Ozark",
    "Bonanza",
    "Central City",
    "Dyer",
    "Hackett",
    "Hartford",
    "Huntington",
    "Kibler",
    "Mountainburg",
    "Altus",
    "Branch",
    "Cecil",
    "Chester",
    "Denning",
    "Midland",
    "Rudy",
    "Wiederkehr Village",
    "Dora",
]
