CALIFORNIA_LA_QUINTA = [
    "Cathedral City",
    "Coachella",
    "Desert Hot Springs",
    "Indian Wells",
    "Indio",
    "La Quinta",
    "Palm Desert",
    "Palm Springs",
    "Rancho Mirage"
]

CALIFORNIA_ORANGE_COUNTY = [
    "Aliso Viejo",
    "Anaheim",
    "Brea",
    "Buena Park",
    "Costa Mesa",
    "Cypress",
    "Dana Point",
    "Fountain Valley",
    "Fullerton",
    "Garden Grove",
    "Huntington Beach",
    "Irvine",
    "La Habra",
    "La Palma",
    "Laguna Beach",
    "Laguna Hills",
    "Laguna Niguel",
    "Laguna Woods",
    "Lake Forest",
    "Los Alamitos",
    "Mission Viejo",
    "Newport Beach",
    "Orange",
    "Placentia",
    "Rancho Santa Margarita",
    "San Clemente",
    "San Juan Capistrano",
    "Santa Ana",
    "Seal Beach",
    "Stanton",
    "Tustin",
    "Villa Park",
    "Westminster",
    "Yorba Linda",
    "Anaheim Island",
    "Coto de Caza",
    "Emerald Bay",
    "Ladera Ranch",
    "Las Flores",
    "Midway City",
    "Modjeska Canyon",
    "North Tustin"
]
