GEOGRAPHIC_AREAS = [
    "Fort Smith, AR",
    "Phoenix, AZ",
    "Tucson, AZ",
    "La Quinta, CA",
    "Orange County, CA",
    "Clearwater, FL",
    "Destin, FL",
    "Fort Lauderdale, FL",
    "Jacksonville, FL",
    "Orlando, FL",
    "Seminole County, FL",
    "St. Johns County, FL",
    "Tampa, FL",
    "Atlanta, GA",
    "Pocatello, ID",
    "Rockford, IL",
    "Springfield, KY",
    "Minneapolis, MN",
    "Kansas City, MO",
    "Charlotte, NC",
    "Durham, NC",
    "Wake County, NC",
    "Winston-Salem, NC",
    "Lincoln, NE",
    "Omaha, NE",
    "Burlington County, NJ",
    "Albuquerque, NM",
    "Las Vegas, NV",
    "Reno, NV",
    "Long Island, NY",
    "Akron, OH",
    "Cincinnati, OH",
    "Mount Vernon, OH",
    "Bucks County, PA",
    "Centre County, PA",
    "Chester County, PA",
    "Delaware County, PA",
    "Montgomery County, PA",
    "Philadelphia County, PA",
    "Pittsburgh, PA",
    "York, PA",
    "Beaufort County, SC",
    "Charleston, SC",
    "Sioux Falls, SD",
    "Nashville, TN",
    "Amarillo, TX",
    "Austin, TX",
    "Beaumont, TX",
    "Dallas, TX",
    "El Paso, TX",
    "Houston, TX",
    "McAllen, TX",
    "San Antonio, TX",
    "Fairfax, VA",
    "Loudon County, VA",
    "Appleton, WI",
    "Green Bay, WI",
    "Milwaukee, WI"
]
