FLORIDA_CLEARWATER = [
    "Tampa",
    "St. Petersburg",
    "Clearwater",
    "Lakeland",
    "Riverview",
    "Brandon",
    "Spring Hill",
    "Apollo Beach",
    "Bayonet Point",
    "Bloomingdale",
    "Citrus Park",
    "Cheval",
    "Dunedin",
    "Egypt Lake-Leto",
    "East Lake",
    "East Lake-Orient Park",
    "Elfers",
    "Fish Hawk",
    "Greater Carrollwood",
    "Greater Northdale",
    "Gulfport",
    "Holiday",
    "Hudson",
    "Jasmine Estates",
    "Keystone",
    "Lake Magdalene",
    "Land o' Lakes",
    "Largo",
    "Lealman",
    "Lutz",
    "New Port Richey",
    "Mango",
    "Oldsmar",
    "Palm Harbor",
    "Palm River-Clair Mel",
    "Pinellas Park",
    "Plant City",
    "Ruskin",
    "Safety Harbor",
    "Shady Hills",
    "Seminole",
    "Sun Center",
    "Tarpon Springs",
    "Temple Terrace",
    "Thonotosassa",
    "Town 'n' Country",
    "Trinity",
    "Valrico",
    "Wesley Chapel",
    "West Lealman",
    "Westchase",
    "Zephyrhills"
]

FLORIDA_DESTIN = [
    "Crestview",
    "Fort Walton Beach",
    "DeFuniak Springs",
    "Destin",
    "Niceville",
    "Valparaiso",
    "Freeport",
    "Mary Esther",
    "Laurel Hill",
    "Paxton",
    "Shalimar",
    "Cinco Bayou"
]

FLORIDA_FORT_LAUDERDALE = [
    "Miami",
    "Hialeah",
    "Fort Lauderdale",
    "Pembroke Pines",
    "Hollywood",
    "Miramar",
    "Coral Springs",
    "Miami Gardens",
    "Pompano Beach",
    "West Palm Beach",
    "Davie",
    "Boca Raton",
    "Sunrise",
    "Plantation",
    "Miami Beach",
    "Deerfield Beach",
    "Boynton Beach",
    "Lauderhill",
    "Weston",
    "Homestead",
    "Aventura",
    "Belle Glade",
    "Boca Del Mar",
    "Boca Raton",
    "Boynton Beach",
    "Brownsville",
    "Coconut Creek",
    "Cooper City",
    "Coral Gables",
    "Coral Terrace",
    "Country Club",
    "Country Walk",
    "Cutler Bay",
    "Dania Beach",
    "Deerfield Beach",
    "Delray Beach",
    "Doral",
    "Florida City",
    "Fontainebleau",
    "Gladeview",
    "Glenvar Heights",
    "Goulds",
    "Greenacres",
    "Hallandale Beach",
    "Hamptons at Boca Raton",
    "Hialeah Gardens",
    "Homestead",
    "Ives Estates",
    "Jupiter",
    "Kendale Lakes",
    "Kendall West",
    "Kendall",
    "Key Biscayne",
    "Kings Point",
    "Lake Worth Corridor",
    "Lake Worth Beach",
    "Lauderdale Lakes",
    "Lauderhill",
    "Leisure City",
    "Lighthouse Point",
    "Margate",
    "Miami Beach",
    "Miami Lakes",
    "Miami Shores",
    "Miami Springs",
    "North Lauderdale",
    "North Miami Beach",
    "North Miami",
    "North Palm Beach",
    "Oakland Park",
    "Ojus",
    "Olympia Heights",
    "Opa-locka",
    "Palm Beach Gardens",
    "Palm Beach",
    "Palm Springs",
    "Palmetto Bay",
    "Palmetto Estates",
    "Parkland",
    "Pinecrest",
    "Pinewood",
    "Plantation",
    "Princeton",
    "Richmond West",
    "Riviera Beach",
    "Royal Palm Beach",
    "Sandalfoot Cove",
    "South Miami Heights",
    "South Miami",
    "Sunny Isles Beach",
    "Sunrise",
    "Sunset",
    "Sweetwater",
    "Tamarac",
    "Tamiami",
    "The Crossings",
    "The Hammocks",
    "University Park",
    "Wellington",
    "West Little River",
    "West Park",
    "Westchester",
    "Weston",
    "Westwood Lakes",
    "Wilton Manors",
    "Atlantis",
    "Bal Harbour",
    "Bay Harbor Islands",
    "Belle Glade Camp",
    "Biscayne Park",
    "Boca Pointe",
    "Boulevard Gardens",
    "Briny Breezes",
    "Broadview Park",
    "Canal Point",
    "Century Village",
    "Cypress Lakes",
    "Dunes Road",
    "El Portal",
    "Fisher Island",
    "Franklin Park",
    "Fremd Village-Padgett Island",
    "Glen Ridge",
    "Godfrey Road",
    "Golden Beach",
    "Golden Lakes",
    "Golf",
    "Gulf Stream",
    "Gun Club Estates",
    "Haverhill",
    "High Point",
    "Highland Beach",
    "Hillsboro Beach",
    "Hillsboro Pines",
    "Homestead Base",
    "Hypoluxo",
    "Indian Creek",
    "Islandia",
    "Juno Beach",
    "Juno Ridge",
    "Jupiter Inlet Colony",
    "Lake Belvedere Estates",
    "Lake Clarke Shores",
    "Lake Harbor",
    "Lake Park",
    "Lakeside Green",
    "Lantana",
    "Lauderdale-by-the-Sea",
    "Lazy Lake",
    "Limestone Creek",
    "Manalapan",
    "Mangonia Park",
    "Medley",
    "Mission Bay",
    "Naranja",
    "North Bay Village",
    "Ocean Ridge",
    "Pahokee",
    "Palm Beach Shores",
    "Palm Springs North",
    "Pembroke Park",
    "Plantation Mobile Home Park",
    "Richmond Heights",
    "Roosevelt Gardens",
    "Royal Palm Estates",
    "Schall Circle",
    "Sea Ranch Lakes",
    "Seminole Manor",
    "South Bay",
    "South Palm Beach",
    "Southwest Ranches",
    "Stacy Street",
    "Surfside",
    "Tequesta",
    "Three Lakes",
    "Villages of Oriole",
    "Virginia Gardens",
    "Washington Park",
    "Westlake",
    "West Miami",
    "West Perrine",
    "Westview",
    "Whisper Walk"
]

FLORIDA_JACKSONVILLE = [
    "Macclenny",
    "Glen St. Mary",
    "Baxter",
    "Cuyler",
    "Olustee",
    "Sanderson",
    "Taylor",
    "Black Bottom/Trail Ridge",
    "Two Bridges",
    "Edd/Eddy Grade",
    "Manning",
    "Jacksonville",
    "Jacksonville Beach",
    "Atlantic Beach",
    "Neptune Beach",
    "Baldwin",
    "St. Augustine",
    "St. Augustine Beach",
    "Butler Beach",
    "Crescent Beach",
    "Flagler Estates",
    "Fruit Cove",
    "Nocatee",
    "Palm Valley",
    "Sawgrass",
    "St. Augustine Shores",
    "St. Augustine South",
    "Villano Beach",
    "World Golf Village",
    "Bakersville",
    "Elkton",
    "Hastings",
    "Julington Creek Plantation",
    "Mill Creek",
    "Ponte Verdra Beach",
    "St. Johns",
    "Spuds",
    "Summer Haven",
    "Switzerland",
    "Vermont Heights",
    "Green Cove Springs",
    "Keystone Heights",
    "Orange Park",
    "Penny Farms",
    "Asbury Lake",
    "Bellair-Meadowbrook Terrace",
    "Fleming Island",
    "Lakeside",
    "Middleburg",
    "Oakleaf Plantation",
    "Belmore",
    "Clay Hill",
    "Doctors Inlet",
    "Hibernia",
    "Lake Geneva",
    "McRae",
    "Virginia Village",
    "Fernandina Beach",
    "Callahan",
    "Hilliard",
    "Nassau Village-Ratliff",
    "Yulee",
    "Amelia City",
    "American Beach",
    "Andrews",
    "Becker",
    "Boulogne",
    "Bryceville",
    "Chester",
    "Crandall",
    "Crawford",
    "Crawford",
    "Dahoma",
    "Dyal",
    "Evergreen",
    "Franklintown",
    "Glenwood",
    "Gross",
    "Hedges",
    "Hero",
    "Ingle",
    "Italia",
    "Keene",
    "Kent",
    "Kings Ferry",
    "Lessie",
    "Mattox",
    "Nassauville",
    "O'Neil",
    "Verdie",
    "Yulee Heights"
]

FLORIDA_ORLANDO = [
    "Orlando",
    "Kissimmee",
    "Sanford",
    "Alafaya",
    "Altamonte Springs",
    "Apopka",
    "Azalea Park",
    "Buenaventura Lakes",
    "Casselberry",
    "Clermont",
    "Conway",
    "DeBary",
    "Deltona",
    "Doctor Phillips",
    "Eustis",
    "Fairview Shores",
    "Four Corners",
    "Goldenrod",
    "Horizon West",
    "Hunter's Creek",
    "Lake Butler",
    "Lake Mary",
    "Lockhart",
    "Longwood",
    "Maitland",
    "Meadow Woods",
    "Mount Dora",
    "Oak Ridge",
    "Ocoee",
    "Oviedo",
    "Pine Castle",
    "Pine Hills",
    "Poinciana",
    "Saint Cloud",
    "Southchase",
    "Tavares",
    "University",
    "Wekiva Springs",
    "Winter Garden",
    "Winter Park",
    "Winter Springs",
    "Bay Lake",
    "Bay Hill",
    "Bithlo",
    "Belle Isle",
    "Campbell",
    "Celebration",
    "Chuluota",
    "Eatonville",
    "Edgewood",
    "Ferndale",
    "Fern Park",
    "Geneva",
    "Gotha",
    "Groveland",
    "Heathrow",
    "Holden Heights",
    "Lake Buena Vista",
    "Lake Hart",
    "Midway",
    "Minneola",
    "Montverde",
    "Mount Plymouth",
    "Oakland",
    "Okahumpka",
    "Orlo Vista",
    "Paradise Heights",
    "Sky Lake",
    "Sorrento",
    "South Apopka",
    "Taft",
    "Tangelo Park",
    "Tangerine",
    "Tildenville",
    "Union Park",
    "Vineland",
    "Wedgefield",
    "Williamsburg",
    "Windermere",
    "Zellwood"
]

FLORIDA_SEMINOLE_COUNTY = [
    "Altamonte Springs",
    "Casselberry",
    "Lake Mary",
    "Longwood",
    "Oviedo",
    "Sanford",
    "Winter Springs",
    "Black Hammock",
    "Chuluota",
    "Fern Park",
    "Forest City",
    "Geneva",
    "Goldenrod",
    "Heathrow",
    "Midway",
    "Wekiwa Springs",
    "Bertha",
    "Indian Mound Village",
    "Lake Monroe",
    "Slavia",
    "Sanlando Springs",
    "Taintsville",
    "Tuskawilla"
]

FLORIDA_ST_JOHNS_COUNTY = [
    "St. Augustine",
    "St. Augustine Beach",
    "Butler Beach",
    "Crescent Beach",
    "Flagler Estates",
    "Fruit Cove",
    "Nocatee",
    "Palm Valley",
    "Sawgrass",
    "St. Augustine Shores",
    "St. Augustine South",
    "Villano Beach",
    "World Golf Village",
    "Bakersville",
    "Elkton",
    "Hastings",
    "Julington Creek Plantation",
    "Mill Creek",
    "Ponte Verdra Beach",
    "St. Johns",
    "Spuds",
    "Summer Haven",
    "Switzerland",
    "Vermont Heights"
]

FLORIDA_TAMPA = [
    "Tampa, FL"
]
