ATLANTA = [
    'Brookhaven, GA',
    'Peachtree Corners, GA',
    'Cumberland, GA',
    'Perimeter Center, GA',
    'Gwinnett Place, GA',
    'Sugarloaf, GA',
    'East Cobb, GA',
    'Roswell, GA',
    'Atlanta, GA',
    'South Fulton, GA',
    'Sandy Springs, GA',
    'Roswell, GA',
    'Johns Creek, GA',
    'Alpharetta, GA',
    'Marietta, GA',
    'Stonecrest, GA',
    'Smyrna, GA',
    'Dunwoody, GA',
    'Mableton, GA',
    'Peachtree City, GA',
    'Gainesville, GA',
    'East Point, GA',
    'Tucker, GA',
    'Newnan, GA',
    'Redan, GA',
    'Milton, GA',
    'Douglasville, GA',
    'Kennesaw, GA',
    'Chamblee, GA',
    'Lawrenceville, GA',
    'Duluth, GA',
    'Stockbridge, GA',
    'Carrollton, GA',
    'Woodstock, GA',
    'Griffin, GA',
    'Candler-McAfee, GA',
    'Canton, GA',
    'McDonough, GA',
    'Acworth, GA',
    'Cartersville, GA',
    'Union City, GA',
    'Decatur, GA',
    'North Druid Hills, GA',
    'Sugar Hill, GA',
    'Forest Park, GA',
    'Snellville, GA',
    'North Decatur, GA',
    'Fayetteville, GA',
    'Lithia Springs, GA',
    'Suwanee, GA',
    'Conyers, GA',
    'Belvedere Park, GA',
    'Riverdale, GA',
    'Druid Hills, GA',
    'Winder, GA',
    'Villa Rica, GA',
    'College Park, GA',
    'Powder Springs, GA',
    'Monroe, GA',
    'Covington, GA',
    'Fairburn, GA',
    'Buford, GA',
    'Lilburn, GA',
    'Mountain Park (Gwinnett), GA',
    'Dallas, GA',
    'Loganville, GA',
    'Panthersville, GA',
    'Vinings, GA',
    'Tyrone, GA',
    'Thomaston, GA',
    'Norcross, GA',
    'Doraville, GA',
    'Clarkston, GA',
    'Braselton, GA',
    'Irondale, GA',
    'Centerville, GA',
    'Hampton, GA',
    'Auburn, GA',
    'Barnesville, GA',
    'Austell, GA',
    'Morrow, GA',
    'Lovejoy, GA',
    'Hapeville, GA',
    'Conley, GA',
    'Stone Mountain, GA',
    'Flowery Branch, GA',
    'Cumming, GA',
    'Locust Grove, GA',
    'Jonesboro, GA',
    'Palmetto, GA',
    'Dacula, GA',
    'Bonanza, GA',
    'Avondale Estates, GA',
    'Lakeview Estates, GA',
    'Grayson, GA',
    'Lake City, GA',
    'Chattahoochee Hills, GA',
    'Lithonia, GA',
    'Berkeley Lake, GA'
]