MINNESOTA_MINNEAPOLIS = [
    'Bloomington, MN',
    'Brooklyn Center, MN',
    'Brooklyn Park, MN',
    'Champlin, MN',
    'Chanhassen, MN',
    'Corcoran, MN',
    'Crystal, MN',
    'Dayton, MN',
    'Deephaven, MN',
    'Eden Prairie, MN',
    'Edina, MN',
    'Excelsior, MN',
    'Golden Valley, MN',
    'Greenfield, MN',
    'Greenwood, MN',
    'Hanover, MN',
    'Hopkins, MN',
    'Independence, MN',
    'Long Lake, MN',
    'Loretto, MN',
    'Maple Grove, MN',
    'Maple Plain, MN',
    'Medicine Lake, MN',
    'Medina, MN',
    'Minneapolis, MN',
    'Minnetonka, MN',
    'Minnetonka Beach, MN',
    'Minnetrista, MN',
    'Mound, MN',
    'New Hope, MN',
    'Orono, MN',
    'Osseo, MN',
    'Plymouth, MN',
    'Richfield, MN',
    'Robbinsdale, MN',
    'Rockford, MN',
    'Rogers, MN',
    'Shorewood, MN',
    'Spring Park, MN',
    'St. Anthony, MN',
    'St. Bonifacius, MN',
    'St. Louis Park, MN',
    'Tonka Bay, MN',
    'Wayzata, MN',
    'Woodland, MN'
]