MISSOURI_KANSAS_CITY = [
    "Blue Springs, MO",
    "Buckner, MO",
    "Grain Valley, MO",
    "Grandview, MO",
    "Greenwood, MO",
    "Independence, MO",
    "Kansas City, MO",
    "Lake Lotawana, MO",
    "Lake Tapawingo, MO",
    "Lee's Summit, MO",
    "Levasy, MO",
    "Lone Jack, MO",
    "Oak Grove, MO",
    "Pleasant Hill, MO",
    "Raytown, MO",
    "Sugar Creek, MO",
    "River Bend, MO",
    "Sibley, MO",
    "Unity Village, MO",
    "Blue Summit, MO",
    "Tarsney Lakes, MO",
    "Atherton, MO",
    "Blue Mills, MO",
    "Blue Summit, MO",
    "Cockrell, MO",
    "Courtney, MO",
    "Hiler, MO",
    "Hicks County, MO",
    "Oakland, MO",
    "Pink Hill, MO",
    "Sni Mills, MO",
    "Tarsney, MO",
    "Camden Point, MO",
    "Dearborn, MO",
    "Edgerton, MO",
    "Houston Lake, MO",
    "Lake Waukomis, MO",
    "Northmoor, MO",
    "Parkville, MO",
    "Platte City, MO",
    "Platte Woods, MO",
    "Riverside, MO",
    "Smithville, MO",
    "Tracy, MO",
    "Weatherby Lake, MO",
    "Weston, MO",
    "Farley, MO",
    "Ferrelview, MO",
    "Iatan, MO",
    "Ridgely, MO",
    "Carroll, MO,",
    "Flair, MO",
    "Fox, MO",
    "Green, MO",
    "Kickapoo, MO",
    "Lee, MO",
    "Marshall, MO",
    "May, MO",
    "Pawnee, MO",
    "Pettis, MO",
    "Preston, MO",
    "Sioux, MO",
    "Waldron, MO",
    "Weston, MO",
    "Beverly, MO",
    "Dye, MO",
    "East Leavenworth, MO",
    "Edgerton Junction, MO",
    "Hoover, MO",
    "Kerrville, MO",
    "New Market, MO",
    "Stillings, MO",
    "Stubbs, MO",
    "Waldron, MO",
    "West Platte, MO",
    "Woodruff, MO",
    "Avondale, MO",
    "Birmingham, MO",
    "Claycomo, MO",
    "Excelsior Estates, MO",
    "Excelsior Springs, MO",
    "Gladstone, MO",
    "Glenaire, MO",
    "Holt, MO",
    "Kearney, MO",
    "Lawson, MO",
    "Liberty, MO",
    "Missouri County, MO",
    "Mosby, MO",
    "North Kansas City, MO",
    "Oaks, MO",
    "Oakview, MO",
    "Oakwood, MO",
    "Oakwood Park, MO",
    "Pleasant Valley, MO",
    "Prathersville, MO",
    "Randolph, MO",
    "Smithville, MO",
    "Sugar Creek, MO",
    "Arley, MO",
    "Chandler, MO",
    "Claysville, MO",
    "Clevenger, MO",
    "Ectonville, MO",
    "Miltondale, MO",
    "Roosterville, MO",
    "Stockdale, MO",
    "Winner, MO",
    "Archie, MO",
    "Belton, MO",
    "Cleveland, MO",
    "Creighton, MO",
    "Drexel, MO",
    "East Lynne, MO",
    "Freeman, MO",
    "Garden City, MO",
    "Harrisonville, MO",
    "Lake Annette, MO",
    "Lake Winnebago, MO",
    "Peculiar, MO",
    "Pleasant Hill, MO",
    "Raymore, MO",
    "Strasburg, MO",
    "Baldwin Park, MO",
    "Gunn City, MO",
    "Riverview Estates, MO",
    "West Line, MO",
    "Lock Lloyd, MO",
    "Martin City, MO",
    "Austin, MO",
    "Coleman, MO",
    "Daugherty, MO",
    "Dayton, MO",
    "Everett, MO",
    "Jaudon, MO",
    "Lisle, MO",
    "Lone Tree, MO",
    "Main City, MO",
    "Wingate, MO"
]