NEBRASKA_LINCOLN = [
    "Lincoln, NE",
    "Hickman, NE",
    "Milford, NE",
    "Seward, NE",
    "Waverly, NE",
    "Bennet, NE",
    "Firth, NE",
    "Utica, NE",
    "Walton, NE",
    "Hallam, NE",
    "Malcolm, NE",
    "Panama, NE",
    "Staplehurst, NE",
    "Bee, NE",
    "Cordova, NE",
    "Davey, NE",
    "Denton, NE",
    "Garland, NE",
    "Goehner, NE",
    "Pleasant Dale, NE",
    "Raymond, NE",
    "Roca, NE",
    "Sprague, NE"
]

NEBRASKA_OMAHA = [
    "Bennington, NE",
    "Omaha, NE",
    "East Omaha, NE",
    "North Omaha, NE",
    "South Omaha, NE",
    "West Omaha, NE",
    "Ralston, NE",
    "Valley, NE",
    "Boys Town, NE",
    "Waterloo, NE",
    "King Lake, NE",
    "Venice, NE",
    "Briggs, NE",
    "Debolt, NE",
    "Elk City, NE",
    "Irvington, NE",
    "Lane, NE"
]