NEBRASKA_LINCOLN = [
    "Lincoln",
    "Hickman",
    "Milford",
    "Seward",
    "Waverly",
    "Bennet",
    "Firth",
    "Utica",
    "Walton",
    "Hallam",
    "Malcolm",
    "Panama",
    "Staplehurst",
    "Bee",
    "Cordova",
    "Davey",
    "Denton",
    "Garland",
    "Goehner",
    "Pleasant Dale",
    "Raymond",
    "Roca",
    "Sprague"
]

NEBRASKA_OMAHA = [
    "Bennington",
    "Omaha",
    "East Omaha",
    "North Omaha",
    "South Omaha",
    "West Omaha",
    "Ralston",
    "Valley",
    "Boys Town",
    "Waterloo",
    "King Lake",
    "Venice",
    "Briggs",
    "Debolt",
    "Elk City",
    "Irvington",
    "Lane"
]
