NEVADA_LAS_VEGAS = [
    "Las Vegas, NV",
    "Boulder City, NV",
    "Enterprise, NV",
    "Henderson, NV",
    "Lone Mountain, NV",
    "North Las Vegas, NV",
    "Paradise, NV",
    "Spring Valley, NV",
    "Summerlin South, NV",
    "Sunrise Manor, NV",
    "Whitney, NV",
    "Winchester, NV",
    "Mesquite, NV",
    "North Las Vegas, NV",
    "Blue Diamond, NV",
    "Bunkerville, NV",
    "Cal-Nev-Ari, NV",
    "Goodsprings, NV",
    "Indian Springs, NV",
    "Laughlin, NV",
    "Moapa Town, NV",
    "Moapa Valley, NV",
    "Mount Charleston, NV",
    "Nelson, NV",
    "Sandy Valley, NV",
    "Searchlight, NV",
    "Spring Valley, NV",
    "Creech AFB, NV",
    "Nellis AFB, NV",
    "Arden, NV",
    "Cactus Springs, NV",
    "Cottonwood Cove, NV",
    "Coyote Springs, NV",
    "Crystal, NV",
    "Fort Mojave Indian Reservation, NV",
    "Glendale, NV",
    "Jean, NV",
    "Logandale, NV",
    "Las Vages Indian Colony, NV",
    "Moapa River Indian Reservation, NV",
    "Mountain Springs, NV",
    "Overton, NV",
    "Primm, NV",
    "Roach, NV",
    "Sloan, NV",
    "Summerlin, NV",
    "Sutor, NV",
    "Vegas Creek, NV"
]

NEVADA_RENO = [
    "Reno, NV",
    "Sparks, NV",
    "Cold Springs, NV",
    "Crystal Bay, NV",
    "Empire, NV",
    "Gerlach, NV",
    "Golden Valley, NV",
    "Incline Village, NV",
    "Lemmon Valley, NV",
    "Mogul, NV",
    "Nixon, NV",
    "Spanish Springs, NV",
    "Sun Valley, NV",
    "Sutcliffe, NV",
    "Verdi, NV",
    "Virginia City, NV",
    "Wadsworth, NV",
    "Gold Hill, NV",
    "New Washoe City, NV",
    "Pleasant Valley, NV",
    "Poeville, NV",
    "Pryamid, NV",
    "Vya, NV"
    "Reno, NV",
    "Sparks, NV",
    "Cold Springs, NV",
    "Crystal Bay, NV",
    "Empire, NV",
    "Gerlach, NV",
    "Golden Valley, NV",
    "Incline Village, NV",
    "Lemmon Valley, NV",
    "Mogul, NV",
    "Nixon, NV",
    "Spanish Springs, NV",
    "Sun Valley, NV",
    "Sutcliffe, NV",
    "Verdi, NV",
    "Wadsworth, NV",
    "Washoe Valley, NV",
    "Anderson, NV",
    "Antelope Valley, NV",
    "Arrowcreek, NV",
    "Bartley Ranch, NV",
    "Beulah, NV",
    "Border Town, NV",
    "Bronco, NV",
    "Buffalo Ranch, NV",
    "Caughlin Ranch, NV",
    "Copperfield, NV",
    "Damonte Ranch, NV",
    "Deep Hole, NV",
    "Diessner, NV",
    "Dodge, NV",
    "Flanigan, NV",
    "Franktown, NV",
    "Galena, NV",
    "Glendale, NV",
    "Grand View Terrace, NV",
    "Heinz, NV",
    "Hidden Valley, NV",
    "Hot Springs, NV",
    "Huffaker, NV",
    "Jumbo, NV",
    "Lawton, NV",
    "Mayberry-Highland Park, NV",
    "McCarran, NV",
    "Mira Loma, NV",
    "Montrêux, NV",
    "Mustang, NV",
    "New Washoe City, NV",
    "North Valleys, NV",
    "Northeast Reno, NV",
    "Northwest Reno, NV",
    "Olinghouse, NV",
    "Palomino Valley, NV",
    "Panther Valley, NV",
    "Phil, NV",
    "Poeville, NV",
    "Pleasant Valley, NV",
    "Pyramid, NV",
    "Raleigh Heights, NV",
    "Rancho Haven, NV",
    "Red Hawk, NV",
    "Red Rock, NV",
    "Reederville, NV",
    "Saddlehorn, NV",
    "Sand Pass, NV",
    "Sano, NV",
    "Steamboat Springs, NV",
    "Upper Pyramid, NV",
    "Virginia Foothills, NV",
    "Vya, NV",
    "Washoe City, NV",
    "Washoe Summit, NV",
    "Wedekind, NV",
    "Winnemucca Ranch, NV"
]