NEW_MEXICO_ALBUQUERQUE = [
    "Albuquerque",
    "Belen",
    "Moriarty",
    "Rio Communities",
    "Rio Rancho",
    "Bernalillo",
    "Estancia",
    "Mountainair",
    "Peralta",
    "Bosque Farms",
    "Corrales",
    "Cuba",
    "Encino",
    "Jemez Springs",
    "Los Lunas",
    "Los Ranchos de Albuquerque",
    "San Ysidro",
    "Tijeras",
    "Willard",
    "Algodones",
    "Carnuel",
    "Casa Colorada",
    "Cedar Crest",
    "Chilili",
    "Cochiti",
    "El Cerro-Monterey Park",
    "Isleta Village Proper",
    "Jarales",
    "Jemez Pueblo",
    "La Jara",
    "Los Chavez",
    "Los Trujillos-Gabaldon",
    "Manzano",
    "Meadow Lake",
    "North Valley",
    "Paradise Hills",
    "Pena Blanca",
    "Placitas",
    "Ponderosa",
    "Pueblo of Sandia Village",
    "Regina",
    "Rio Communities North",
    "Rio Communities",
    "San Felipe Pueblo",
    "Santa Ana Pueblo",
    "Santo Domingo Pueblo",
    "South Valley",
    "Tajique",
    "Tome Adelino",
    "Torreon",
    "Valencia",
    "Zia Pueblo",
    "Edgewood",
    "Barton",
    "Carnuel",
    "Cedar Crest",
    "Cedro",
    "Chilili",
    "Edith Endave",
    "Isleta",
    "Kirtland AFB",
    "Manzano Springs",
    "North Valley",
    "Paa-Ko",
    "Pajarito Mesa",
    "Paradise Hills",
    "Ponderosa Pine",
    "San Antonito",
    "Sandia Heights",
    "Sandia Knolls",
    "Sandia Park",
    "Sedillo",
    "South Valley",
    "Alameda",
    "Isleta Pueblo",
    "Laguna Pueblo",
    "Sandia Pueblo",
    "Zuzax"
]
