NEW_JERSEY_BURLINGTON_COUNTY = [
    "Bass River Township",
    "Beverly",
    "Bordentown",
    "Bordentown Township",
    "Burlington",
    "Burlington Township",
    "Chesterfield",
    "Cinnaminson Township",
    "Delanco Township",
    "Delran Township",
    "Easthampton Township",
    "Edgewater Park",
    "Evesham Township",
    "Fieldsboro",
    "Florence Township",
    "Hainsport Township",
    "Lumberton Township",
    "Mansfield Township",
    "Maple Shade Township",
    "Medford",
    "Medford Lakes",
    "Moorestown Township",
    "Mount Holly",
    "Mount Laurel",
    "New Hanover Township",
    "North Hanover Township",
    "Palmyra",
    "Pemberton",
    "Pemberton Township",
    "Riverside Township",
    "Riverton",
    "Shamong Township",
    "Southampton Township",
    "Springfield Township",
    "Tabernacle Township",
    "Washington Township",
    "Westampton Township",
    "Willingboro Township",
    "Woodland Township",
    "Wrightstown"
]
