NEW_YORK_LONG_ISLAND = [
    'Brooklyn, NY', 
    'Queens, NY', 
    'Nassau County, NY', 
    'Glen Cove, NY', 
    'Long Beach, NY', 
    'Hempstead, NY',  
    'Atlantic Beach, NY', 
    'Bellerose, NY', 
    'Cedarhurst, NY', 
    'East Rockaway, NY', 
    'Freeport, NY', 
    'Garden City, NY', 
    'Hempstead, NY', 
    'Hewlett Bay Park, NY', 
    'Hewlett Harbor, NY', 
    'Hewlett Neck, NY', 
    'Island Park, NY', 
    'Lawrence, NY', 
    'Lynbrook, NY', 
    'Malverne, NY', 
    'Rockville Centre, NY', 
    'South Floral Park, NY', 
    'Stewart Manor, NY', 
    'Valley Stream, NY', 
    'Woodsburgh, NY', 
    'Baldwin, NY', 
    'Baldwin Harbor, NY', 
    'Barnum Island, NY', 
    'Bay Park, NY', 
    'Bellerose Terrace, NY', 
    'Bellmore, NY', 
    'East Atlantic Beach, NY', 
    'East Garden City, NY', 
    'East Meadow, NY', 
    'Elmont, NY', 
    'Franklin Square, NY', 
    'Garden City South, NY', 
    'Harbor Isle, NY', 
    'Hewlett, NY', 
    'Inwood, NY', 
    'Lakeview, NY', 
    'Levittown, NY', 
    'Lido Beach, NY', 
    'Malverne Park Oaks, NY', 
    'Merrick, NY', 
    'North Bellmore, NY', 
    'North Lynbrook, NY', 
    'North Merrick, NY', 
    'North Valley Stream, NY', 
    'North Wantagh, NY', 
    'North Woodmere, NY', 
    'Oceanside, NY', 
    'Point Lookout, NY', 
    'Roosevelt, NY', 
    'Salisbury, NY', 
    'Seaford, NY', 
    'South Hempstead, NY', 
    'South Valley Stream, NY', 
    'Uniondale, NY', 
    'Wantagh, NY', 
    'West Hempstead, NY', 
    'Woodmere, NY', 
    'Floral Park, NY', 
    'Garden City, NY', 
    'Mineola, NY', 
    'New Hyde Park, NY', 
    'North Hempstead, NY',  
    'Baxter Estates, NY', 
    'East Williston, NY', 
    'Flower Hill, NY', 
    'Great Neck, NY', 
    'Great Neck Estates, NY', 
    'Great Neck Plaza, NY', 
    'Kensington, NY', 
    'Kings Point, NY', 
    'Lake Success, NY', 
    'Manorhaven, NY', 
    'Munsey Park, NY', 
    'North Hills, NY', 
    'Plandome, NY', 
    'Plandome Heights, NY', 
    'Plandome Manor, NY', 
    'Port Washington North, NY', 
    'Roslyn, NY', 
    'Roslyn Estates, NY', 
    'Russell Gardens, NY', 
    'Saddle Rock, NY', 
    'Sands Point, NY', 
    'Thomaston, NY', 
    'Westbury, NY', 
    'Williston Park, NY', 
    'Albertson, NY', 
    'Carle Place, NY', 
    'Garden City Park, NY', 
    'Glenwood Landing, NY', 
    'Great Neck Gardens, NY', 
    'Greenvale, NY', 
    'Harbor Hills, NY', 
    'Herricks, NY', 
    'Manhasset, NY', 
    'Manhasset Hills, NY', 
    'New Cassel, NY', 
    'North New Hyde Park, NY', 
    'Port Washington, NY', 
    'Roslyn Heights, NY', 
    'Saddle Rock Estates, NY', 
    'Searingtown, NY',
    'University Gardens, NY', 
    'East Hills, NY', 
    'Old Westbury, NY', 
    'Roslyn Harbor, NY', 
    'Oyster Bay, New York, NY',
    'Bayville, NY', 
    'Brookville, NY', 
    'Centre Island, NY', 
    'Cove Neck, NY', 
    'Farmingdale, NY', 
    'Lattingtown, NY', 
    'Laurel Hollow, NY', 
    'Massapequa Park, NY', 
    'Matinecock, NY', 
    'Mill Neck, NY', 
    'Muttontown, NY', 
    'Old Brookville, NY', 
    'Oyster Bay Cove, NY', 
    'Sea Cliff, NY', 
    'Upper Brookville, NY', 
    'Bethpage, NY', 
    'East Massapequa, NY', 
    'East Norwich, NY', 
    'Glen Head, NY', 
    'Glenwood Landing, NY', 
    'Greenvale, NY', 
    'Hicksville, NY', 
    'Jericho, NY', 
    'Locust Valley, NY', 
    'Massapequa, NY', 
    'North Massapequa, NY', 
    'Old Bethpage, NY', 
    'Oyster Bay, NY', 
    'Plainedge, NY', 
    'Plainview, NY', 
    'South Farmingdale, NY', 
    'Syosset, NY', 
    'Woodbury, NY', 
    'East Hills, NY', 
    'Old Westbury, NY', 
    'Roslyn Harbor, NY',
    'Suffolk County, NY',  
    'Babylon, NY', 
    'Amityville, NY', 
    'Babylon, NY', 
    'Lindenhurst, NY', 
    'Copiague, NY', 
    'Deer Park, NY', 
    'East Farmingdale, NY', 
    'Gilgo, NY', 
    'North Amityville, NY', 
    'North Babylon, NY', 
    'North Lindenhurst, NY', 
    'Oak Beach, NY', 
    'Captree, NY', 
    'West Babylon, NY', 
    'Wheatley Heights, NY', 
    'Wyandanch, NY', 
    'Copiague Harbor, NY',  
    'Huntington, New York, NY', 
    'Asharoken, NY', 
    'Huntington Bay, NY', 
    'Lloyd Harbor, NY', 
    'Northport, NY', 
    'Centerport, NY', 
    'Cold Spring Harbor, NY', 
    'Dix Hills, NY', 
    'East Northport, NY', 
    'Eatons Neck, NY', 
    'Elwood, NY', 
    'Greenlawn, NY', 
    'Halesite, NY', 
    'Huntington, NY', 
    'Huntington Station, NY', 
    'Melville, NY', 
    'South Huntington, NY', 
    'Vernon Valley, NY',
    'West Hills, NY', 
    'Wincoma, NY', 
    'Commack, NY', 
    'Fort Salonga, NY',  
    'Islip, NY', 
    'Brightwaters, NY', 
    'Islandia, NY', 
    'Ocean Beach, NY', 
    'Saltaire, NY', 
    'Bay Shore, NY', 
    'Bayport, NY', 
    'Baywood, NY', 
    'Bohemia, NY', 
    'Brentwood, NY', 
    'Central Islip, NY', 
    'East Islip, NY', 
    'Great River, NY', 
    'Islip, NY', 
    'Islip Terrace, NY', 
    'North Bay Shore, NY', 
    'North Great River, NY', 
    'Oakdale, NY', 
    'Ronkonkoma, NY', 
    'Sayville, NY', 
    'West Bay Shore, NY', 
    'West Islip, NY', 
    'West Sayville, NY', 
    'Holbrook, NY', 
    'Holtsville, NY', 
    'Hauppauge, NY',
    'Smithtown, NY', 
    'Head of the Harbor, NY', 
    'Nissequogue, NY', 
    'Village of the Branch, NY', 
    'Kings Park, NY', 
    'Nesconset, NY', 
    'Smithtown, NY', 
    'St. James, NY', 
    'Lake Ronkonkoma, NY', 
    'Commack, NY', 
    'Fort Salonga, NY', 
    'Hauppauge, NY', 
    'Brookhaven, NY', 
    'Belle Terre, NY', 
    'Bellport, NY', 
    'Lake Grove, NY', 
    'Old Field, NY', 
    'Patchogue, NY', 
    'Poquott, NY', 
    'Port Jefferson, NY', 
    'Shoreham, NY', 
    'Blue Point, NY', 
    'Brookhaven, NY', 
    'Canaan Lake, NY', 
    'Center Moriches, NY', 
    'Centereach, NY', 
    'Cherry Grove, NY', 
    'Coram, NY', 
    'Crystal Brook, NY', 
    'Cupsogue Beach, NY', 
    'Davis Park, NY', 
    'East Moriches, NY', 
    'East Patchogue, NY', 
    'East Setauket, NY', 
    'East Shoreham, NY', 
    'East Yaphank, NY', 
    'Farmingville, NY', 
    'Fire Island Pines, NY', 
    'Gordon Heights, NY', 
    'Hagerman, NY', 
    'Manor Park, NY', 
    'Manorville, NY', 
    'Mastic, NY', 
    'Mastic Acres, NY', 
    'Mastic Beach, NY', 
    'Medford, NY', 
    'Middle Island, NY', 
    'Miller Place, NY', 
    'Moriches, NY', 
    'Mount Sinai, NY', 
    'North Bellport, NY', 
    'North Patchogue, NY', 
    'Ocean Bay Park, NY', 
    'Old Mastic, NY', 
    'Point of Woods, NY', 
    'Port Jefferson Station, NY', 
    'Ridge, NY', 
    'Rocky Point, NY', 
    'Selden, NY', 
    'Setauket, NY', 
    'Shirley, NY', 
    'South Haven, NY', 
    'Sound Beach, NY', 
    'Stony Brook, NY', 
    'Strongs Neck, NY', 
    'Terryville, NY', 
    'Upton, NY', 
    'Water Island, NY', 
    'West Manor, NY', 
    'Yaphank, NY', 
    'Holbrook, NY', 
    'Holtsville, NY', 
    'Ronkonkoma, NY', 
    'Calverton, NY', 
    'Lake Ronkonkoma, NY', 
    'Eastport, NY', 
    'Lake Grove, NY', 
    'Southampton, NY', 
    'North Haven, NY', 
    'Quogue, NY', 
    'Sagaponack, NY', 
    'Southampton, NY', 
    'Westhampton Beach, NY', 
    'West Hampton Dunes, NY', 
    'Sag Harbor, NY', 
    'Bridgehampton, NY', 
    'East Quogue, NY', 
    'Flanders, NY', 
    'Hampton Bays, NY', 
    'Northampton, NY', 
    'North Sea, NY', 
    'Noyack, NY', 
    'Noyac, NY',
    'Quiogue, NY', 
    'Remsenburg, NY', 
    'Riverside, NY', 
    'Shinnecock Hills, NY', 
    'Speonk, NY', 
    'Tuckahoe, NY', 
    'Water Mill, NY', 
    'Watermill, NY',
    'Westhampton, NY', 
    'Eastport, NY', 
    'Riverhead, NY', 
    'Aquebogue, NY', 
    'Baiting Hollow, NY', 
    'Jamesport, NY', 
    'Northville, NY', 
    'Riverhead, NY', 
    'Wading River, NY', 
    'Calverton, NY', 
    'East Hampton, NY', 
    'East Hampton, NY', 
    'Sag Harbor, NY', 
    'Amagansett, NY', 
    'East Hampton North, NY', 
    'Montauk, NY', 
    'Napeague, NY', 
    'Northwest Harbor, NY', 
    'Springs, NY', 
    'Wainscott, NY',
    'Shelter Island, NY', 
    'Dering Harbor, NY', 
    'Shelter Island, NY', 
    'Shelter Island Heights, NY', 
    'Southold, NY', 
    'Greenport, NY', 
    'Cutchogue, NY', 
    'East Marion, NY', 
    'Fishers Island, NY', 
    'Greenport West, NY', 
    'Laurel, NY', 
    'Mattituck, NY', 
    'Orient, NY', 
    'New Suffolk, NY', 
    'Peconic, NY', 
    'Southold, NY', 
    'Fire Island, NY', 
    'Ocean Beach, NY', 
    'Saltaire, NY', 
    'Cherry Grove, NY', 
    'Fire Island Pines, NY', 
    'Davis Park, NY', 
    'Dunewood, NY', 
    'Fair Harbor, NY', 
    'Kismet, NY', 
    'Lonelyville, NY', 
    "Point o' Woods, NY", 
    'Water Island, NY', 
    'Atlantique, NY', 
    'Bayberry Dunes, NY', 
    'Corneille Estates, NY', 
    'Long Cove, NY', 
    'Ocean Bay Park, NY', 
    'Robbins Rest, NY', 
    'Seaview, NY', 
    'Watch Hill, NY', 
    'West Fire Island, NY'
]