NORTH_CAROLINA_CHARLOTTE = [
    "Charlotte, NC",
    "Cornelius, NC",
    "Davidson, NC",
    "Huntersville, NC",
    "Matthews, NC",
    "Mint Hill, NC",
    "Pineville, NC",
    "Stallings, NC",
    "Weddington, NC",
    "Caldwell, NC",
    "Hopewell, NC",
    "Mountain Island, NC",
    "Newell, NC",
    "Prosperity Village Area, NC",
    "Sterling, NC",
    "Berryhill, NC",
    "Charlotte, NC",
    "Clear Creek, NC",
    "Crab Creek, NC",
    "Crab Orchard, NC",
    "Deweese, NC",
    "Huntersville, NC",
    "Lemley, NC",
    "Long Creek, NC",
    "Mallard Creek, NC",
    "Morning Star, NC",
    "Paw Creek, NC",
    "Pineville, NC",
    "Providence, NC",
    "Sharon, NC",
    "Steele Creek, NC"
]

NORTH_CAROLINA_DURHAM = [
    "Durham, NC",
    "Raleigh, NC",
    "Chapel Hill, NC",
    "Morrisville, NC",
    "Carr, NC",
    "Lebanon, NC",
    "Mangum, NC",
    "Oak Grove, NC",
    "Triangle, NC",
    "Gorman, NC",
    "Rougemont, NC",
    "Bahama, NC",
    "Bethesda, NC",
    "Genlee, NC",
    "Lowe's Grove, NC",
    "Nelson, NC",
    "Braggtown, NC"
]

NORTH_CAROLINA_WAKE_COUNTY =  [
    "Durham, NC",
    "Raleigh, NC",
    "Apex, NC",
    "Cary, NC",
    "Fuquay-Varina, NC",
    "Garner, NC",
    "Holly Springs, NC",
    "Knightdale, NC",
    "Morrisville, NC",
    "Rolesville, NC",
    "Wake Forest, NC",
    "Wendell, NC",
    "Zebulon, NC",
    "Bartons Creek, NC",
    "Buckhorn, NC",
    "Cedar Fork, NC",
    "House Creek, NC",
    "Leesville, NC",
    "Little River, NC",
    "Marks Creek, NC",
    "Meredith, NC",
    "Middle Creek, NC",
    "Neuse, NC",
    "New Light, NC",
    "Panther Branch, NC",
    "St. Mary's, NC",
    "St. Matthew's, NC",
    "Swift Creek, NC",
    "White Oak, NC",
    "Asbury, NC",
    "Auburn, NC",
    "Banks, NC",
    "Barham, NC",
    "Bayleaf, NC",
    "Bonsai, NC",
    "Carpenter, NC",
    "Clegg, NC",
    "Eagle Rock, NC",
    "Falls, NC",
    "Feltonville, NC",
    "Five Points, NC",
    "Forestville, NC",
    "Fowlers Crossroads, NC",
    "Friendship, NC",
    "Green Level, NC",
    "Holland, NC",
    "Hollemans Crossroads, NC",
    "Hopkins, NC",
    "Kennebec, NC",
    "Lassiter, NC",
    "Leesville, NC",
    "Lizard Lick, NC",
    "Macks Village, NC",
    "McCullers, NC",
    "McCullers Crossroads, NC",
    "Medfield, NC",
    "Mount Pleasant, NC",
    "Neuse, NC",
    "New Hill, NC",
    "New Hope, NC",
    "New Light, NC",
    "Purnell, NC",
    "Riley Hill, NC",
    "Sandy Plain, NC",
    "Shotwell, NC",
    "Six Forks, NC",
    "Stony Hill, NC",
    "Swift Creek, NC",
    "Wake Crossroads, NC",
    "Walkers Crossroad, NC",
    "Westover, NC",
    "Wilborn, NC",
    "Williams Crossroads, NC",
    "Willow Spring, NC",
    "Wyatt, NC"
]

NORTH_CAROLINA_WINSTON_SALEM = [
    "Winston-Salem, NC",
    "High Point, NC",
    "King, NC",
    "Bethania, NC",
    "Kernersville, NC",
    "Lewisville, NC",
    "Rural Hall, NC",
    "Walkertown, NC",
    "Clemmons, NC",
    "Tobaccoville, NC",
    "Germantown, NC",
    "Abbots Creek, NC",
    "Belews Creek, NC",
    "Bethania, NC",
    "Broadbay, NC",
    "Clemmonsville, NC",
    "Kernersville, NC",
    "Lewisville, NC",
    "Middle Fork I, NC",
    "Middle Fork II Township, NC",
    "Old Richmond, NC",
    "Old Town, NC",
    "Salem Chapel, NC",
    "South Fork, NC",
    "Vienna, NC",
    "Winston, NC",
    "Bethabara, NC",
    "Donnaha, NC",
    "Dozier, NC",
    "Pfafftown, NC",
    "Seward, NC",
    "Stanleyville, NC",
    "Union Cross, NC",
]