OHIO_AKRON = [
    "Akron, OH",
    "Barberton, OH",
    "Cuyahoga Falls, OH",
    "Fairlawn, OH",
    "Green, OH",
    "Hudson, OH",
    "Mogadore, OH",
    "Montrose-Ghent, OH",
    "Munroe Falls, OH",
    "Norton, OH",
    "Silver Lake, OH",
    "Stow, OH",
    "Tallmadge, OH"
    "Springfield Township, OH",
    "Coventry Township, OH",
    "Copley Township, OH",
    "Bath Township, OH",
    "Aurora, OH",
    "Brimfield Township, OH",
    "Copley Township, OH",
    "Coventry Township, OH",
    "Hudson, OH",
    "Macedonia, OH",
    "New Franklin, OH",
    "Norton, OH",
    "Portage Lakes, OH",
    "Ravenna, OH",
    "Sagamore Hills Township, OH",
    "Streetsboro, OH",
    "Twinsburg, OH",
    "Franklin Township, OH",
    "Munroe Falls, OH",
    "Northfield Center Township, OH",
    "Randolph Township, OH",
    "Ravenna Township, OH",
    "Richfield Township, OH",
    "Rootstown Township, OH",
    "Shalersville Township, OH",
    "Suffield Township, OH",
    "Atwater Township, OH",
    "Boston Heights, OH",
    "Boston Township, OH",
    "Brimfield, OH",
    "Charlestown Township, OH",
    "Clinton, OH",
    "Deerfield Township, OH",
    "Edinburg Township, OH",
    "Freedom Township, OH",
    "Garrettsville, OH",
    "Hiram, OH",
    "Hiram Township, OH",
    "Lakemore, OH",
    "Mantua, OH",
    "Mantua Township, OH",
    "Nelson Township, OH",
    "Palmyra Township, OH",
    "Northfield, OH",
    "Paris Township, OH",
    "Reminderville, OH",
    "Richfield, OH",
    "Silver Lake, OH",
    "Twinsburg Township, OH",
    "Windham, OH",
    "Windham Township, OH",
    "Brady Lake, OH",
    "Peninsula, OH",
    "Pigeon Creek, OH",
    "Sugar Bush Knolls, OH",
    "Diamond, OH",
    "Ghent, OH",
    "Hammond's Corners, OH",
    "Montrose, OH",
    "Wayland, OH"
]

OHIO_CINCINNATI = [
    "Blue Ash, OH",
    "Cheviot, OH",
    "Cincinnati, OH",
    "Deer Park, OH",
    "Fairfield, OH",
    "Forest Park, OH",
    "Harrison, OH",
    "Village of Indian Hill, OH",
    "Loveland, OH",
    "Madeira, OH",
    "Milford, OH",
    "Montgomery, OH",
    "Mount Healthy, OH",
    "North College Hill, OH",
    "Norwood, OH",
    "Reading, OH",
    "Sharonville, OH",
    "Springdale, OH",
    "Wyoming, OH",
    "Addyston, OH",
    "Amberley, OH",
    "Arlington Heights, OH",
    "Cleves, OH",
    "Elmwood, OH",
    "Evendale, OH",
    "Fairfax, OH",
    "Glendale, OH",
    "Golf Manor, OH",
    "Greenhills, OH",
    "Lincoln Heights, OH",
    "Lockland, OH",
    "Mariemont, OH",
    "Newtown, OH",
    "North Bend, OH",
    "Silverton, OH",
    "St. Bernard, OH",
    "Terrace Park, OH",
    "Woodlawn, OH",
    "Anderson Township, OH",
    "Colerain Township, OH",
    "Columbia Township, OH",
    "Crosby Township, OH",
    "Delhi Township, OH",
    "Green Township, OH",
    "Harrison Township, OH",
    "Miami Township, OH",
    "Springfield Township, OH",
    "Sycamore Township, OH",
    "Sycamore Township, OH",
    "Symmes Township, OH",
    "Whitewater Township, OH",
    "Blue Jay, OH",
    "Brecon, OH",
    "Bridgetown, OH",
    "Camp Dennison, OH",
    "Cherry Grove, OH",
    "Coldstream, OH",
    "Concorde Hills, OH",
    "Covedale, OH",
    "Delhi Hills, OH",
    "Delshire, OH",
    "Dent, OH",
    "Dillonvale, OH",
    "Dry Ridge, OH",
    "Dry Run, OH",
    "Dunlap, OH",
    "Elizabethtown, OH",
    "Finneytown, OH",
    "Forestville, OH",
    "Fruit Hill, OH",
    "Grandview, OH",
    "Groesbeck, OH",
    "Highpoint, OH",
    "Hooven, OH",
    "Kenwood, OH",
    "Loveland Park, OH",
    "Mack, OH",
    "Madison Place, OH",
    "Miami Heights, OH",
    "Miamitown, OH",
    "Monfort Heights, OH",
    "Mount Healthy Heights, OH",
    "New Baltimore, OH",
    "New Burlington, OH",
    "New Haven, OH",
    "Northbrook, OH",
    "Northgate, OH",
    "Plainville, OH",
    "Pleasant Hills, OH",
    "Pleasant Run, OH",
    "Pleasant Run Farms, OH",
    "Remington, OH",
    "Ridgewood, OH",
    "Rossmoyne, OH",
    "Salem Heights, OH",
    "Shawnee, OH",
    "Sherwood, OH",
    "Sixteen Mile Stand, OH",
    "Skyline Acres, OH",
    "Taylor Creek, OH",
    "Turpin Hills, OH",
    "White Oak, OH",
    "Colerain Heights, OH",
    "Mount Saint Joseph, OH"
]

OHIO_MOUNT_VERNON = [
    "Mount Vernon, OH",
    "Centerburg, OH",
    "Danville, OH",
    "Fredericktown, OH",
    "Gambier, OH",
    "Gann, OH",
    "Martinsburg, OH",
    "Utica, OH",
    "Berlin, OH",
    "Brown, OH",
    "Butler, OH",
    "Clay, OH",
    "Clinton, OH",
    "College, OH",
    "Harrison, OH",
    "Hillar, OH",
    "Howard, OH",
    "Jackson, OH",
    "Jefferson, OH",
    "Liberty, OH",
    "Middlebury, OH",
    "Milford, OH",
    "Miller, OH",
    "Monroe, OH",
    "Morgan, OH",
    "Morris, OH",
    "Pike, OH",
    "Pleasant, OH",
    "Union, OH",
    "Wayne, OH",
    "Apple Valley, OH",
    "Bladensburg, OH",
    "Howard, OH",
    "South Mount Vernon, OH",
    "Amity, OH",
    "Ankenytown, OH",
    "Artanna OH",
    "Bangs, OH",
    "Batemantown, OH",
    "Brandon, OH",
    "Five Corners, OH",
    "Green Valley, OH",
    "Greer, OH",
    "Hunt, OH",
    "Jelloway, OH",
    "Knox, OH",
    "Lock, OH",
    "Lucerne, OH",
    "Millwood, OH",
    "Monroe Mills, OH",
    "Morgan Center, OH",
    "Mt. Liberty, OH",
    "North Liberty, OH",
    "Palmyra, OH",
    "Pipesville, OH",
    "Rich Hill, OH",
    "Rossville, OH",
    "Waterford, OH",
    "Zuck, OH"
]