SOUTH_CAROLINA_BEAUFORT_COUNTY = [
    "Beaufort",
    "Bluffton",
    "Hilton Head Island",
    "Port Royal",
    "Yemassee",
    "Burton",
    "Laurel Bay",
    "Shell Point",
    "Brighton Beach",
    "Dale",
    "Frogmore",
    "Lady's Island",
    "Lobeco",
    "Parris Island",
    "Pocotaligo",
    "Pritchardville",
    "Sheldon",
    "Sun City",
    "Seabrook",
    "Barataria Island",
    "Bull Island",
    "Callawassie Island",
    "Cane Island",
    "Coosaw Island",
    "Dataw Island",
    "Daufuskie Island",
    "Fripp Island",
    "Grays Hills",
    "Harbor Island",
    "Hilton Head Island",
    "Hunting Island",
    "Lady's Island",
    "Lemon Island",
    "Little Capers Island",
    "Morgan Island",
    "Parris Island",
    "Poppy Hill",
    "Port Royal Island",
    "Pritchard Island",
    "Saint Helena Island",
    "Spring Island",
    "St. Philips Island",
    "Warsaw Island"
]

SOUTH_CAROLINA_CHARLESTON = [
    "Charleston",
    "North Charleston",
    "Mount Pleasant",
    "Summerville",
    "James Island",
    "Hollywood",
    "Isle of Palms",
    "Ravenel",
    "Folly Beach",
    "Lincolnville",
    "Sullivan's Island",
    "Seabrook Island",
    "Kiawah Island",
    "Awendaw",
    "Meggett",
    "McClellanville",
    "Rockville",
    "West Ashley",
    "Ladson",
    "Charleston",
    "North Charleston",
    "Goose Creek",
    "Mount Pleasant",
    "Summerville",
    "Hanahan",
    "James Island",
    "Johns Island",
    "Ladson",
    "Moncks Corner",
    "Hollywood",
    "Awendaw",
    "Folly Beach",
    "Isle of Palms",
    "Kiawah Island",
    "Lincolnville",
    "Meggett",
    "Ravenel",
    "Ridgeville",
    "Seabrook Island",
    "St. George",
    "St. Stephen",
    "Sullivan's Island",
    "Bonneau",
    "Harleyville",
    "Jamestown",
    "McClellanville",
    "Reevesville",
    "Rockville",
    "Cross",
    "Gumville",
    "Huger",
    "Pineville",
    "Wadmalaw Island"
]
