TENNESSEE_NASHVILLE = [
    "Nashville, TN",
    "12 South",
    "8th Ave S",
    "Belmont Blvd",
    "Berry Hill",
    "Demonbreun Hill",
    "Downtown",
    "East Nashville",
    "Edgehill",
    "Elliston Place",
    "Germantown",
    "Green Hills",
    "Gulch",
    "Hillsboro Village",
    "Marathon Village",
    "Melrose",
    "Midtown",
    "Sobro",
    "Sylvan Park",
    "The Nations",
    "Wedgewood-Houston",
    "West End",
    "Belle Meade, TN",
    "Berry Hill, TN",
    "Forest Hills, TN",
    "Goodlettsville, TN",
    "Oak Hill, TN",
    "Ridgetop, TN",
    "Antioch, TN",
    "Bellevue, TN",
    "Donelson, TN",
    "Hermitage, TN",
    "Inglewood, TN",
    "Joelton, TN",
    "Lakewood, TN",
    "Madison, TN",
    "Old Hickory, TN",
    "Pasquo, TN",
    "Whites Creek, TN",
    "Una, TN",
    "Murfreesboro, TN",
    "Franklin, TN",
    "Bellevue, TN",
    "Hendersonville, TN",
    "Smyrna, TN",
    "Spring Hill, TN",
    "Brentwood, TN",
    "Columbia, TN",
    "Donelson, TN",
    "Gallatin, TN",
    "Hermitage, TN",
    "La Vergne, TN",
    "Lebanon, TN",
    "Madison, TN",
    "Mount Juliet, TN",
    "Dickson, TN",
    "Goodlettsville, TN",
    "Nolensville, TN",
    "Old Hickory, TN",
    "Portland, TN",
    "Springfield, TN",
    "White House, TN",
    "Ashland City, TN",
    "Belle Meade, TN",
    "Bethpage, TN",
    "Burns, TN",
    "Carthage, TN",
    "Charlotte, TN",
    "Coopertown, TN",
    "Cross Plains, TN",
    "Fairview, TN",
    "Forest Hills, TN",
    "Gordonville, TN",
    "Greenbrier, TN",
    "Green Hill, TN",
    "Hartsville, TN",
    "Kingston Springs, TN",
    "Lafayette, TN",
    "Lakewood, TN",
    "Millersville, TN",
    "Mount Pleasant, TN",
    "Oak Hill, TN",
    "Pegram, TN",
    "Pleasant View, TN",
    "Red Boiling Springs, TN",
    "Ridgetop, TN",
    "Rural Hill, TN",
    "South Carthadge, TN",
    "Thompson's Station, TN",
    "Watertown, TN",
    "Westmoreland, TN",
    "White Bluff, TN",
    "Woodbury, TN",
    "Adams, TN",
    "Auburntown, TN",
    "Berry Hill, TN",
    "Cedar Hill, TN",
    "Eagleville, TN",
    "Mitchellville, TN",
    "Orlinda, TN",
    "Slayden, TN",
    "Vanleer, TN",
    "Walterhill, TN"
]