TEXAS_AMARILLO = [
"Amarillo, TX",
"Canyon, TX",
"Claude, TX",
"Panhandle, TX",
"White Deer, TX",
"Groom, TX",
"Happy, TX",
"Lake Tanglewood, TX",
"Skellytown, TX",
"Bishop Hills, TX",
"Palisades, TX",
"Timbercreek Canyon, TX",
"Bushland, TX",
"Goodnight, TX",
"Umbarger, TX",
"Washburn, TX",
"Wayside, TX"
]

TEXAS_AUSTIN = [
    "Central Austin",
    "Bryker Woods",
    "Caswell Heights",
    "Downtown Austin",
    "Eastwoods",
    "Hancock",
    "Heritage",
    "Hyde Park",
    "Hyde Park Historic District",
    "Clarksville Historic District",
    "Judges' Hill",
    "Lower Waller Creek",
    "North University",
    "Oakmont Heights",
    "Old Enfield",
    "Old Pecan Street",
    "Old West Austin",
    "Original Austin",
    "Original West University",
    "Pemberton Heights",
    "Ridgelea",
    "Ridegetop",
    "Rosedale",
    "Shoal Crest",
    "Shawdown Lawn Historic District",
    "West Downtown",
    "North Austin",
    "Allandale",
    "Balcones Woods",
    "Barrington Oaks",
    "Battle Bend Springs",
    "Brentwood",
    "Crestview",
    "Estates of Brentwood",
    "Hancock",
    "Highland",
    "North Burnet",
    "North Campus",
    "North Lamar",
    "North Shoal Creek",
    "Saint John",
    "Wooten",
    "Windsor Hills",
    "Windsor Park",
    "Canyon Creek",
    "Great Hills/Arboretum",
    "Northwest Hills",
    "Copperfield",
    "Steiner Ranch",
    "Wells Branch",
    "East Austin",
    "Central East Austin",
    "East Cesar Chavez",
    "East Congress",
    "East End",
    "French Place",
    "Govalle",
    "Gracy Woods",
    "Holly",
    "Mueller",
    "West Austin",
    "Far West",
    "Tarrytown",
    "West Congress",
    "West End",
    "West Line Historic District",
    "South Austin",
    "Barton Creek",
    "Barton Hills",
    "Bouldin Creek",
    "Dawson",
    "Galindo",
    "South Congress",
    "South Lamar",
    "South River City",
    "Spyglass-Barton's Bluffs",
    "Travis Heights",
    "Zilker",
    "East Riverside-Oltorf",
    "Montopolis",
    "Pleasant Valley",
    "Dove Springs",
    "Onion Creek",
    "South Manchaca",
    "Southeast Austin",
    "Southpark Meadows",
    "Cherry Creek",
    "Circle C Ranch",
    "Oak Hill",
    "Far South Austin/Slaughter-Manchaca",
    "Kincheonville",
    "The Ridge at Lantana",
    "Maple Run",
    "Sendera",
    "Shady Hollow",
    "Sunset Valley",
    "Tanglewood Forest",
    "Travis County",
    "Westgate",
    "Woodstone Village",
    "Round Rock, TX",
    "Cedar Park, TX",
    "Georgetown, TX",
    "Pflugerville, TX",
    "San Marcos, TX",
    "Leander, TX",
    "Kyle, TX",
    "Hutto, TX",
    "Brushy Creek, TX",
    "Bastrop, TX",
    "Bee Cave, TX",
    "Buda, TX",
    "Camp Swift, TX",
    "Dripping Springs, TX",
    "Elgin, TX",
    "Jollyville, TX",
    "Lago Vista, TX",
    "Lakeway, TX",
    "Lockhart, TX",
    "Luling, TX",
    "Manor, TX",
    "Shady Hollow, TX",
    "Taylor, TX",
    "Wells Branch",
    "Bartlett, TX",
    "Barton Creek, TX",
    "Briarcliff, TX",
    "Circle D-KC Estates, TX",
    "Florence, TX",
    "Garfield, TX",
    "Granger, TX",
    "Hudson Bend, TX",
    "Jarrell, TX",
    "Jonestown, TX",
    "Liberty Hill, TX",
    "Lost Creek, TX",
    "Martindale, TX",
    "Point Venture, TX",
    "Rollingwood, TX",
    "Serenada, TX",
    "Smithville, TX",
    "The Hills, TX",
    "Thorndale, TX",
    "Uhland, TX",
    "West Lake Hills, TX",
    "Wimberley, TX",
    "Windemere, TX",
    "Woodcreek, TX",
    "Wyldwood, TX",
    "Bear Creek, TX",
    "Coupland, TX",
    "Creedmoor, TX",
    "Hays, TX",
    "Mountain City, TX",
    "Mustang Ridge, TX",
    "Niederwald, TX",
    "San Leanna, TX",
    "Sunset Valley, TX",
    "Thrall, TX",
    "Volente, TX",
    "Webberville, TX",
    "Weir, TX",
    "Alum Creek, TX",
    "Andice, TX",
    "Butler, TX",
    "Cedar Creek, Tx",
    "Colorado, TX",
    "Corn Hill, TX",
    "Dale, TX",
    "Delhi, TX",
    "Driftwood, TX",
    "Flower Hill, TX",
    "Hills, TX",
    "Hornsby Bend ETJ, TX",
    "Jeddo, TX",
    "Kirtley, TX",
    "Manchca, TX",
    "Maxwell, TX",
    "McDade, TX",
    "McNeil, TX",
    "Norman's Crossing, TX",
    "Paige, TX",
    "Prairie Lea, TX",
    "Sayersville, TX",
    "Schwertner, TX",
    "String Prarie, TX",
    "Red Rock, TX",
    "Rosanky, T",
    "Theon, TX",
    "Togo, TX",
    "Upton, TX"
    "Walburg, TX",
    "Waterloo, TX"
]

TEXAS_BEAUMONT = [
    "Beaumont, TX",
    "Bevil Oaks, TX",
    "China, TX",
    "Groves, TX",
    "Nederland, TX",
    "Nome, TX",
    "Port Arthur, TX",
    "Port Neches, TX",
    "Taylor Landing, TX",
    "Central Gardens, TX",
    "Fannett, TX",
    "Beauxart, TX",
    "Cheek, TX",
    "Dowling, TX",
    "Hamshire, TX",
    "LaBelle, TX",
    "Viterbo, TX",
    "Beaumont, TX",
    "Port Arthur, TX",
    "Orange, TX",
    "Nederland, TX",
    "Groves, TX",
    "Port Neches, TX",
    "Vidor, TX",
    "Lumberton, TX",
    "Bevil Oaks, TX",
    "Bridge City, TX",
    "Central Gardens, TX",
    "China, TX",
    "Mauriceville, TX",
    "Nome, TX",
    "Pine Forest, TX",
    "Pinehurst, TX",
    "Pinewood Estates, TX",
    "Rose City, TX",
    "Rose Hill Acres, TX",
    "Silsbee, TX",
    "Sour Lake, TX",
    "Taylor Landing, TX",
    "West Orange, TX",
    "Batson, TX",
    "Fannett, TX",
    "Forest Heights, TX",
    "Hamshire, TX",
    "Honey Island, TX",
    "LaBelle, TX",
    "Little Cypress, TX",
    "Orangefield, TX",
    "Saratoga, TX",
    "Thicket, TX",
    "Village Mills, TX",
    "Votaw, TX",
    "Wildwood, TX"
]

TEXAS_DALLAS = [
    'Downtown Dallas', 
    'Baylor District', 
    'The Cedars', 
    'Civic Center District', 
    'Dallas Arts District', 
    'Dallas Farmers Market', 
    'Deep Ellum', 
    'Design District', 
    'Main Street District', 
    'Reunion District', 
    'Riverfront District', 
    'South Side', 
    'Thanksgiving Commercial Center', 
    'Uptown', 
    'Victory Park', 
    'West End Historic District', 
    'East Dallas',
    'Alger Park/Ash Creek', 
    'Belmont', 
    'Buckner Terrace', 
    'Caruth Terrace',
    'Casa Linda Estates', 
    'Casa Linda Park',
    'Casa View', 
    'Casa View Haven', 
    'Claremont', 
    'Claremont Park', 
    'Eastwood', 
    'Edgemont Park', 
    'Forest Hills', 
    'Gaston Park',
    'Greenland Hills', 
    'Hillridge', 
    'Hollywood Heights', 
    'Junius Heights',
    'Lake Park Estates', 
    'Lakewood',
    'Lakewood Heights',
    'Lakewood Trails', 
    'Little Forest Hills', 
    'Lochwood', 
    'Lower Greenville', 
    'North Stonewall Terrace', 
    'Old Lake Highlands',
    'Ridgewood Park', 
    'Santa Monica', 
    'Stonewall Terrace', 
    'University Meadows',
    'Vickery Place',
    'White Rock', 
    'Wilshire Heights', 
    'Old East Dallas', 
    'Baylor/Meadows', 
    'Belmont Park',
    'Bryan Place', 
    'Deep Ellum',
    'Munger Place Historic District', 
    "Peak's Suburban Addition",
    'Swiss Avenue',
    'Abrams Place', 
    "Alexander's Village", 
    'Boundbrook Oaks Estates', 
    'Chimney Hill', 
    'Copperfield Community', 
    'Country Forest', 
    'Forest Highlands', 
    'Glen Oaks', 
    'Hamilton Park', 
    'Highlands West', 
    'Highland Meadows', 
    'High Oaks Addition', 
    'Jackson Meadow',
    'L Streets', 
    'Lake Highlands', 
    'Lake Highlands Estates', 
    'Lake Highlands North', 
    'Lake Highlands Square', 
    'Lake Ridge Estates',
    'Merriman Park Estates', 
    'Merriman Park North', 
    'Moss Farm', 
    'Moss Meadows',
    'Northwood Heights', 
    'Oak Highlands', 
    'Oak Tree Village', 
    'Pebble Creek', 
    'Richland Park Estates', 
    'Rolling Trails', 
    'Royal Highlands', 
    'Royal Highlands Village', 
    'Stultz Road', 
    'Town Creek', 
    'Royal Lane Village', 
    'Walnut Creek Estates',
    'Whispering Hills', 
    'White Rock Valley',
    'Woodbridge', 
    'Woodlands on the Creek', 
    'University Manor',
    'University Terrace',
    'Urban Reserve',
    'North Dallas',
    'Bent Tree', 
    'Bluffview',
    'Devonshire',
    'Elm Thicket',
    'Greenway Parks', 
    'Preston Center',
    'Preston Hollow', 
    'Vickery Meadows', 
    'Far North Dallas', 
    'Bent Tree',
    'Preston Highlands', 
    'Timberglen', 
    'Far North Dallas', 
    'Melshire Estates', 
    'Northwood Hills', 
    'Platinum Corridor', 
    'Northwest Dallas', 
    'Arlington Park', 
    'Asian Trade District', 
    'Bachman', 
    'Design District', 
    'Love Field', 
    'Midway Hollow', 
    'Shannon Estates', 
    'Stemmons Corridor', 
    'Oak Cliff', 
    'Arcadia Park', 
    'Beckley Club Estates', 
    'Bishop Arts District', 
    'Elmwood', 
    'Stevens Park Estates', 
    'Stevens Park Village', 
    "Tenth Street Freedman's Town", 
    'Western Park',
    'Winnetka Heights',
    'Wynnewood', 
    'East Kessler Park', 
    'Kessler Highlands', 
    'Kessler Park Estates', 
    'Kessler Plaza', 
    'Kessler Square', 
    'West Kessler', 
    'Kidd Springs',
    'Kings Highway Conservation District',
    'Lake Cliff', 
    'L.O. Daniel', 
    'Redbird', 
    'Elderwoods/Elderoaks', 
    'Glenn Oaks', 
    'Wynnewood Hills', 
    'Oak Lawn', 
    'Cityplace', 
    'Uptown',
    'International Center', 
    'LoMac', 
    'Knox Park', 
    'Perry Heights', 
    'State Thomas',
    'Turtle Creek', 
    'Oak Lawn',
    'Victory Park', 
    'West Village', 
    'Southeast Dallas', 
    "Arnold's Station", 
    'Buckner Park', 
    'Cedar Run', 
    'El Barrio (Little Mexico)', 
    'Elam', 
    'Fireside', 
    'Kleberg', 
    'Lake June', 
    'Parkdale', 
    'Pemberton Hill', 
    'Piedmont', 
    'Pleasant Grove', 
    'Pleasant Hills', 
    'Pleasant Mound', 
    'Riverway Estates/Bruton Terrace', 
    'Rylie', 
    'Seagoville/Dallas', 
    'Scyene', 
    'Spruce Square', 
    'Urbandale', 
    'Woodland Springs', 
    'Far South Dallas', 
    'Bonton', 
    'Dixon Circle', 
    'Highland Hills', 
    'South Central Dallas', 
    'Cedar Crest', 
    'Skyline Heights', 
    'Old South Dallas/Fair Park', 
    'Exposition Park', 
    'Fair Park', 
    'Mill City', 
    'Owenwood', 
    'Jubilee Park', 
    'Dolphin Heights', 
    'Wheatley Place', 
    'Monterey Gardens', 
    'Edgewood', 
    'South Boulevard/Park Row',
    'South Boulevard/Park Row', 
    'Magnolia Park', 
    'Alta Park', 
    'West Dallas', 
    'Eagle Ford', 
    'Greenleaf Village', 
    'La Bajada',
    "La L'aceate", 
    'La Loma', 
    'Lake West', 
    'Ledbetter Gardens', 
    'Los Altos', 
    'Muncie', 
    'Western Heights', 
    'Westmoreland Heights', 
    'Trinity Grove', 
    "Carrollton, TX",
    "Cedar Hill, TX",
    "Combine, TX",
    "Coppell, TX",
    "Dallas, TX",
    "Ferris, TX",
    "Garland, TX",
    "Glenn Heights, TX",
    "Grand Prarie, TX",
    "Grapevine, TX",
    "Lewisville, TX",
    "Mesquite, TX",
    "Ovilla, TX",
    "Richardson, TX",
    "Rowlett, TX",
    "Sachse, TX",
    "Seagoville, TX",
    "Wylie, TX",
    "Balch Springs, TX",
    "Cockrell Hill, TX",
    "DeSoto, TX",
    "Duncanville, TX",
    "Farmers Branch, TX",
    "Hutchins, TX",
    "Irving, TX",
    "Lancaster, TX",
    "University Park, TX",
    "Wilmer, TX",
    "Addison, TX",
    "Highland Park, TX",
    "Sunnyvale, TX",
    "Bear Creek Ranch, TX",
    "Sand Branch, TX",
    "Alpha, TX",
    "Buckingham, TX",
    "Cedar Springs, TX",
    "Duck Creek, TX",
    "East Dallas, TX",
    "Embree, TX",
    "Fruitdale, TX",
    "Hatterville, TX",
    "Hord's Ridge, TX",
    "Kleberg, TX",
    "La Reunion, TX",
    "Letot, TX",
    "Liberty Grove, TX",
    "Lisbon, TX",
    "Little Egypt, TX",
    "Long Creek, TX",
    "Meaders, TX",
    "New Hope, TX",
    "Noel Junction, TX",
    "Oak Cliff, TX",
    "Penn Springs, TX",
    "Pleasant Grove, TX",
    "Preston Hollow, TX",
    "Renner, TX",
    "Rylie, TX",
    "Scyene, TX",
    "Trinity Mills, TX",
    "Tripp, TX",
    "Carrollton, TX",
    "Celina, TX",
    "Dallas, TX",
    "Frisco, TX",
    "Garland, TX",
    "Josephine, TX",
    "Plano, TX",
    "Prosper, TX",
    "Richardson, TX",
    "Royse City, TX",
    "Sachse, TX",
    "Van Alstyne, TX",
    "Wylie, TX",
    "Allen, TX",
    "Anna, TX",
    "Blue Ridge, TX",
    "Celina, TX",
    "Farmersville, TX",
    "Lavon, TX",
    "Lowry Crossing, TX",
    "Lucas, TX",
    "McKinney, TX",
    "Melissa, TX",
    "Murphy, TX",
    "Nevada, TX",
    "Parker, TX",
    "Princeton, TX",
    "Weston, TX",
    "Fairview, TX",
    "Hebron, TX",
    "New Hope, TX",
    "St. Paul, TX",
    "Seis Lagos, TX",
    "Westminster, TX",
    "Altoga, TX",
    "Arnold, TX",
    "Berverly Hill, TX",
    "Bloomdale, TX",
    "Branch, TX",
    "Buckner, TX",
    "Chambersville, TX",
    "Chambliss, TX",
    "Clear Lake, TX",
    "Climax, TX",
    "Collin, TX",
    "Copeville, TX",
    "Cowley, TX",
    "Culleoka, TX",
    "Deep Water Point Estates, TX",
    "Desert, TX",
    "Fayburg, TX",
    "Forest Grove, TX",
    "Frognot, TX",
    "Kelly, TX",
    "Lavon Beach Estates, TX",
    "Lavon Shores Estates, TX",
    "Little Ridge, TX",
    "Marilee, TX",
    "Milligan, TX",
    "Millwood, TX",
    "New Mesquite, TX",
    "Pebble Beach Sunset Acres, TX",
    "Pecan Grove, TX",
    "Pike, TX",
    "Rhea Mills, TX",
    "Rockhill, TX",
    "Roland, TX",
    "Sedalia, TX",
    "Snow Hill, TX",
    "Trinity Park, TX",
    "Valdasta, TX",
    "Verona, TX",
    "Walnut Grove, TX",
    "Wetsel, TX",
    "Winningkoff, TX",
    "Yucote Acres, TX",
    "Lebanon, TX",
    "Lolaville, TX",
    "Renner, TX",
    "Shepton, TX",
    "Biggers, TX",
    "Nickelville, TX",
    "Parris, TX",
    "Carrollton, TX",
    "Celina, TX",
    "Coppell, TX",
    "Dallas, TX",
    "Fort Worth, TX",
    "Frisco, TX",
    "Grapevine, TX",
    "Haslet, TX",
    "Lewisville, TX",
    "Plano, TX",
    "Southlake, TX",
    "Aubrey, TX",
    "Corinth, TX",
    "Denton, TX",
    "Highland Village, TX",
    "Justin, TX",
    "Krugerville, TX",
    "Krum, TX",
    "Lake Dallas, TX",
    "Lakewood Village, TX",
    "Little Elm, TX",
    "Oak Point, TX",
    "Pilot Point, TX",
    "Roanoke, TX",
    "Sanger, TX",
    "The Colony, TX",
    "Flower Mound, TX",
    "Hebron, TX",
    "Prosper, TX",
    "Trophy Club, TX",
    "Westlake, TX",
    "Argyle, TX",
    "Bartonville, TX",
    "Copper Canyon, TX",
    "Cross Roads, TX",
    "DISH, TX",
    "Double Oak, TX",
    "Draper, TX",
    "Hackberry, TX",
    "Hickory Creek, TX",
    "Lincoln Park, TX",
    "Northlake, TX",
    "Northlake, TX",
    "Ponder, TX",
    "Providence Village, TX",
    "Shady Shores, TX",
    "Frisco West, TX",
    "Lantana, TX",
    "Paloma Creek, TX",
    "Paloma Creek South, TX",
    "Savannah, TX",
    "Alliance, TX",
    "Bolivar, TX",
    "Drop, TX",
    "Navo, TX",
    "Elizabethtown, TX",
    "Combine, TX",
    "Dallas, TX",
    "Heath, TX",
    "Mesquite, TX",
    "Poetry, TX",
    "Seagoville, TX",
    "Seven Points, TX",
    "Cottonwood, TX",
    "Crandall, TX",
    "Forney, TX",
    "Kaufman, TX",
    "Kemp, TX",
    "Terrell, TX",
    "Mabank, TX",
    "Oak Grove, TX",
    "Oak Ridge, TX",
    "Post Oak Bend City, TX",
    "Scurry, TX",
    "Talty, TX",
    "Grays Prairie, TX",
    "Rosser, TX",
    "Elmo, TX",
    "Travis Ranch, TX",
    "Ables Springs, TX",
    "Abner, TX",
    "Becker, TX",
    "Cartwright, TX",
    "Cedar Grove, TX",
    "Cedarvale, TX",
    "Cobb, TX",
    "College Mound, TX",
    "Colquitt, TX",
    "Frog, TX",
    "Gastonia, TX",
    "Heartland, TX",
    "Hiram, TX",
    "Jiba, TX",
    "Lawrence, TX",
    "Lively, TX",
    "Lone Star, TX",
    "Markout, TX",
    "McCoy, TX",
    "Ola, TX",
    "Peeltown, TX",
    "Prairieville, TX",
    "Rand, TX",
    "Stubbs, TX",
    "Styx, TX",
    "Tolosa, TX",
    "Union Valley, TX",
    "Warsaw, TX",
    "Wilson, TX",
    "Dallas, TX",
    "Fate, TX",
    "Garland, TX",
    "Heath, TX",
    "McLendon-Chisholm, TX",
    "Mobile City, TX",
    "Rockwall, TX",
    "Rowlett, TX",
    "Royse City, TX",
    "Wylie, TX"
]

TEXAS_EL_PASO = [
    "Agua Dulce, TX",
    "Anthony, TX",
    "Butterfield, TX",
    "Canutillo, TX",
    "Clint, TX",
    "Fabens, TX",
    "Fort Bliss, TX",
    "Homestead Meadows North, TX",
    "Homestead Meadows South, TX",
    "El Paso, TX",
    "Horizon City, TX",
    "Montana Vista, TX",
    "Morning Glory, TX",
    "Newman, TX",
    "Prado Verde, TX",
    "San Elizario, TX",
    "Socorro, TX",
    "Tornillo, TX",
    "Vinton, TX",
    "Westway, TX",
    "Anthony, NM",
    "Chamberino, NM",
    "Chaparral, NM",
    "Doña Ana, NM",
    "Hatch, NM",
    "La Mesa, NM",
    "Las Cruces, NM",
    "Mesilla, NM",
    "Mesquite, NM",
    "Organ, NM",
    "Picacho, NM",
    "Radium Springs, NM",
    "Rincon, NM",
    "Salem, NM",
    "Santa Teresa, NM",
    "Sunland Park, NM",
    "University Park, NM",
    "Vado, NM",
    "White Sands, NM",
    "Allamore, TX",
    "Dell City, TX",
    "Salt Flat, TX",
    "Sierra Blanca, TX",
    "Anthony, TX",
    "Clint, TX",
    "Dell City, TX",
    "Horizon City, TX",
    "Socorro, TX",
    "Vinton, TX",
    "Agua Dulce, TX",
    "Butterfield, TX",
    "Canutillo, TX",
    "Fabens, TX",
    "Fort Bliss, TX",
    "Fort Hancock, TX",
    "Homestead Meadows North, TX",
    "Homestead Meadows South, TX",
    "Morning Glory, TX",
    "Prado Verde, TX",
    "San Elizario, TX",
    "Sierra Blanca, TX",
    "Sparks, TX",
    "Tornillo, TX",
    "Westway, TX",
    "Allamore, TX",
    "Montana Vista, TX",
    "Newman, TX",
    "Salt Flat, TX",
    "Fort Bliss, TX"
]

TEXAS_HOUSTON = [
    "Houston, TX",
    "Acres Homes",
    "Addicks",
    "Afton Oaks",
    "Aldine",
    "Alief",
    "Almeda",
    "Atascocita",
    "Audubon Place",
    "Avenida Houston",
    "Avondale East",
    "Bay Forest",
    "Bay Glen",
    "Bay Knoll",
    "Barrett Station",
    "Bear Creek 1",
    "Bear Creek 2",
    "Binz",
    "Blue Ridge",
    "Bordersville",
    "Boulevard Oaks",
    "Braeburn",
    "Braeswood Place",
    "Brays Oaks",
    "Brentwood",
    "Briar Meadow",
    "Briargrove",
    "Briargrove Park",
    "Briarhills",
    "Briarmeadow",
    "Broadacres",
    "Brooke Smith",
    "Brookline",
    "Camden Park",
    "Camino South",
    "Camp Logan",
    "Candlelight Estates",
    "Candlelight Place",
    "Carverdale",
    "Central City",
    "Champion Forest",
    "Chasewood",
    "Cherryhurst",
    "Chevy Chase",
    "Chinatown",
    "City Park",
    "City Centre",
    "Clear Lake City",
    "Clinton Park",
    "Cloverland",
    "Cole Creek Manor",
    "Copperfield",
    "Corinthian Pointe",
    "Cottage Grove",
    "Courtlandt Place",
    "Crestwood / Glen Cove",
    "Candlelight Forest West",
    "Denver Harbor",
    "Downtown",
    "East Downtown",
    "East End",
    "East Houston",
    "Eastex / Jensen",
    "East Little York / Homestead",
    "Eastwood",
    "Edgebrook",
    "El Dorado / Oates Prairie",
    "Eldridge / West Oaks",
    "Energy Corridor",
    "Fairbanks / Northwest Crossing",
    "Fondren Southwest",
    "Fifth Ward",
    "First Ward",
    "Forum Park",
    "Fourth Ward",
    "Forest West / Pinemont",
    "Forrest Lake",
    "Foster Place",
    "Frenchtown",
    "Frostwood",
    "Garden Oaks",
    "Garden Villas",
    "Gaywood",
    "Genoa",
    "Glenbrook Valley",
    "Glenshire",
    "Golfcrest",
    "Greenfield Village",
    "Greenspoint",
    "Greenway Plaza",
    "Greenwood",
    "Gulfgate / Pine Valley",
    "Gulfton",
    "Gulfway Terrace",
    "Harrisburg",
    "Heather Glen",
    "Herschellwood",
    "Hidden Valley",
    "Highland Village",
    "Hillwood",
    "Hiram Clarke",
    "Houston Gardens",
    "Houston Heights",
    "Humble",
    "Hunters Glen",
    "Hunters Point",
    "Hunterwood",
    "Hyde Park",
    "Idylwood",
    "Independence Heights",
    "International District",
    "Inwood Forest",
    "Ingrando Park",
    "Jeanetta",
    "Kashmere Gardens",
    "Kingwood",
    "Kleinbrook",
    "Knollwood Village",
    "Lake Houston",
    "Lakes of Parkway",
    "Lakewood",
    "Langwood",
    "Larchmont",
    "Lawndale / Wayside",
    "Lazybrook / Timbergrove",
    "Lindale Park",
    "Link Valley",
    "Linkwood",
    "Little Saigon",
    "Lincoln Greens",
    "Lower Westheimer",
    "Magnolia Grove",
    "Magnolia Park",
    "Mahatma Gandhi District",
    "Manchester",
    "Maplewood",
    "Maplewood South-North",
    "Marilyn Estates",
    "Meadowcreek Village",
    "Memorial",
    "Memorial Bend",
    "Memorial City",
    "Memorial Park",
    "Meyerland",
    "Midtown",
    "Montrose",
    "Moonshine Hill",
    "Morningside Place",
    "Museum District",
    "Museum Park",
    "Mykawa",
    "Near Northside",
    "Near Northwest",
    "Neartown",
    "North Lindale",
    "Norhill",
    "North Central",
    "North Shore",
    "Northcliffe",
    "Northcliffe Manor",
    "Northfield",
    "Northline",
    "Northside",
    "Nottingham Forest",
    "Nottingham West",
    "Oak Brook",
    "Oak Estates",
    "Oak Forest",
    "Oak Manor-University Woods",
    "Old Braeswood",
    "Overbrook",
    "Paradise Valley",
    "Park Place",
    "Parkway Villages",
    "Pecan Park",
    "Pierce Junction",
    "Pine Valley",
    "Pleasantville",
    "Port Houston",
    "Ponderosa Forest",
    "Prestonwood Forest",
    "Recreation Acres",
    "Rice Military",
    "Rice Village",
    "Richmond Strip",
    "Ridgegate",
    "Ridgemont",
    "River Oaks",
    "Rivercrest Estates",
    "Riverside Terrace",
    "Robindell",
    "Royal Oaks Country Club",
    "Sagemont",
    "Scenic Woods",
    "Second Ward",
    "Settegast",
    "Shady Acres",
    "Shadyside",
    "Sharpstown",
    "Shenandoah",
    "Shepherd Park Plaza",
    "Sherwood Forest",
    "Sherwood Oaks",
    "Sixth Ward",
    "Somerset Green",
    "South Acres",
    "South Bank",
    "South Main",
    "South Park",
    "South Union",
    "Southcrest",
    "Southampton",
    "Southbelt / Ellington",
    "Southgate",
    "Southwest",
    "Spring Branch",
    "Spring Lakes",
    "St. George Place",
    "Sugar Valley",
    "Sunnyside",
    "Sunset Terrace / Montclair",
    "Tanglewood",
    "Tanglewilde",
    "Third Ward",
    "Timbergrove Manor"
    "University Oaks",
    "Upper Kirby",
    "Uptown",
    "Village at Glen Iris",
    "Walnut Bend",
    "Washington Avenue",
    "Washington Terrace",
    "West Eleventh Place",
    "West End",
    "West Oaks",
    "Westbury",
    "Westmoreland",
    "Westmoreland Farms",
    "Westwood",
    "Willow Meadows",
    "Willowbend",
    "Willowbrook",
    "Willowick Place",
    "Willowood",
    "Windemere",
    "Windsor Village",
    "Woodland Heights",
    "Woodland Trails",
    "Woodshire",
    "Woodside",
    "Wrenwood",
    "Yellowstone",
    "Yorkshire",
    "Yorkwood",
    "First Ward",
    "Second Ward",
    "Third Ward",
    "Fourth Ward",
    "Fifth Ward",
    "Sixth Ward",
    "The Woodlands, TX",
    "Sugar Land, TX",
    "Pasadena, TX",
    "Pearland, TX",
    "League City, TX",
    "Baytown, TX",
    "Conroe, TX",
    "Galveston, TX",
    'Houston, TX',
    'League City, TX', 
    'Pasadena, TX',
    'Pearland, TX', 
    'Sugar Land, TX',
    'The Woodlands, TX', 
    'Conroe, TX', 
    'Baytown, TX', 
    'Deer Park, TX', 
    'Friendswood, TX', 
    'Galveston, TX', 
    'Lake Jackson, TX', 
    'La Porte, TX', 
    'Missouri City, TX', 
    'Rosenberg, TX', 
    'Texas City, TX', 
    'Atascocita, TX', 
    'Channelview, TX', 
    'Mission Bend, TX', 
    'Spring, TX',
    'Alvin, TX', 
    'Angleton, TX', 
    'Bellaire, TX', 
    'Clute, TX', 
    'Dickinson, TX', 
    'Freeport, TX', 
    'Galena Park, TX', 
    'Humble, TX', 
    'Jacinto City, TX', 
    'Katy, TX', 
    'La Marque, TX', 
    'Richmond, TX', 
    'Santa Fe, TX', 
    'Seabrook, TX', 
    'South Houston, TX', 
    'Stafford, TX', 
    'Tomball, TX', 
    'Webster, TX', 
    'West University Place, TX',
    'Aldine, TX', 
    'Cinco Ranch, TX', 
    'Cloverleaf, TX', 
    'Four Corners, TX', 
    'Fresno, TX', 
    'Greatwood, TX', 
    'New Territory, TX', 
    'Pecan Grove, TX', 
    'Sienna Plantation, TX',
    'Ames, TX', 
    'Anahuac, TX', 
    'Arcola, TX', 
    'Bayou Vista, TX', 
    'Beach City, TX', 
    'Beasley, TX', 
    'Bellville, TX', 
    'Brazoria, TX', 
    'Brazos Country, TX', 
    'Brookshire, TX', 
    'Brookside Village, TX', 
    'Bunker Hill Village, TX', 
    'Clear Lake Shores, TX', 
    'Cleveland, TX', 
    'Cove, TX', 
    'Cut and Shoot, TX', 
    'Daisetta, TX', 
    'Danbury, TX', 
    'Dayton, TX', 
    'Dayton Lakes, TX', 
    'Devers, TX', 
    'El Lago, TX', 
    'Fulshear, TX', 
    'Hardin, TX', 
    'Hempstead, TX', 
    'Hedwig Village, TX', 
    'Hilshire Village, TX', 
    'Hitchcock, TX', 
    'Hunters Creek Village, TX', 
    'Industry, TX', 
    'Iowa Colony, TX', 
    'Jamaica Beach, TX', 
    'Jersey Village, TX', 
    'Kemah, TX', 
    'Kendleton, TX', 
    'Liberty, TX', 
    'Liverpool, TX', 
    'Magnolia, TX', 
    'Manvel, TX', 
    'Meadows Place, TX', 
    'Mont Belvieu, TX', 
    'Montgomery, TX', 
    "Morgan's Point, TX", 
    'Nassau Bay, TX', 
    'Needville, TX', 
    'North Cleveland, TX', 
    'Oak Ridge North, TX', 
    'Old River-Winfree, TX', 
    'Orchard, TX', 
    'Oyster Creek, TX', 
    'Panorama Village, TX', 
    'Pattison, TX', 
    'Patton Village, TX', 
    'Piney Point Village, TX', 
    'Plum Grove, TX', 
    'Prairie View, TX', 
    'Richwood, TX', 
    'Sealy, TX', 
    'Shenandoah, TX', 
    'Shoreacres, TX', 
    'Simonton, TX', 
    'Southside Place, TX', 
    'Splendora, TX', 
    'Spring Valley Village, TX', 
    'Surfside Beach, TX', 
    'Sweeny, TX', 
    'Taylor Lake Village, TX', 
    'Waller, TX', 
    'Wallis, TX', 
    'West Columbia, TX', 
    'Willis, TX', 
    'Woodbranch, TX',
    'Holiday Lakes, TX', 
    'Kenefick, TX', 
    'Pine Island, TX', 
    'Quintana, TX', 
    'Roman Forest, TX', 
    'San Felipe, TX', 
    'Stagecoach, TX', 
    'Thompsons, TX', 
    'Woodloch, TX', 
    "Bailey's Prairie, TX", 
    'Bonney, TX', 
    'Fairchilds, TX', 
    'Hillcrest, TX', 
    'Jones Creek, TX', 
    'Pleak, TX', 
    'Tiki Island, TX',
    'Bacliff, TX', 
    'Barrett, TX', 
    'Bolivar Peninsula, TX', 
    'Crosby, TX', 
    'Cumings, TX', 
    'Damon, TX', 
    'Fifth Street, TX', 
    'Highlands, TX', 
    'Pinehurst, TX', 
    'Porter Heights, TX', 
    'San Leon, TX', 
    'Sheldon, TX', 
    'Stowell, TX', 
    'Wild Peach Village, TX', 
    'Winnie, TX'
]

TEXAS_MCALLEN = [
    'Alamo, TX', 
    'Alton, TX', 
    'Donna, TX', 
    'Edcouch, TX', 
    'Edinburg, TX', 
    'Elsa, TX', 
    'Granjeno, TX', 
    'Hidalgo, TX', 
    'La Joya, TX', 
    'La Villa, TX', 
    'McAllen, TX', 
    'Mercedes, TX', 
    'Mission, TX', 
    'Palmhurst, TX', 
    'Palmview, TX', 
    'Penitas, TX', 
    'Pharr, TX', 
    'Progreso, TX', 
    'Progreso Lakes, TX', 
    'San Juan, TX', 
    'Sullivan City, TX', 
    'Weslaco, TX',
    'Abram, TX', 
    'Alton North, TX', 
    'César Chávez, TX', 
    'Citrus City, TX', 
    'Cuevitas, TX', 
    'Doffing, TX', 
    'Doolittle, TX', 
    'Faysville, TX', 
    'Harding Gill Tract, TX', 
    'Hargill, TX', 
    'Havana, TX', 
    'Heidelberg, TX', 
    'Indian Hills, TX', 
    'La Blanca, TX', 
    'La Coma Heights, TX', 
    'La Homa, TX', 
    'Laguna Seca, TX', 
    'Linn, TX', 
    'Llano Grande, TX', 
    'Lopezville, TX', 
    'Los Ebanos, TX', 
    'Midway North, TX', 
    'Midway South, TX', 
    'Mila Doce, TX', 
    'Monte Alto, TX', 
    'Muniz, TX', 
    'Murillo, TX', 
    'North Alamo, TX', 
    'Olivarez, TX', 
    'Palmview South, TX', 
    'Perezville, TX', 
    'Relampago, TX', 
    'Salida del Sol Estates, TX', 
    'San Carlos, TX', 
    'Scissors, TX', 
    'South Alamo, TX', 
    'Villa Verde, TX', 
    'West Sharyland, TX', 
    'McCook, TX'
]

TEXAS_SAN_ANTONIO = [
    "Central San Antonio",
    "Downtown San Antonio",
    "Midtown San Antonio",
    "Southtown San Antonio",
    "Alamo Heights, San Antonio",
    "North San Antonio",
    "Uptown San Antonio",
    "Uptown Central San Antonio",
    "North Central San Antonio",
    "Far North Central San Antonio",
    "Northeast Side San Antonio",
    "Northwest Side San Antonio",
    "West San Antonio",
    "Inner West Side San Antonio",
    "Near Northwest Side San Antonio",
    "Far West Side San Antonio",
    "South San Antonio",
    "East San Antonio",
    "Near East Side San Antonio",
    'San Antonio, TX',
    'New Braunfels, TX',
    'Cibolo, TX', 
    'Converse, TX', 
    'Schertz, TX', 
    'Seguin, TX', 
    'Timberwood Park, TX', 
    'Boerne, TX', 
    'Canyon Lake, TX', 
    'Leon Valley, TX', 
    'Live Oak, TX', 
    'Pleasanton, TX', 
    'Selma, TX', 
    'Universal City, TX', 
    'Uvalde, TX', 
    'Alamo Heights, TX', 
    'Bulverde, TX', 
    'Fair Oaks Ranch, TX', 
    'Floresville, TX', 
    'Helotes, TX', 
    'Hondo, TX', 
    'Kirby, TX', 
    'Lackland AFB, TX', 
    'Lakehills, TX', 
    'Terrell Hills, TX', 
    'Windcrest, TX', 
    'Balcones Heights, TX', 
    'Castle Hills, TX', 
    'Castroville, TX', 
    'Charlotte, TX',
    'China Grove, TX', 
    'Comfort, TX', 
    'Cross Mountain, TX', 
    'Devine, TX', 
    'Elmendorf, TX', 
    'Garden Ridge, TX', 
    'Hill Country Village, TX', 
    'Hollywood Park, TX', 
    'Jourdanton, TX', 
    'LaCoste, TX', 
    'La Vernia, TX', 
    'Lake Dunlap, TX', 
    'Lytle, TX', 
    'Marion, TX', 
    'McQueeney, TX', 
    'Natalia, TX', 
    'Nixon, TX', 
    'Northcliff, TX', 
    'Olmos Park, TX', 
    'Poteet, TX', 
    'Poth, TX', 
    'Randolph AFB, TX', 
    'Redwood, TX', 
    'Sandy Oaks, TX',
    'Scenic Oaks, TX', 
    'Shavano Park, TX', 
    'Somerset, TX', 
    'St. Hedwig, TX', 
    'Stockdale, TX', 
    'Von Ormy, TX', 
    'San Saba, TX',
    'Bandera, TX', 
    'Christine, TX', 
    'Geronimo, TX', 
    'Grey Forest, TX', 
    'Kingsbury, TX', 
    'New Berlin, TX', 
    'Santa Clara, TX', 
    'Spring Branch, TX', 
    'Staples, TX', 
    'Zuehl, TX', 
    'Adkins, TX', 
    'Amphion, TX', 
    'Atascosa, TX', 
    'Bandera Falls, TX', 
    'Bergheim, TX', 
    'Carpenter, TX',
    "D'Hanis, TX", 
    'Dunlay, TX', 
    'Fischer, TX', 
    'Kicaster, TX', 
    'Leesville, TX', 
    'Guadalupe County, TX', 
    'Leming, TX', 
    'Leon Springs, TX', 
    'Losoya, TX', 
    'Macdona, TX', 
    'Medina, TX', 
    'Mico, TX', 
    'Pearson, TX', 
    'Pandora, TX', 
    'Pipe Creek, TX', 
    'Rio Medina, TX', 
    'Saspamco, TX', 
    'Sayers, TX', 
    'Sutherland Springs, TX', 
    'Tarpley, TX', 
    'Vanderpool, TX', 
    'Waring, TX', 
    'Welfare, TX', 
    'Yancey, TX'
]