VIRGINIA_FAIRFAX = [
    "Fairfax, VA",
    "Clifton, VA",
    "Herndon, VA",
    "Falls Church, VA",
    "Alexandria, VA",
    "South Alexandria, VA",
    "Lower Alexandria, VA",
    "Alexandria, Fairfax County",
    "Hollin Hills",
    "Franconia",
    "Groveton",
    "Hybia Valley",
    "Huntington",
    "Belle Haven",
    "Mount Vernon",
    "Fort Hunt",
    "Engleside",
    "Burgundy Village",
    "Waynewood",
    "Wilton Woods",
    "Rose Hill",
    "Virginia Hills",
    "Hayfield",
    "Kingstowne",
    "Annandale, VA",
    "Bailey's Crossroads, VA",
    "Belle Haven, VA",
    "Braddock, VA",
    "Bull Run, VA",
    "Burke, VA",
    "Burke Centre, VA",
    "Centreville, VA",
    "Chantilly, VA",
    "Crosspointe, VA",
    "Difficult Run, VA",
    "Dranesville, VA",
    "Dunn Loring, VA",
    "Fair Lakes, VA",
    "Fair Oaks, VA",
    "Fairfax Station, VA",
    "Floris, VA",
    "Fort Belvoir, VA",
    "Fort Hunt, VA",
    "Franconia, VA",
    "Franklin Farm, VA",
    "George Mason, VA",
    "Great Falls, VA",
    "Great Falls Crossing, VA",
    "Greenbriar, VA",
    "Groveton, VA",
    "Hayfield, VA",
    "Huntington, VA",
    "Hutchison, VA",
    "Hybla Valley, VA",
    "Idylwood, VA",
    "Kings Park, VA",
    "Kings Park West, VA", 
    "Kingstowne, VA",
    "Lake Barcroft, VA",
    "Laurel Hill, VA",
    "Lincolnia, VA",
    "Long Branch, VA",
    "Lorton, VA",
    "Mantua, Va",
    "Mason Neck, VA",
    "McLean, VA",
    "McNair, VA",
    "Merrifield, VA",
    "Mount Vernon, VA",
    "Navy, VA",
    "Newington, VA",
    "Newington Forest, VA",
    "North Springfield, VA",
    "Oakton, VA",
    "Pimmit Hills, VA",
    "Ravensworth, VA",
    "Reston, VA",
    "Rose Hill, VA",
    "Seven Corners, VA",
    "South Run, VA",
    "Springfield, VA",
    "Sully Square, VA",
    "Tysons, VA",
    "Union Mill, VA",
    "Wakefield, VA",
    "West Falls Church, VA",
    "West Springfield, VA",
    "Wolf Trap, VA",
    "Woodburn, VA",
    "Woodlawn, VA",
    "Accotink, VA",
    "Arcturus, VA",
    "Barkers Crossroads, VA",
    "Blevinstown, VA",
    "Browns Mill, VA",
    "Colchester, VA",
    "Colchester Hunt, VA",
    "Cooktown, VA",
    "Crowells Corner, VA",
    "Culmore, VA",
    "Donovans Corner, VA",
    "Doveville, VA",
    "Farrs Corner, VA",
    "Five Forks, VA",
    "Four Corners, VA",
    "Hattontown, VA",
    "Hollindale, VA",
    "Jermantown, VA",
    "Langley, VA",
    "Lees Corner, VA",
    "Lewinsville, VA",
    "Lewis Park, VA",
    "Makleys Corner, VA",
    "Matildaville, VA",
    "New Alexandria, VA",
    "Oak Hill, VA",
    "Odricks Corner, VA",
    "Pohick, VA",
    "Schneider Crossroads, VA",
    "Shady Oak, VA",
    "Strathmeade Springs, VA",
    "Sunset Hills, VA",
    "Uniontown, VA",
    "Virginia Hills, VA",
    "Westhampton, VA"
]

VIRGINIA_LOUDON_COUNTY = [
    'Hamilton, VA', 
    'Hillsboro, VA', 
    'Leesburg, VA', 
    'Lovettsville, VA', 
    'Middleburg, VA', 
    'Purcellville, VA', 
    'Round Hill, VA', 
    'Aldie, VA', 
    'Arcola, VA', 
    'Ashburn, VA', 
    'Belmont, VA', 
    'Brambleton, VA', 
    'Broadlands, VA', 
    'Cascades, VA', 
    'Countryside, VA', 
    'Dulles Town Center, VA', 
    'Goose Creek Village, VA', 
    'Kincora, VA', 
    'Lansdowne, VA', 
    'Loudoun Valley Estates, VA', 
    'Lowes Island, VA', 
    'Moorefield, VA', 
    'Oak Grove, VA', 
    'One Loudoun, VA', 
    'South Riding, VA', 
    'Sterling, VA', 
    'Stone Ridge, VA', 
    'Sugarland Run, VA', 
    'University Center, VA', 
    'Waterford, VA', 'edit, VA', 
    'Airmont, VA', 
    'Bloomfield, VA', 
    'Bluemont, VA', 
    'Britain, VA', 
    'Conklin, VA', 
    'Dover, VA', 
    'Dulles, VA', 
    'Elvan, VA', 
    'Eubanks, VA',
    'Georges Mill, VA', 
    'Gilberts Corner, VA', 
    'Gleedsville, VA', 
    'Howardsville, VA', 
    'Leithtown, VA', 
    'Lenah, VA', 
    'Lincoln, VA', 
    'Loudoun Heights, VA', 
    'Lucketts, VA', 
    'Morrisonville, VA', 
    'Mount Gilead, VA', 
    'Neersville, VA', 
    'Paeonian Springs, VA', 
    'Paxson, VA', 
    'Philomont, VA', 
    'Potomac Falls, VA', 
    'Potomac Green, VA',  
    'River Creek, VA', 
    'Ryan, VA', 
    'Saint Louis, VA', 
    'Scattersville, VA', 
    'Silcott Spring, VA', 
    'Stewartown, VA', 
    'Stumptown, VA', 
    'Taylorstown, VA', 
    'Telegraph Spring, VA', 
    'Trapp, VA', 
    'Unison, VA', 
    'Watson, VA', 
    'Waxpool, VA', 
    'Wheatland, VA', 
    'Willard, VA', 
    'Willisville, VA', 
    'Woodburn, VA'
]