WISCONSIN_APPLETON = [
    "Appleton, WI",
    "Kaukauna, WI",
    "Menasha, WI",
    "Neenah, WI",
    "Oshkosh, WI",
    "Combined Locks, WI",
    "Fox Crossing, WI",
    "Harrison, WI",
    "Hortonville, WI",
    "Kimberley, WI",
    "Little Chute, WI",
    "Sherwood, WI",
    "Buchanan, WI",
    "Clayton, WI",
    "Freedom, WI",
    "Grand Chute, WI",
    "Greenville, WI",
    "Kaukauna, WI",
    "Neenah, WI",
    "Vandenbroek, WI",
    "New London, WI",
    "Seymour, WI",
    "Bear Creek, WI",
    "Black Creek, WI",
    "Combined Locks, WI",
    "Harrison, WI",
    "Hortonville, WI",
    "Howard, WI",
    "Kimberly, WI",
    "Little Chute, WI",
    "Nichols, WI",
    "Shiocton, WI",
    "Wrightstown, WI",
    "Black Creek, WI",
    "Bovina, WI",
    "Buchanan, WI",
    "Center, WI",
    "Cicero, WI",
    "Dale, WI",
    "Deer Creek, WI",
    "Ellington, WI",
    "Freedom, WI",
    "Grand Chute, WI",
    "Greenville, WI",
    "Hortonia, WI",
    "Kaukauna, WI",
    "Liberty, WI",
    "Maine, WI",
    "Maple Creek, WI",
    "Oneida, WI",
    "Osborn, WI",
    "Seymour, WI",
    "Vandenbroek, WI",
    "Apple Creek, WI",
    "Binghamton, WI",
    "Center Valley, WI",
    "Chicago Corners, WI",
    "Cicero, WI",
    "Darboy, WI",
    "Five Corners, WI",
    "Freedom, WI",
    "Greenville, WI",
    "Hamples Corner, WI",
    "Isaar, WI",
    "Leeman, WI",
    "Mackville, WI",
    "Medina, WI",
    "Murphy Corner, WI",
    "Oneida, WI",
    "Sniderville, WI",
    "Stephensville, WI",
    "Sugar Bush, WI",
    "Twelve Corners, WI",
    "Grand Chute, WI",
    "Lawesburg, WI",
    "Lime Rock, WI",
    "Wakefield, WI",
    "Oneida Nation of Wisconsin, WI",
    "Appleton, WI",
    "Brillion, WI",
    "Chilton, WI",
    "Kiel, WI",
    "Menasha, WI",
    "New Holstein, WI",
    "Harrison, WI",
    "Hilbert, WI",
    "Potter, WI",
    "Sherwood, WI",
    "Stockbridge, WI",
    "Brillion, WI",
    "Brothertown, WI",
    "Charlestown, WI",
    "Chilton, WI",
    "Harrison, WI",
    "Rantoul, WI",
    "Stockbridge, WI",
    "Woodville, WI",
    "Forest Junction, WI",
    "Brant, WI",
    "Calmutville, WI",
    "Charlesburg, WI",
    "Dorns Faro Springs, WI",
    "Dorns Twilight Beach, WI",
    "Dundas, WI",
    "Eckers Lakeland, WI",
    "Hayton, WI",
    "Highland Beach, WI",
    "Jericho, WI",
    "Kloten, WI",
    "Maple Heights, WI",
    "Meggers, WI",
    "Quinney, WI",
    "Rockaway Beach, WI",
    "Saint Catherines Bay, WI",
    "St. Anna, WI",
    "St. John, WI",
    "Utowana Beach, WI",
    "Waverly Beach, WI",
    "Wells, WI",
    "Pequot, WI",
    "Appleton, WI",
    "Menasha, WI",
    "Neenah, WI",
    "Omro, WI",
    "Oshkosh, WI",
    "Fox Crossing, WI",
    "Winneconne, WI",
    "Algoma, WI",
    "Black Wolf, WI",
    "Clayton, WI",
    "Neenah, WI",
    "Nekimi, WI",
    "Nepeuskun, WI",
    "Omro, WI",
    "Oshkosh, WI",
    "Poygan, WI",
    "Rushford, WI",
    "Utica, WI",
    "Vinland, WI",
    "Winchester, WI",
    "Winneconne, WI",
    "Wolf River, WI",
    "Butte des Morts, WI",
    "Eureka, WI",
    "Waukau, WI",
    "Winchester, WI",
    "Adella Beach, WI",
    "Allenville, WI",
    "Black Wolf, WI",
    "Black Wolf Point, WI",
    "Clarks Point, WI",
    "Decorah Beach, WI",
    "Elo, WI",
    "Fairview Beach, WI",
    "Fisk, WI",
    "Fitzgerald, WI",
    "Harbor Springs, WI",
    "Highland Shore, WI",
    "Indian Shores, WI",
    "Island Park, WI",
    "Larsen, WI",
    "Lasleys Point, WI",
    "Leonards Point, WI",
    "Little Point, WI",
    "Koro, WI",
    "Medina Junction, WI",
    "Melrose Park, WI",
    "Metz, WI",
    "Mikesville, WI",
    "Nichols Shore Acres, WI",
    "Oakwood, WI",
    "Orihula, WI",
    "Paukotuk, WI",
    "Piacenza, WI",
    "Pickett, WI",
    "Plummer Point, WI",
    "Point Comfort, WI",
    "Reighmoor, WI",
    "Ricker Bay, WI",
    "Ring, WI",
    "Rivermoor, WI",
    "Rush Lake, WI",
    "Shangri La Point, WI",
    "Snells, WI",
    "Sunrise Bay, WI",
    "Waverly Beach, WI",
    "Winnebago, WI",
    "Zion, WI",
    "Zittau, WI",
]

WISCONSIN_GREEN_BAY = [
    "Green Bay, WI",
    "Allouez, WI",
    "Ashwaubernon, WI",
    "Bellevue, WI",
    "Suamico, WI",
    "De Pere, WI",
    "Howard, WI",
    "Algoma, WI",
    "Casco, WI",
    "Denmark, WI",
    "Gillett, WI",
    "Hobart, WI",
    "Kewaunee, WI",
    "Lena, WI",
    "Luxemburg, WI",
    "Oconto, WI",
    "Oconto Falls, WI",
    "Pulaski, WI",
    "Suring, WI",
    "Wrightstown, WI",
    "Anston, WI",
    "Askeaton, WI",
    "Champion, WI",
    "Dyckesville, WI",
    "Greenleaf, WI",
    "Flintville, WI",
    "New Franken, WI",
    "Little Rapids, WI",
    "Sobieski, WI",
    "Eaton, WI",
    "Glenmore, WI",
    "Holland, WI",
    "Humboldt, WI",
    "Lawrence, WI",
    "Ledgeview, WI",
    "Morrison, WI",
    "New Denmark, WI",
    "Pittsfield, WI",
    "Rockland, WI",
    "Scott, WI",
    "Wrightstown, WI",
    "Ahnapee, WI",
    "Carlton, WI",
    "Casco, WI",
    "Franklin, WI",
    "Lincoln, WI",
    "Luxemburg, WI",
    "Montpelier, WI",
    "Pierce, WI",
    "Red River, WI",
    "West Kewaunee, WI",
    "Abrams, WI",
    "Bagley, WI",
    "Brazeau, WI",
    "Breed, WI",
    "Chase, WI",
    "Doty, WI",
    "Gillett, WI",
    "How, WI",
    "Lakewood, WI",
    "Lena, WI",
    "Little River, WI",
    "Little Suamico, WI",
    "Maple Valley, WI",
    "Morgan, WI",
    "Mountain, WI",
    "Oconto Falls, WI",
    "Oconto, WI",
    "Pensaukee, WI",
    "Riverview, WI",
    "Spruce, WI",
    "Stiles, WI",
    "Townsend, WI",
    "Underhill, WI",
    "De Pere, WI",
    "Allouez, WI",
    "Ashwaubenon, WI",
    "Bellevue, WI",
    "Denmark, WI",
    "Hobart, WI",
    "Howard, WI",
    "Pulaski, WI",
    "Suamico, WI",
    "Wrightstown, WI",
    "Eaton, WI",
    "Glenmore, WI",
    "Holland, WI",
    "Humboldt, WI",
    "Lawrence, WI",
    "Ledgeview, WI",
    "Morrison, WI",
    "New Denmark, WI",
    "Pittsfield, WI",
    "Rockland, WI",
    "Scott, WI",
    "Wrightstown, WI",
    "Dyckesville, WI",
    "Greenleaf, WI",
    "Anston, WI",
    "Askeaton, WI",
    "Bay Settlement, WI",
    "Benderville, WI",
    "Buckman, WI",
    "Champion, WI",
    "Chapel Ridge, WI",
    "Coppens Corner, WI",
    "Edgewater Beach, WI",
    "Fontenoy, WI",
    "Glenmore, WI",
    "Henrysville, WI",
    "Hollandtown, WI",
    "Humboldt, WI",
    "Kolb, WI",
    "Kunesh, WI",
    "Langes Corners, WI",
    "Lark, WI",
    "Little Rapids, WI",
    "Mill Center, WI",
    "Morrison, WI",
    "New Franken, WI",
    "Pine Grove, WI",
    "Pittsfield, WI",
    "Poland, WI",
    "Red Banks, WI",
    "Shirley, WI",
    "Sniderville, WI",
    "Sugar Bush, WI",
    "Wayside, WI",
    "Wequiock, WI",
    "Fort Howard, WI",
    "Preble, WI",
    "Oneida Nation of Wisconsin, WI"
]

WISCONSIN_MILWAUKEE = [
    "Milwaukee, WI",
    "Arlington Heights",
    "Brewers' Hill",
    "Franklin Heights",
    "Granville",
    "Grover Heights",
    "Halyard Park",
    "Harambee",
    "Bronzeville",
    "Havenwoods",
    "Hillside / Lapham Park",
    "Metcalfe Park",
    "Midtown",
    "Park West",
    "Sherman Park",
    "Thurston Woods",
    "Williamsburg Heights",
    "Bay View",
    "Clarke Square",
    "Holler Park",
    "Jackson Park",
    "Jones Island",
    "Layton Park",
    "Lincoln Village",
    "Mitchell Street",
    "Tippecanoe",
    "Town of Lake",
    "Walker's Point",
    "The East Side",
    "Lower East Side",
    "East Village",
    "Murray Hill",
    "Beerline B",
    "West Side",
    "North Side",
    "South Side",
    "Avenue West",
    "University Hill",
    "Cold Spring Park",
    "Historic Concordia District",
    "Enderis Park",
    "Grantosa Heights",
    "Kops Park",
    "Martin Drive",
    "Merrill PArk",
    "Piggsville",
    "Mount Mary",
    "Story Hill",
    "Walnut Hill",
    "Washington Heights"
    "Washington Park",
    "Downtown",
    "East Town",
    "Menomonee River Valley",
    "Historic Third Ward",
    "Westown",
    'Milwaukee, WI', 
    'Racine, WI', 
    'Waukesha, WI', 
    'Beaver Dam, WI', 
    'Brookfield, WI', 
    'Brown Deer, WI', 
    'Burlington, WI', 
    'Caledonia, WI', 
    'Cedarburg, WI', 
    'Cudahy, WI', 
    'Delavan, WI', 
    'Elkhorn, WI',
    'Fort Atkinson, WI', 
    'Franklin, WI', 
    'Germantown, WI', 
    'Glendale, WI', 
    'Grafton, WI', 
    'Greendale, WI', 
    'Greenfield, WI', 
    'Hartford, WI', 
    'Menomonee Falls, WI', 
    'Mequon, WI', 
    'Mount Pleasant, WI', 
    'Muskego, WI',
    'New Berlin, WI', 
    'Oak Creek, WI', 
    'Oconomowoc, WI', 
    'Pewaukee, WI', 
    'Port Washington, WI', 
    'Richfield, WI', 
    'Shorewood, WI', 
    'South Milwaukee, WI', 
    'Sussex, WI', 
    'Watertown, WI', 
    'Wauwatosa, WI', 
    'West Allis, WI', 
    'West Bend, WI', 
    'Whitefish Bay, WI', 
    'Whitewater, WI',  
    'Addison, WI', 
    'Barton, WI', 
    'Bayside, WI', 
    'Belgium, WI', 
    'Big Bend, WI', 
    'Bohners Lake, WI', 
    'Browns Lake, WI', 
    'Brownsville, WI', 
    'Butler, WI', 
    'Chenequa, WI', 
    'Clyman, WI', 
    'Darien, WI', 
    'Delafield, WI', 
    'Delafield, WI', 
    'Dousman, WI', 
    'Dover, WI', 
    'Eagle, WI', 
    'Eagle Lake, WI', 
    'East Troy, WI', 
    'Elkhorn, WI', 
    'Elm Grove, WI', 
    'Elmwood Park, WI', 
    'Erin, WI', 
    'Farmington, WI', 
    'Fox Lake, WI', 
    'Fox Point, WI', 
    'Franksville, WI', 
    'Fredonia, WI', 
    'Genesee, WI', 
    'Germantown, WI', 
    'Hales Corners, WI', 
    'Hartland, WI', 
    'Herman, WI', 
    'Horicon, WI', 
    'Hustisford, WI', 
    'Ixonia, WI', 
    'Iron Ridge, WI', 
    'Jackson, WI', 
    'Jefferson, WI', 
    'Johnson Creek, WI', 
    'Juneau, WI', 
    'Kekoskee, WI', 
    'Kewaskum, WI', 
    'Lac La Belle, WI', 
    'Lake Geneva, WI', 
    'Lake Mills, WI', 
    'Lannon, WI', 
    'Leroy, WI', 
    'Lisbon, WI', 
    'Lomira, WI', 
    'Lowell, WI', 
    'Mayville, WI', 
    'Merton, WI', 
    'Mukwonago, WI', 
    'Nashotah, WI', 
    'Neosho, WI', 
    'Newburg, WI', 
    'North Bay, WI', 
    'North Prairie, WI', 
    'Norway, WI', 
    'Oconomowoc Lake, WI', 
    'Okauchee Lake, WI', 
    'Ottawa, WI', 
    'Palmyra, WI', 
    'Pewaukee, WI', 
    'Polk, WI', 
    'Randolph, WI', 
    'Raymond, WI', 
    'Reeseville, WI', 
    'River Hills, WI', 
    'Rochester, WI', 
    'Rubicon, WI', 
    'Saukville, WI', 
    'Slinger, WI', 
    'St. Francis, WI', 
    'Sturtevant, WI', 
    'Sullivan, WI', 
    'Summit, WI', 
    'Theresa, WI', 
    'Thiensville, WI', 
    'Trenton, WI', 
    'Union Grove, WI', 
    'Vernon, WI', 
    'Wales, WI', 
    'Walworth, WI', 
    'Waterford, WI', 
    'Waterloo, WI', 
    'Waupun, WI', 
    'Wayne, WI', 
    'West Milwaukee, WI', 
    'Williams Bay, WI', 
    'Wind Lake, WI', 
    'Wind Point, WI', 
    'Yorkville, WI',  
    'Allenton, WI', 
    'Boltonville, WI', 
    'Cheeseville, WI', 
    'Colgate, WI', 
    'Ebenezer, WI', 
    'Farmersville, WI', 
    'Fillmore, WI', 
    'Genesee Depot, WI', 
    'Herman Center, WI', 
    'Hubertus, WI', 
    'Kansasville, WI', 
    'Kohlsville, WI', 
    'Lake Church, WI', 
    'Lakefield, WI', 
    'Myra, WI', 
    'Nabob, WI', 
    'Nenno, WI', 
    'North Cape, WI', 
    'Oak Hill, WI', 
    'Pipersville, WI', 
    'Pike Lake, WI', 
    'Rockfield, WI', 
    'Saint Michaels, WI', 
    'Saylesville, WI', 
    'Stone Bank, WI', 
    'Thompson, WI', 
    'Tichigan, WI', 
    'Ulao, WI', 
    'Waubeka, WI', 
    'Woodland, WI'
]