# real blocked numbers that have called me
SPAM_PHONE_NUMBERS = [
    "989-355-0317",
    "248-238-8990",
    "586-501-3201",
    "224-704-1462",
    "734-726-9644",
    "409-739-6011",
    "317-667-1733",
    "631-228-9011",
    "518-300-3797",
    "972-370-5020",
    "832-279-3343",
    "248-283-3626",
    "202-459-1993",
    "202-446-6041",
    "313-349-5713",
    "813-331-2523",
    "248-266-3603",
    "720-639-8067",
    "628-242-2498",
    "351-207-4285",
    "469-825-4691",
    "248-780-6441",
    "248-900-8320",
    "947-207-7058",
    "248-780-3389",
    "248-900-8252",
    "248-744-6797",
    "248-780-3071",
    "616-266-5784",
    "248-744-6741",
    "917-781-2565",
    "248-780-6471",
    "248-780-2631",
    "517-201-0190",
    "248-780-3736",
    "248-894-3374",
    "248-774-6770",
    "248-814-2534",
    "989-455-7616",
    "248-791-0557",
    "248-494-7384",
    "906-256-9585",
    "248-270-7008",
    "248-780-6410",
    "248-368-0179",
    "248-780-6410",
    "248-206-8752",
    "734-628-1460",
    "248-963-5272",
    "734-290-3006",
    "248-900-1536",
    "734-488-8825",
    "470-628-9559",
    "248-900-1366",
    "248-900-1712",
    ##
    "947-207-7058",
    "248-988-4113",
    "248-214-3962",
    "248-956-6306",
    "248-937-6165",
    "248-780-3389",
    "248-900-8320",
    "248-780-6441",
    "248-744-6797",
    "248-900-8252",
    "248-744-6741",
    "616-266-5784",
    "248-780-3071",
    "989-455-7616",
    "248-814-2534",
    "248-744-6770",
    "248-894-3374",
    "248-780-3736",
    "517-201-0190",
    "248-780-2631",
    "248-791-0557",
    "917-781-2565",
    "248-494-7384",
    "248-270-7008",
    "906-256-9585",
    "248-780-6410",
    "248-900-1536",
    "734-290-3006",
    "248-963-5262",
    "734-628-1460",
    "248-206-8752",
    "248-780-3005",
    "248-368-0179",
    "734-488-8825",
    "469-825-4691",
    "470-628-9599",
    "248-900-1366",
    "620-524-3123",
    "248-900-1712",
    "248-970-5572",
    "269-242-6706",
    "603-584-7183",
    "646-681-2382",
    "248-780-6326",
    "810-255-3665",
    "248-780-6927",
    "248-780-6863",
    "248-900-7148",
    "248-970-5172",
    "248-900-7148",
    "409-370-2745",
    "248-780-3071",
    "248-752-4328",
    "734-252-0685",
    "269-242-6705",
    "351-207-4285",
    "269-242-6696",
    "404-857-0025",
    "616-266-5772",
    "248-782-3271",
    "616-266-5772",
    "469-825-4691"
]

SUBURBS = {
    "Fort Smith, AR": [
        'Fort Smith, AR',
        'Van Buren, AR',
        'Alma, AR',
        'Arkoma, OK',
        'Barling, AR',
        'Cedarville, AR',
        'Charleston, AR',
        'Greenwood, AR',
        'Heavener, OK',
        'Lavaca, AR',
        'Mansfield, AR',
        'Mulberry, AR',
        'Muldrow, OK',
        'Ozark, AR',
        'Panama, OK',
        'Pocola, OK',
        'Poteau, OK',
        'Roland, OK',
        'Sallisaw, OK',
        'Spiro, OK',
        'Talihina, OK',
        'Vian, OK',
        'Wister, OK',
        'Bonanza, AR',
        'Brent, OK',
        'Brushy, OK',
        'Carlisle, OK',
        'Central City, AR',
        'Dyer, AR',
        'Gore, OK',
        'Hackett, AR',
        'Hartford, AR',
        'Howe, OK',
        'Huntington, AR',
        'Kibler, AR',
        'Mountainburg, AR',
        'Rock Island, OK',
        'Shady Point, OK',
        'Akins, OK',
        'Altus, AR',
        'Belfonte, OK',
        'Bokoshe, OK',
        'Branch, AR',
        'Cameron, OK',
        'Cecil, AR',
        'Chester, AR',
        'Cowlington, OK',
        'Denning, AR',
        'Dwight Mission, OK',
        'Evening Shade, OK',
        'Fanshawe, OK',
        'Flute Springs, OK',
        'Fort Coffee, OK',
        'Gans, OK',
        'Le Flore, OK',
        'Long, OK',
        'Marble City Community, OK',
        'Marble City, OK',
        'McKey, OK',
        'Midland, AR',
        'Moffett, OK',
        'Notchietown, OK',
        'Paradise Hill, OK',
        'Pinhook Corners, OK',
        'Redbird Smith, OK',
        'Remy, OK',
        'Rudy, AR',
        'Short, OK',
        'Stony Point, OK',
        'Sycamore, Sequoyah County, OK',
        'Wiederkehr Village, AR',
        'Big Cedar, OK',
        'Dora, AR',
        'Hodgen, OK',
        'Monroe, OK',
        'Muse, OK',
        'Skullyville, OK',
        'Whitesboro, OK'
    ],
    "Phoenix, AZ": [
        'Phoenix, AZ',
        'Mesa, AZ',
        'Chandler, AZ',
        'Gilbert, AZ',
        'Glendale, AZ',
        'Scottsdale, AZ',
        'Peoria, AZ',
        'Tempe, AZ',
        'Surprise, AZ',
        'Goodyear, AZ',
        'Buckeye, AZ',
        'Avondale, AZ',
        'Queen Creek, AZ',
        'Maricopa, AZ',
        'Casa Grande, AZ',
        'Apache Junction, AZ',
        'El Mirage, AZ',
        'Florence, AZ',
        'Fountain Hills, AZ',
        'Eloy, AZ',
        'Coolidge, AZ',
        'Paradise Valley, AZ',
        'Wickenburg, AZ',
        'Tolleson, AZ',
        'Youngtown, AZ',
        'Litchfield Park, AZ',
        'Guadalupe, AZ',
        'Cave Creek, AZ',
        'Carefree, AZ',
        'Superior, AZ',
        'Kearny, AZ',
        'Gila Bend, AZ',
        'Mammoth, AZ',
        'San Tan Valley, AZ',
        'Sun City, AZ',
        'Sun City West, AZ',
        'Anthem, AZ',
        'New River, AZ',
        'Sun Lakes, AZ',
        'Gold Canyon, AZ',
        'Arizona City, AZ',
        'Aguila, AZ',
        'Ak-Chin Village, AZ',
        'Arlington, AZ',
        'Bapchule, AZ',
        'Cactus Forest, AZ',
        'Chuichu, AZ',
        'Circle City, AZ',
        'Eleven Mile Corner, AZ',
        'Komatke, AZ',
        'La Palma, AZ',
        'Liberty, AZ',
        'Morristown, AZ',
        'Olberg, AZ',
        'Palo Verde, AZ',
        'Queen Valley, AZ',
        'Red Rock, AZ',
        'Rio Verde, AZ',
        'Sacaton, AZ',
        'Stanfield, AZ',
        'Tonopah, AZ',
        'Tortilla Flat, AZ',
        'Valley Farms, AZ',
        'Waddell, AZ',
        'Wintersburg, AZ',
        'Wittmann, AZ'
    ],
    "Tucson, AZ": [
        "South Tuscon, AZ",
        "Tucson, AZ",
        "Marana, AZ",
        "Ora Valley, AZ",
        "Sahuarita, AZ",
        "Casa Adobes, AZ",
        "Catalina Foothills, AZ",
        "Drexel Heights, AZ",
        "Green Valley, AZ",
        "Tanque Verde, AZ",
        "Flowing Wells, AZ",
        "Tucson Estates, AZ",
        "Vail, AZ",
        "Picture Rocks, AZ",
        "Valencia West, AZ",
        "Catalina, AZ"
        "Avra Valley, AZ",
        "Corona de Tucson, AZ",
        "South Tuscon, AZ",
        "Three Points, AZ",
        "Summit, AZ",
        "Rincon Valley, AZ",
        "Ajo, AZ",
        "Sells, AZ",
        "Arivaca Junction, AZ"
    ],
    "La Quinta, CA": [
        "Cathedral City, CA",
        "Coachella, CA",
        "Desert Hot Springs, CA",
        "Indian Wells, CA",
        "Indio, CA",
        "La Quinta, CA",
        "Palm Desert, CA",
        "Palm Springs, CA",
        "Rancho Mirage, CA"
    ],
    "Orange County, CA": [
        'Aliso Viejo, CA',
        'Anaheim, CA',
        'Brea, CA',
        'Buena Park, CA',
        'Costa Mesa, CA',
        'Cypress, CA',
        'Dana Point, CA',
        'Fountain Valley, CA',
        'Fullerton, CA',
        'Garden Grove, CA',
        'Huntington Beach, CA',
        'Irvine, CA',
        'La Habra, CA',
        'La Palma, CA',
        'Laguna Beach, CA',
        'Laguna Hills, CA',
        'Laguna Niguel, CA',
        'Laguna Woods, CA',
        'Lake Forest, CA',
        'Los Alamitos, CA',
        'Mission Viejo, CA',
        'Newport Beach, CA',
        'Orange, CA',
        'Placentia, CA',
        'Rancho Santa Margarita, CA',
        'San Clemente, CA',
        'San Juan Capistrano, CA',
        'Santa Ana, CA',
        'Seal Beach, CA',
        'Stanton, CA',
        'Tustin, CA',
        'Villa Park, CA',
        'Westminster, CA',
        'Yorba Linda, CA',
        'Anaheim Island, CA',
        'Coto de Caza, CA',
        'Emerald Bay, CA',
        'Ladera Ranch, CA',
        'Las Flores, CA',
        'Midway City, CA',
        'Modjeska Canyon, CA',
        'North Tustin, CA'
    ],
    "Clearwater, FL": [
        'Tampa, FL',
        'St. Petersburg, FL',
        'Clearwater, FL',
        'Lakeland, FL',
        'Riverview, FL',
        'Brandon, FL',
        'Spring Hill, FL',
        'Apollo Beach, FL',
        'Bayonet Point, FL',
        'Bloomingdale, FL',
        'Citrus Park, FL',
        'Cheval, FL',
        'Dunedin, FL',
        'Egypt Lake-Leto, FL',
        'East Lake, FL',
        'East Lake-Orient Park, FL',
        'Elfers, FL',
        'Fish Hawk, FL',
        'Greater Carrollwood, FL',
        'Greater Northdale, FL',
        'Gulfport, FL',
        'Holiday, FL',
        'Hudson, FL',
        'Jasmine Estates, FL',
        'Keystone, FL',
        'Lake Magdalene, FL',
        "Land o' Lakes, FL",
        'Largo, FL',
        'Lealman, FL',
        'Lutz, FL',
        'New Port Richey, FL',
        'Mango, FL',
        'Oldsmar, FL',
        'Palm Harbor, FL',
        'Palm River-Clair Mel, FL',
        'Pinellas Park, FL',
        'Plant City, FL',
        'Ruskin, FL',
        'Safety Harbor, FL',
        'Shady Hills, FL',
        'Seminole, FL',
        'Sun Center, FL',
        'Tarpon Springs, FL',
        'Temple Terrace, FL',
        'Thonotosassa, FL',
        "Town 'n' Country, FL",
        'Trinity, FL',
        'Valrico, FL',
        'Wesley Chapel, FL',
        'West Lealman, FL',
        'Westchase, FL',
        'Zephyrhills, FL'
    ],
    "Destin, FL": [
        "Crestview, FL",
        "Fort Walton Beach, FL",
        "DeFuniak Springs, FL",
        "Destin, FL",
        "Niceville, FL",
        "Valparaiso, FL",
        "Freeport, FL",
        "Mary Esther, FL",
        "Laurel Hill, FL",
        "Paxton, FL",
        "Shalimar, FL",
        "Cinco Bayou, FL"
    ],
    "Fort Lauderdale, FL": [
        'Miami, FL',
        'Hialeah, FL',
        'Fort Lauderdale, FL',
        'Pembroke Pines, FL',
        'Hollywood, FL',
        'Miramar, FL',
        'Coral Springs, FL',
        'Miami Gardens, FL',
        'Pompano Beach, FL',
        'West Palm Beach, FL',
        'Davie, FL',
        'Boca Raton, FL',
        'Sunrise, FL',
        'Plantation, FL',
        'Miami Beach, FL',
        'Deerfield Beach, FL',
        'Boynton Beach, FL',
        'Lauderhill, FL',
        'Weston, FL',
        'Homestead, FL',
        'Aventura, FL',
        'Belle Glade, FL',
        'Boca Del Mar, FL',
        'Boca Raton, FL',
        'Boynton Beach, FL',
        'Brownsville, FL',
        'Coconut Creek, FL',
        'Cooper City, FL',
        'Coral Gables, FL',
        'Coral Terrace, FL',
        'Country Club, FL',
        'Country Walk, FL',
        'Cutler Bay, FL',
        'Dania Beach, FL',
        'Deerfield Beach, FL',
        'Delray Beach, FL',
        'Doral, FL',
        'Florida City, FL',
        'Fontainebleau, FL',
        'Gladeview, FL',
        'Glenvar Heights, FL',
        'Goulds, FL',
        'Greenacres, FL',
        'Hallandale Beach, FL',
        'Hamptons at Boca Raton, FL',
        'Hialeah Gardens, FL',
        'Homestead, FL',
        'Ives Estates, FL',
        'Jupiter, FL',
        'Kendale Lakes, FL',
        'Kendall West, FL',
        'Kendall, FL',
        'Key Biscayne, FL',
        'Kings Point, FL',
        'Lake Worth Corridor, FL',
        'Lake Worth Beach, FL',
        'Lauderdale Lakes, FL',
        'Lauderhill, FL',
        'Leisure City, FL',
        'Lighthouse Point, FL',
        'Margate, FL',
        'Miami Beach, FL',
        'Miami Lakes, FL',
        'Miami Shores, FL',
        'Miami Springs, FL',
        'North Lauderdale, FL',
        'North Miami Beach, FL',
        'North Miami, FL',
        'North Palm Beach, FL',
        'Oakland Park, FL',
        'Ojus, FL',
        'Olympia Heights, FL',
        'Opa-locka, FL',
        'Palm Beach Gardens, FL',
        'Palm Beach, FL',
        'Palm Springs, FL',
        'Palmetto Bay, FL',
        'Palmetto Estates, FL',
        'Parkland, FL',
        'Pinecrest, FL',
        'Pinewood, FL',
        'Plantation, FL',
        'Princeton, FL',
        'Richmond West, FL',
        'Riviera Beach, FL',
        'Royal Palm Beach, FL',
        'Sandalfoot Cove, FL',
        'South Miami Heights, FL',
        'South Miami, FL',
        'Sunny Isles Beach, FL',
        'Sunrise, FL',
        'Sunset, FL',
        'Sweetwater, FL',
        'Tamarac, FL',
        'Tamiami, FL',
        'The Crossings, FL',
        'The Hammocks, FL',
        'University Park, FL',
        'Wellington, FL',
        'West Little River, FL',
        'West Park, FL',
        'Westchester, FL',
        'Weston, FL',
        'Westwood Lakes, FL',
        'Wilton Manors, FL',
        'Atlantis, FL',
        'Bal Harbour, FL',
        'Bay Harbor Islands, FL',
        'Belle Glade Camp, FL',
        'Biscayne Park, FL',
        'Boca Pointe, FL',
        'Boulevard Gardens, FL',
        'Briny Breezes, FL',
        'Broadview Park, FL',
        'Canal Point, FL',
        'Century Village, FL',
        'Cypress Lakes, FL',
        'Dunes Road, FL',
        'El Portal, FL',
        'Fisher Island, FL',
        'Franklin Park, FL',
        'Fremd Village-Padgett Island, FL',
        'Glen Ridge, FL',
        'Godfrey Road, FL',
        'Golden Beach, FL',
        'Golden Lakes, FL',
        'Golf, FL',
        'Gulf Stream, FL',
        'Gun Club Estates, FL',
        'Haverhill, FL',
        'High Point, FL',
        'Highland Beach, FL',
        'Hillsboro Beach, FL',
        'Hillsboro Pines, FL',
        'Homestead Base, FL',
        'Hypoluxo, FL',
        'Indian Creek, FL',
        'Islandia, FL',
        'Juno Beach, FL',
        'Juno Ridge, FL',
        'Jupiter Inlet Colony, FL',
        'Lake Belvedere Estates, FL',
        'Lake Clarke Shores, FL',
        'Lake Harbor, FL',
        'Lake Park, FL',
        'Lakeside Green, FL',
        'Lantana, FL',
        'Lauderdale-by-the-Sea, FL',
        'Lazy Lake, FL',
        'Limestone Creek, FL',
        'Manalapan, FL',
        'Mangonia Park, FL',
        'Medley, FL',
        'Mission Bay, FL',
        'Naranja, FL',
        'North Bay Village, FL',
        'Ocean Ridge, FL',
        'Pahokee, FL',
        'Palm Beach Shores, FL',
        'Palm Springs North, FL',
        'Pembroke Park, FL',
        'Plantation Mobile Home Park, FL',
        'Richmond Heights, FL',
        'Roosevelt Gardens, FL',
        'Royal Palm Estates, FL',
        'Schall Circle, FL',
        'Sea Ranch Lakes, FL',
        'Seminole Manor, FL',
        'South Bay, FL',
        'South Palm Beach, FL',
        'Southwest Ranches, FL',
        'Stacy Street, FL',
        'Surfside, FL',
        'Tequesta, FL',
        'Three Lakes, FL',
        'Villages of Oriole, FL',
        'Virginia Gardens, FL',
        'Washington Park, FL',
        'Westlake, FL',
        'West Miami, FL',
        'West Perrine, FL',
        'Westview, FL',
        'Whisper Walk, FL'
    ],
    "Jacksonville, FL": [
        "Macclenny, FL",
        "Glen St. Mary, FL",
        "Baxter, FL",
        "Cuyler, FL",
        "Olustee, FL",
        "Sanderson, FL",
        "Taylor, FL",
        "Black Bottom/Trail Ridge, FL",
        "Two Bridges, FL",
        "Edd/Eddy Grade, FL",
        "Manning, FL",
        "Jacksonville, FL",
        "Jacksonville Beach, FL",
        "Atlantic Beach, FL",
        "Neptune Beach, FL",
        "Baldwin, FL",
        "St. Augustine, FL",
        "St. Augustine Beach, FL",
        "Butler Beach, FL",
        "Crescent Beach, FL",
        "Flagler Estates, FL",
        "Fruit Cove, FL",
        "Nocatee, FL",
        "Palm Valley, FL",
        "Sawgrass, FL",
        "St. Augustine Shores, FL",
        "St. Augustine South, FL",
        "Villano Beach, FL",
        "World Golf Village, FL",
        "Bakersville, FL",
        "Elkton, FL",
        "Hastings, FL",
        "Julington Creek Plantation, FL",
        "Mill Creek, FL",
        "Ponte Verdra Beach, FL",
        "St. Johns, FL",
        "Spuds, FL",
        "Summer Haven, FL",
        "Switzerland, FL",
        "Vermont Heights, FL",
        "Green Cove Springs, FL",
        "Keystone Heights, FL",
        "Orange Park, FL",
        "Penny Farms, FL",
        "Asbury Lake, FL",
        "Bellair-Meadowbrook Terrace, FL",
        "Fleming Island, FL",
        "Lakeside, FL",
        "Middleburg, FL",
        "Oakleaf Plantation, FL",
        "Belmore, FL",
        "Clay Hill, FL",
        "Doctors Inlet, FL",
        "Hibernia, FL",
        "Lake Geneva, FL",
        "McRae, FL",
        "Virginia Village, FL",
        "Fernandina Beach, FL",
        "Callahan, FL",
        "Hilliard, FL",
        "Nassau Village-Ratliff, FL",
        "Yulee, FL",
        "Amelia City, FL",
        "American Beach, FL",
        "Andrews, FL",
        "Becker, FL",
        "Boulogne, FL",
        "Bryceville, FL",
        "Chester, FL",
        "Crandall, FL",
        "Crawford, FL",
        "Crawford, FL",
        "Dahoma, FL",
        "Dyal, FL",
        "Evergreen, FL",
        "Franklintown, FL",
        "Glenwood, FL",
        "Gross, FL",
        "Hedges, FL",
        "Hero, FL",
        "Ingle, FL",
        "Italia, FL",
        "Keene, FL",
        "Kent, FL",
        "Kings Ferry, FL",
        "Lessie, FL",
        "Mattox, FL",
        "Nassauville, FL",
        "O'Neil, FL",
        "Verdie, FL",
        "Yulee Heights, FL"
    ],
    "Orlando, FL": [
        'Orlando, FL',
        'Kissimmee, FL',
        'Sanford, FL',
        'Alafaya, FL',
        'Altamonte Springs, FL',
        'Apopka, FL',
        'Azalea Park, FL',
        'Buenaventura Lakes, FL',
        'Casselberry, FL',
        'Clermont, FL',
        'Conway, FL',
        'DeBary, FL',
        'Deltona, FL',
        'Doctor Phillips, FL',
        'Eustis, FL',
        'Fairview Shores, FL',
        'Four Corners, FL',
        'Goldenrod, FL',
        'Horizon West, FL',
        "Hunter's Creek, FL",
        'Lake Butler, FL',
        'Lake Mary, FL',
        'Lockhart, FL',
        'Longwood, FL',
        'Maitland, FL',
        'Meadow Woods, FL',
        'Mount Dora, FL',
        'Oak Ridge, FL',
        'Ocoee, FL',
        'Oviedo, FL',
        'Pine Castle, FL',
        'Pine Hills, FL',
        'Poinciana, FL',
        'Saint Cloud, FL',
        'Southchase, FL',
        'Tavares, FL',
        'University, FL',
        'Wekiva Springs, FL',
        'Winter Garden, FL',
        'Winter Park, FL',
        'Winter Springs, FL',
        'Bay Lake, FL',
        'Bay Hill, FL',
        'Bithlo, FL',
        'Belle Isle, FL',
        'Campbell, FL',
        'Celebration, FL',
        'Chuluota, FL',
        'Eatonville, FL',
        'Edgewood, FL',
        'Ferndale, FL',
        'Fern Park, FL',
        'Geneva, FL',
        'Gotha, FL',
        'Groveland, FL',
        'Heathrow, FL',
        'Holden Heights, FL',
        'Lake Buena Vista, FL',
        'Lake Hart, FL',
        'Midway, FL',
        'Minneola, FL',
        'Montverde, FL',
        'Mount Plymouth, FL',
        'Oakland, FL',
        'Okahumpka, FL',
        'Orlo Vista, FL',
        'Paradise Heights, FL',
        'Sky Lake, FL',
        'Sorrento, FL',
        'South Apopka, FL',
        'Taft, FL',
        'Tangelo Park, FL',
        'Tangerine, FL',
        'Tildenville, FL',
        'Union Park, FL',
        'Vineland, FL',
        'Wedgefield, FL',
        'Williamsburg, FL',
        'Windermere, FL',
        'Zellwood, FL'
    ],
    "Seminole County, FL": [
        "Altamonte Springs, FL",
        "Casselberry, FL",
        "Lake Mary, FL",
        "Longwood, FL",
        "Oviedo, FL",
        "Sanford, FL",
        "Winter Springs, FL",
        "Black Hammock, FL",
        "Chuluota, FL",
        "Fern Park, FL",
        "Forest City, FL",
        "Geneva, FL",
        "Goldenrod, FL",
        "Heathrow, FL",
        "Midway, FL",
        "Wekiwa Springs, FL",
        "Bertha, FL",
        "Indian Mound Village, FL",
        "Lake Monroe, FL",
        "Slavia, FL",
        "Sanlando Springs, FL",
        "Taintsville, FL",
        "Tuskawilla, FL"
    ],
    "St. Johns County, FL": [
        "St. Augustine, FL",
        "St. Augustine Beach, FL",
        "Butler Beach, FL",
        "Crescent Beach, FL",
        "Flagler Estates, FL",
        "Fruit Cove, FL",
        "Nocatee, FL",
        "Palm Valley, FL",
        "Sawgrass, FL",
        "St. Augustine Shores, FL",
        "St. Augustine South, FL",
        "Villano Beach, FL",
        "World Golf Village, FL",
        "Bakersville, FL",
        "Elkton, FL",
        "Hastings, FL",
        "Julington Creek Plantation, FL",
        "Mill Creek, FL",
        "Ponte Verdra Beach, FL",
        "St. Johns, FL",
        "Spuds, FL",
        "Summer Haven, FL",
        "Switzerland, FL",
        "Vermont Heights, FL"
    ],
    "Atlanta, GA": [
        'Brookhaven, GA',
        'Peachtree Corners, GA',
        'Cumberland, GA',
        'Perimeter Center, GA',
        'Gwinnett Place, GA',
        'Sugarloaf, GA',
        'East Cobb, GA',
        'Roswell, GA',
        'Atlanta, GA',
        'South Fulton, GA',
        'Sandy Springs, GA',
        'Roswell, GA',
        'Johns Creek, GA',
        'Alpharetta, GA',
        'Marietta, GA',
        'Stonecrest, GA',
        'Smyrna, GA',
        'Dunwoody, GA',
        'Mableton, GA',
        'Peachtree City, GA',
        'Gainesville, GA',
        'East Point, GA',
        'Tucker, GA',
        'Newnan, GA',
        'Redan, GA',
        'Milton, GA',
        'Douglasville, GA',
        'Kennesaw, GA',
        'Chamblee, GA',
        'Lawrenceville, GA',
        'Duluth, GA',
        'Stockbridge, GA',
        'Carrollton, GA',
        'Woodstock, GA',
        'Griffin, GA',
        'Candler-McAfee, GA',
        'Canton, GA',
        'McDonough, GA',
        'Acworth, GA',
        'Cartersville, GA',
        'Union City, GA',
        'Decatur, GA',
        'North Druid Hills, GA',
        'Sugar Hill, GA',
        'Forest Park, GA',
        'Snellville, GA',
        'North Decatur, GA',
        'Fayetteville, GA',
        'Lithia Springs, GA',
        'Suwanee, GA',
        'Conyers, GA',
        'Belvedere Park, GA',
        'Riverdale, GA',
        'Druid Hills, GA',
        'Winder, GA',
        'Villa Rica, GA',
        'College Park, GA',
        'Powder Springs, GA',
        'Monroe, GA',
        'Covington, GA',
        'Fairburn, GA',
        'Buford, GA',
        'Lilburn, GA',
        'Mountain Park (Gwinnett), GA',
        'Dallas, GA',
        'Loganville, GA',
        'Panthersville, GA',
        'Vinings, GA',
        'Tyrone, GA',
        'Thomaston, GA',
        'Norcross, GA',
        'Doraville, GA',
        'Clarkston, GA',
        'Braselton, GA',
        'Irondale, GA',
        'Centerville, GA',
        'Hampton, GA',
        'Auburn, GA',
        'Barnesville, GA',
        'Austell, GA',
        'Morrow, GA',
        'Lovejoy, GA',
        'Hapeville, GA',
        'Conley, GA',
        'Stone Mountain, GA',
        'Flowery Branch, GA',
        'Cumming, GA',
        'Locust Grove, GA',
        'Jonesboro, GA',
        'Palmetto, GA',
        'Dacula, GA',
        'Bonanza, GA',
        'Avondale Estates, GA',
        'Lakeview Estates, GA',
        'Grayson, GA',
        'Lake City, GA',
        'Chattahoochee Hills, GA',
        'Lithonia, GA',
        'Berkeley Lake, GA'
    ],
    "Tampa, FL": [
        "Tampa, FL"
    ],
    "Pocatello, ID": [
        "Arimo, ID",
        "Chubbuck, ID",
        "Downey, ID",
        "Inkom, ID",
        "Lava Hot Springs, ID",
        "McCammon, ID",
        "Pocatello, ID",
        "Fort Hall, ID",
        "Tyhee, ID",
        "Blackrock, ID",
        "Portneuf, ID",
        "Red Rock Junction, ID",
        "Robin, ID",
        "Swanlake, ID",
        "Virginia, ID",
        "Zenda, ID"
    ],
    "Rockford, IL": [
        "Loves Park, IL",
        "Rockford, IL",
        "South Beloit, IL",
        "Cherry Valley, IL",
        "Durand, IL",
        "Machesney Park, IL",
        "New Milford, IL",
        "Pecatonica, IL",
        "Rockton, IL",
        "Roscoe, IL",
        "Winnebago, IL",
        "Alworth, IL",
        "Argyle, IL",
        "Harlem, IL",
        "Harrison, IL",
        "Kishwaukee, IL",
        "Latham Park, IL",
        "Seward, IL",
        "Shirland, IL",
        "Wempletown, IL",
        "Westfield Corners, IL",
        "Burritt, IL",
        "Harrison, IL",
        "Laona, IL",
        "Owen, IL",
        "Camp Grant, IL"
    ],
    "Springfield, KY": [
        "Bear Wallow, KY",
        "Brush Grove, KY",
        "Fredericktown, KY",
        "Mackville, KY",
        "Manton, KY",
        "Pleasant Grove, KY",
        "Saint Catharine, KY",
        "Springfield, KY",
        "Thompsonville, KY",
        "Willisburg, KY",
        "Mooresville, KY",
        "Maud, KY"
    ],
    "Minneapolis, MN": [
        'Bloomington, MN',
        'Brooklyn Center, MN',
        'Brooklyn Park, MN',
        'Champlin, MN',
        'Chanhassen, MN',
        'Corcoran, MN',
        'Crystal, MN',
        'Dayton, MN',
        'Deephaven, MN',
        'Eden Prairie, MN',
        'Edina, MN',
        'Excelsior, MN',
        'Golden Valley, MN',
        'Greenfield, MN',
        'Greenwood, MN',
        'Hanover, MN',
        'Hopkins, MN',
        'Independence, MN',
        'Long Lake, MN',
        'Loretto, MN',
        'Maple Grove, MN',
        'Maple Plain, MN',
        'Medicine Lake, MN',
        'Medina, MN',
        'Minneapolis, MN',
        'Minnetonka, MN',
        'Minnetonka Beach, MN',
        'Minnetrista, MN',
        'Mound, MN',
        'New Hope, MN',
        'Orono, MN',
        'Osseo, MN',
        'Plymouth, MN',
        'Richfield, MN',
        'Robbinsdale, MN',
        'Rockford, MN',
        'Rogers, MN',
        'Shorewood, MN',
        'Spring Park, MN',
        'St. Anthony, MN',
        'St. Bonifacius, MN',
        'St. Louis Park, MN',
        'Tonka Bay, MN',
        'Wayzata, MN',
        'Woodland, MN'
    ],
    "Kansas City, MO": [
        "Blue Springs, MO",
        "Buckner, MO",
        "Grain Valley, MO",
        "Grandview, MO",
        "Greenwood, MO",
        "Independence, MO",
        "Kansas City, MO",
        "Lake Lotawana, MO",
        "Lake Tapawingo, MO",
        "Lee's Summit, MO",
        "Levasy, MO",
        "Lone Jack, MO",
        "Oak Grove, MO",
        "Pleasant Hill, MO",
        "Raytown, MO",
        "Sugar Creek, MO",
        "River Bend, MO",
        "Sibley, MO",
        "Unity Village, MO",
        "Blue Summit, MO",
        "Tarsney Lakes, MO",
        "Atherton, MO",
        "Blue Mills, MO",
        "Blue Summit, MO",
        "Cockrell, MO",
        "Courtney, MO",
        "Hiler, MO",
        "Hicks County, MO",
        "Oakland, MO",
        "Pink Hill, MO",
        "Sni Mills, MO",
        "Tarsney, MO",
        "Camden Point, MO",
        "Dearborn, MO",
        "Edgerton, MO",
        "Houston Lake, MO",
        "Lake Waukomis, MO",
        "Northmoor, MO",
        "Parkville, MO",
        "Platte City, MO",
        "Platte Woods, MO",
        "Riverside, MO",
        "Smithville, MO",
        "Tracy, MO",
        "Weatherby Lake, MO",
        "Weston, MO",
        "Farley, MO",
        "Ferrelview, MO",
        "Iatan, MO",
        "Ridgely, MO",
        "Carroll, MO,",
        "Flair, MO",
        "Fox, MO",
        "Green, MO",
        "Kickapoo, MO",
        "Lee, MO",
        "Marshall, MO",
        "May, MO",
        "Pawnee, MO",
        "Pettis, MO",
        "Preston, MO",
        "Sioux, MO",
        "Waldron, MO",
        "Weston, MO",
        "Beverly, MO",
        "Dye, MO",
        "East Leavenworth, MO",
        "Edgerton Junction, MO",
        "Hoover, MO",
        "Kerrville, MO",
        "New Market, MO",
        "Stillings, MO",
        "Stubbs, MO",
        "Waldron, MO",
        "West Platte, MO",
        "Woodruff, MO",
        "Avondale, MO",
        "Birmingham, MO",
        "Claycomo, MO",
        "Excelsior Estates, MO",
        "Excelsior Springs, MO",
        "Gladstone, MO",
        "Glenaire, MO",
        "Holt, MO",
        "Kearney, MO",
        "Lawson, MO",
        "Liberty, MO",
        "Missouri County, MO",
        "Mosby, MO",
        "North Kansas City, MO",
        "Oaks, MO",
        "Oakview, MO",
        "Oakwood, MO",
        "Oakwood Park, MO",
        "Pleasant Valley, MO",
        "Prathersville, MO",
        "Randolph, MO",
        "Smithville, MO",
        "Sugar Creek, MO",
        "Arley, MO",
        "Chandler, MO",
        "Claysville, MO",
        "Clevenger, MO",
        "Ectonville, MO",
        "Miltondale, MO",
        "Roosterville, MO",
        "Stockdale, MO",
        "Winner, MO",
        "Archie, MO",
        "Belton, MO",
        "Cleveland, MO",
        "Creighton, MO",
        "Drexel, MO",
        "East Lynne, MO",
        "Freeman, MO",
        "Garden City, MO",
        "Harrisonville, MO",
        "Lake Annette, MO",
        "Lake Winnebago, MO",
        "Peculiar, MO",
        "Pleasant Hill, MO",
        "Raymore, MO",
        "Strasburg, MO",
        "Baldwin Park, MO",
        "Gunn City, MO",
        "Riverview Estates, MO",
        "West Line, MO",
        "Lock Lloyd, MO",
        "Martin City, MO",
        "Austin, MO",
        "Coleman, MO",
        "Daugherty, MO",
        "Dayton, MO",
        "Everett, MO",
        "Jaudon, MO",
        "Lisle, MO",
        "Lone Tree, MO",
        "Main City, MO",
        "Wingate, MO"
    ],
    "Charlotte, NC": [],
    "Durham, NC": [],
    "Wake County, NC": [],
    "Winston-Salem, NC": [],
    "Lincoln, NE": [],
    "Omaha, NE": [],
    "Burlington County, NJ": [],
    "Albuquerque, NM": [],
    "Las Vegas, NV": [],
    "Reno, NV": [],
    "Long Island": [],
    "Akron, OH": [],
    "Cincinnati, OH": [],
    "Mount Vernon, OH": [],
    "Bucks County, PA": [],
    "Centre County, PA": [],
    "Chester County, PA": [],
    "Delaware County, PA": [],
    "Montgomery County, PA": [],
    "Philadephia County, PA": [],
    "Pittsburgh, PA": [],
    "York, PA": [],
    "Beaufort County, SC": [],
    "Charleston, SC": [],
    "Sioux Falls, SD": [],
    "Nashville, TN": [],
    "Amarillo, TX": [],
    "Austin, TX": [],
    "Beaumont, TX": [],
    "Dallas, TX": [],
    "El Paso, TX": [],
    "Houston, TX": [],
    "McAllen, TX": [],
    "San Antonio, TX": [],
    "Fairfax, VA": [],
    "Loudon County, VA": [],
    "Appleton, WI": [],
    "Green Bay, WI": [],
    "Milwaukee, WI": []
}
