CITY_TOWNS_DICT = {
    "Fort Smith, AR": [
        'Fort Smith, AR',
        'Van Buren, AR',
        'Alma, AR',
        'Arkoma, OK',
        'Barling, AR',
        'Cedarville, AR',
        'Charleston, AR',
        'Greenwood, AR',
        'Heavener, OK',
        'Lavaca, AR',
        'Mansfield, AR',
        'Mulberry, AR',
        'Muldrow, OK',
        'Ozark, AR',
        'Panama, OK',
        'Pocola, OK',
        'Poteau, OK',
        'Roland, OK',
        'Sallisaw, OK',
        'Spiro, OK',
        'Talihina, OK',
        'Vian, OK',
        'Wister, OK',
        'Bonanza, AR',
        'Brent, OK',
        'Brushy, OK',
        'Carlisle, OK',
        'Central City, AR',
        'Dyer, AR',
        'Gore, OK',
        'Hackett, AR',
        'Hartford, AR',
        'Howe, OK',
        'Huntington, AR',
        'Kibler, AR',
        'Mountainburg, AR',
        'Rock Island, OK',
        'Shady Point, OK',
        'Akins, OK',
        'Altus, AR',
        'Belfonte, OK',
        'Bokoshe, OK',
        'Branch, AR',
        'Cameron, OK',
        'Cecil, AR',
        'Chester, AR',
        'Cowlington, OK',
        'Denning, AR',
        'Dwight Mission, OK',
        'Evening Shade, OK',
        'Fanshawe, OK',
        'Flute Springs, OK',
        'Fort Coffee, OK',
        'Gans, OK',
        'Le Flore, OK',
        'Long, OK',
        'Marble City Community, OK',
        'Marble City, OK',
        'McKey, OK',
        'Midland, AR',
        'Moffett, OK',
        'Notchietown, OK',
        'Paradise Hill, OK',
        'Pinhook Corners, OK',
        'Redbird Smith, OK',
        'Remy, OK',
        'Rudy, AR',
        'Short, OK',
        'Stony Point, OK',
        'Sycamore, Sequoyah County, OK',
        'Wiederkehr Village, AR',
        'Big Cedar, OK',
        'Dora, AR',
        'Hodgen, OK',
        'Monroe, OK',
        'Muse, OK',
        'Skullyville, OK',
        'Whitesboro, OK'
    ],
    "Phoenix, AZ": [
        'Phoenix, AZ',
        'Mesa, AZ',
        'Chandler, AZ',
        'Gilbert, AZ',
        'Glendale, AZ',
        'Scottsdale, AZ',
        'Peoria, AZ',
        'Tempe, AZ',
        'Surprise, AZ',
        'Goodyear, AZ',
        'Buckeye, AZ',
        'Avondale, AZ',
        'Queen Creek, AZ',
        'Maricopa, AZ',
        'Casa Grande, AZ',
        'Apache Junction, AZ',
        'El Mirage, AZ',
        'Florence, AZ',
        'Fountain Hills, AZ',
        'Eloy, AZ',
        'Coolidge, AZ',
        'Paradise Valley, AZ',
        'Wickenburg, AZ',
        'Tolleson, AZ',
        'Youngtown, AZ',
        'Litchfield Park, AZ',
        'Guadalupe, AZ',
        'Cave Creek, AZ',
        'Carefree, AZ',
        'Superior, AZ',
        'Kearny, AZ',
        'Gila Bend, AZ',
        'Mammoth, AZ',
        'San Tan Valley, AZ',
        'Sun City, AZ',
        'Sun City West, AZ',
        'Anthem, AZ',
        'New River, AZ',
        'Sun Lakes, AZ',
        'Gold Canyon, AZ',
        'Arizona City, AZ',
        'Aguila, AZ',
        'Ak-Chin Village, AZ',
        'Arlington, AZ',
        'Bapchule, AZ',
        'Cactus Forest, AZ',
        'Chuichu, AZ',
        'Circle City, AZ',
        'Eleven Mile Corner, AZ',
        'Komatke, AZ',
        'La Palma, AZ',
        'Liberty, AZ',
        'Morristown, AZ',
        'Olberg, AZ',
        'Palo Verde, AZ',
        'Queen Valley, AZ',
        'Red Rock, AZ',
        'Rio Verde, AZ',
        'Sacaton, AZ',
        'Stanfield, AZ',
        'Tonopah, AZ',
        'Tortilla Flat, AZ',
        'Valley Farms, AZ',
        'Waddell, AZ',
        'Wintersburg, AZ',
        'Wittmann, AZ'
    ],
    "Tucson, AZ": [
        "South Tuscon, AZ",
        "Tucson, AZ",
        "Marana, AZ",
        "Ora Valley, AZ",
        "Sahuarita, AZ",
        "Casa Adobes, AZ",
        "Catalina Foothills, AZ",
        "Drexel Heights, AZ",
        "Green Valley, AZ",
        "Tanque Verde, AZ",
        "Flowing Wells, AZ",
        "Tucson Estates, AZ",
        "Vail, AZ",
        "Picture Rocks, AZ",
        "Valencia West, AZ",
        "Catalina, AZ"
        "Avra Valley, AZ",
        "Corona de Tucson, AZ",
        "South Tuscon, AZ",
        "Three Points, AZ",
        "Summit, AZ",
        "Rincon Valley, AZ",
        "Ajo, AZ",
        "Sells, AZ",
        "Arivaca Junction, AZ"
    ],
    "La Quinta, CA": [
        "Cathedral City, CA",
        "Coachella, CA",
        "Desert Hot Springs, CA",
        "Indian Wells, CA",
        "Indio, CA",
        "La Quinta, CA",
        "Palm Desert, CA",
        "Palm Springs, CA",
        "Rancho Mirage, CA"
    ],
    "Orange County, CA": [
        'Aliso Viejo, CA',
        'Anaheim, CA',
        'Brea, CA',
        'Buena Park, CA',
        'Costa Mesa, CA',
        'Cypress, CA',
        'Dana Point, CA',
        'Fountain Valley, CA',
        'Fullerton, CA',
        'Garden Grove, CA',
        'Huntington Beach, CA',
        'Irvine, CA',
        'La Habra, CA',
        'La Palma, CA',
        'Laguna Beach, CA',
        'Laguna Hills, CA',
        'Laguna Niguel, CA',
        'Laguna Woods, CA',
        'Lake Forest, CA',
        'Los Alamitos, CA',
        'Mission Viejo, CA',
        'Newport Beach, CA',
        'Orange, CA',
        'Placentia, CA',
        'Rancho Santa Margarita, CA',
        'San Clemente, CA',
        'San Juan Capistrano, CA',
        'Santa Ana, CA',
        'Seal Beach, CA',
        'Stanton, CA',
        'Tustin, CA',
        'Villa Park, CA',
        'Westminster, CA',
        'Yorba Linda, CA',
        'Anaheim Island, CA',
        'Coto de Caza, CA',
        'Emerald Bay, CA',
        'Ladera Ranch, CA',
        'Las Flores, CA',
        'Midway City, CA',
        'Modjeska Canyon, CA',
        'North Tustin, CA'
    ],
    "Clearwater, FL": [
        'Tampa, FL',
        'St. Petersburg, FL',
        'Clearwater, FL',
        'Lakeland, FL',
        'Riverview, FL',
        'Brandon, FL',
        'Spring Hill, FL',
        'Apollo Beach, FL',
        'Bayonet Point, FL',
        'Bloomingdale, FL',
        'Citrus Park, FL',
        'Cheval, FL',
        'Dunedin, FL',
        'Egypt Lake-Leto, FL',
        'East Lake, FL',
        'East Lake-Orient Park, FL',
        'Elfers, FL',
        'Fish Hawk, FL',
        'Greater Carrollwood, FL',
        'Greater Northdale, FL',
        'Gulfport, FL',
        'Holiday, FL',
        'Hudson, FL',
        'Jasmine Estates, FL',
        'Keystone, FL',
        'Lake Magdalene, FL',
        "Land o' Lakes, FL",
        'Largo, FL',
        'Lealman, FL',
        'Lutz, FL',
        'New Port Richey, FL',
        'Mango, FL',
        'Oldsmar, FL',
        'Palm Harbor, FL',
        'Palm River-Clair Mel, FL',
        'Pinellas Park, FL',
        'Plant City, FL',
        'Ruskin, FL',
        'Safety Harbor, FL',
        'Shady Hills, FL',
        'Seminole, FL',
        'Sun Center, FL',
        'Tarpon Springs, FL',
        'Temple Terrace, FL',
        'Thonotosassa, FL',
        "Town 'n' Country, FL",
        'Trinity, FL',
        'Valrico, FL',
        'Wesley Chapel, FL',
        'West Lealman, FL',
        'Westchase, FL',
        'Zephyrhills, FL'
    ],
    "Destin, FL": [
        "Crestview, FL",
        "Fort Walton Beach, FL",
        "DeFuniak Springs, FL",
        "Destin, FL",
        "Niceville, FL",
        "Valparaiso, FL",
        "Freeport, FL",
        "Mary Esther, FL",
        "Laurel Hill, FL",
        "Paxton, FL",
        "Shalimar, FL",
        "Cinco Bayou, FL"
    ],
    "Fort Lauderdale, FL": [
        'Miami, FL',
        'Hialeah, FL',
        'Fort Lauderdale, FL',
        'Pembroke Pines, FL',
        'Hollywood, FL',
        'Miramar, FL',
        'Coral Springs, FL',
        'Miami Gardens, FL',
        'Pompano Beach, FL',
        'West Palm Beach, FL',
        'Davie, FL',
        'Boca Raton, FL',
        'Sunrise, FL',
        'Plantation, FL',
        'Miami Beach, FL',
        'Deerfield Beach, FL',
        'Boynton Beach, FL',
        'Lauderhill, FL',
        'Weston, FL',
        'Homestead, FL',
        'Aventura, FL',
        'Belle Glade, FL',
        'Boca Del Mar, FL',
        'Boca Raton, FL',
        'Boynton Beach, FL',
        'Brownsville, FL',
        'Coconut Creek, FL',
        'Cooper City, FL',
        'Coral Gables, FL',
        'Coral Terrace, FL',
        'Country Club, FL',
        'Country Walk, FL',
        'Cutler Bay, FL',
        'Dania Beach, FL',
        'Deerfield Beach, FL',
        'Delray Beach, FL',
        'Doral, FL',
        'Florida City, FL',
        'Fontainebleau, FL',
        'Gladeview, FL',
        'Glenvar Heights, FL',
        'Goulds, FL',
        'Greenacres, FL',
        'Hallandale Beach, FL',
        'Hamptons at Boca Raton, FL',
        'Hialeah Gardens, FL',
        'Homestead, FL',
        'Ives Estates, FL',
        'Jupiter, FL',
        'Kendale Lakes, FL',
        'Kendall West, FL',
        'Kendall, FL',
        'Key Biscayne, FL',
        'Kings Point, FL',
        'Lake Worth Corridor, FL',
        'Lake Worth Beach, FL',
        'Lauderdale Lakes, FL',
        'Lauderhill, FL',
        'Leisure City, FL',
        'Lighthouse Point, FL',
        'Margate, FL',
        'Miami Beach, FL',
        'Miami Lakes, FL',
        'Miami Shores, FL',
        'Miami Springs, FL',
        'North Lauderdale, FL',
        'North Miami Beach, FL',
        'North Miami, FL',
        'North Palm Beach, FL',
        'Oakland Park, FL',
        'Ojus, FL',
        'Olympia Heights, FL',
        'Opa-locka, FL',
        'Palm Beach Gardens, FL',
        'Palm Beach, FL',
        'Palm Springs, FL',
        'Palmetto Bay, FL',
        'Palmetto Estates, FL',
        'Parkland, FL',
        'Pinecrest, FL',
        'Pinewood, FL',
        'Plantation, FL',
        'Princeton, FL',
        'Richmond West, FL',
        'Riviera Beach, FL',
        'Royal Palm Beach, FL',
        'Sandalfoot Cove, FL',
        'South Miami Heights, FL',
        'South Miami, FL',
        'Sunny Isles Beach, FL',
        'Sunrise, FL',
        'Sunset, FL',
        'Sweetwater, FL',
        'Tamarac, FL',
        'Tamiami, FL',
        'The Crossings, FL',
        'The Hammocks, FL',
        'University Park, FL',
        'Wellington, FL',
        'West Little River, FL',
        'West Park, FL',
        'Westchester, FL',
        'Weston, FL',
        'Westwood Lakes, FL',
        'Wilton Manors, FL',
        'Atlantis, FL',
        'Bal Harbour, FL',
        'Bay Harbor Islands, FL',
        'Belle Glade Camp, FL',
        'Biscayne Park, FL',
        'Boca Pointe, FL',
        'Boulevard Gardens, FL',
        'Briny Breezes, FL',
        'Broadview Park, FL',
        'Canal Point, FL',
        'Century Village, FL',
        'Cypress Lakes, FL',
        'Dunes Road, FL',
        'El Portal, FL',
        'Fisher Island, FL',
        'Franklin Park, FL',
        'Fremd Village-Padgett Island, FL',
        'Glen Ridge, FL',
        'Godfrey Road, FL',
        'Golden Beach, FL',
        'Golden Lakes, FL',
        'Golf, FL',
        'Gulf Stream, FL',
        'Gun Club Estates, FL',
        'Haverhill, FL',
        'High Point, FL',
        'Highland Beach, FL',
        'Hillsboro Beach, FL',
        'Hillsboro Pines, FL',
        'Homestead Base, FL',
        'Hypoluxo, FL',
        'Indian Creek, FL',
        'Islandia, FL',
        'Juno Beach, FL',
        'Juno Ridge, FL',
        'Jupiter Inlet Colony, FL',
        'Lake Belvedere Estates, FL',
        'Lake Clarke Shores, FL',
        'Lake Harbor, FL',
        'Lake Park, FL',
        'Lakeside Green, FL',
        'Lantana, FL',
        'Lauderdale-by-the-Sea, FL',
        'Lazy Lake, FL',
        'Limestone Creek, FL',
        'Manalapan, FL',
        'Mangonia Park, FL',
        'Medley, FL',
        'Mission Bay, FL',
        'Naranja, FL',
        'North Bay Village, FL',
        'Ocean Ridge, FL',
        'Pahokee, FL',
        'Palm Beach Shores, FL',
        'Palm Springs North, FL',
        'Pembroke Park, FL',
        'Plantation Mobile Home Park, FL',
        'Richmond Heights, FL',
        'Roosevelt Gardens, FL',
        'Royal Palm Estates, FL',
        'Schall Circle, FL',
        'Sea Ranch Lakes, FL',
        'Seminole Manor, FL',
        'South Bay, FL',
        'South Palm Beach, FL',
        'Southwest Ranches, FL',
        'Stacy Street, FL',
        'Surfside, FL',
        'Tequesta, FL',
        'Three Lakes, FL',
        'Villages of Oriole, FL',
        'Virginia Gardens, FL',
        'Washington Park, FL',
        'Westlake, FL',
        'West Miami, FL',
        'West Perrine, FL',
        'Westview, FL',
        'Whisper Walk, FL'
    ],
    "Jacksonville, FL": [
        "Macclenny, FL",
        "Glen St. Mary, FL",
        "Baxter, FL",
        "Cuyler, FL",
        "Olustee, FL",
        "Sanderson, FL",
        "Taylor, FL",
        "Black Bottom/Trail Ridge, FL",
        "Two Bridges, FL",
        "Edd/Eddy Grade, FL",
        "Manning, FL",
        "Jacksonville, FL",
        "Jacksonville Beach, FL",
        "Atlantic Beach, FL",
        "Neptune Beach, FL",
        "Baldwin, FL",
        "St. Augustine, FL",
        "St. Augustine Beach, FL",
        "Butler Beach, FL",
        "Crescent Beach, FL",
        "Flagler Estates, FL",
        "Fruit Cove, FL",
        "Nocatee, FL",
        "Palm Valley, FL",
        "Sawgrass, FL",
        "St. Augustine Shores, FL",
        "St. Augustine South, FL",
        "Villano Beach, FL",
        "World Golf Village, FL",
        "Bakersville, FL",
        "Elkton, FL",
        "Hastings, FL",
        "Julington Creek Plantation, FL",
        "Mill Creek, FL",
        "Ponte Verdra Beach, FL",
        "St. Johns, FL",
        "Spuds, FL",
        "Summer Haven, FL",
        "Switzerland, FL",
        "Vermont Heights, FL",
        "Green Cove Springs, FL",
        "Keystone Heights, FL",
        "Orange Park, FL",
        "Penny Farms, FL",
        "Asbury Lake, FL",
        "Bellair-Meadowbrook Terrace, FL",
        "Fleming Island, FL",
        "Lakeside, FL",
        "Middleburg, FL",
        "Oakleaf Plantation, FL",
        "Belmore, FL",
        "Clay Hill, FL",
        "Doctors Inlet, FL",
        "Hibernia, FL",
        "Lake Geneva, FL",
        "McRae, FL",
        "Virginia Village, FL",
        "Fernandina Beach, FL",
        "Callahan, FL",
        "Hilliard, FL",
        "Nassau Village-Ratliff, FL",
        "Yulee, FL",
        "Amelia City, FL",
        "American Beach, FL",
        "Andrews, FL",
        "Becker, FL",
        "Boulogne, FL",
        "Bryceville, FL",
        "Chester, FL",
        "Crandall, FL",
        "Crawford, FL",
        "Crawford, FL",
        "Dahoma, FL",
        "Dyal, FL",
        "Evergreen, FL",
        "Franklintown, FL",
        "Glenwood, FL",
        "Gross, FL",
        "Hedges, FL",
        "Hero, FL",
        "Ingle, FL",
        "Italia, FL",
        "Keene, FL",
        "Kent, FL",
        "Kings Ferry, FL",
        "Lessie, FL",
        "Mattox, FL",
        "Nassauville, FL",
        "O'Neil, FL",
        "Verdie, FL",
        "Yulee Heights, FL"
    ],
    "Orlando, FL": [
        'Orlando, FL',
        'Kissimmee, FL',
        'Sanford, FL',
        'Alafaya, FL',
        'Altamonte Springs, FL',
        'Apopka, FL',
        'Azalea Park, FL',
        'Buenaventura Lakes, FL',
        'Casselberry, FL',
        'Clermont, FL',
        'Conway, FL',
        'DeBary, FL',
        'Deltona, FL',
        'Doctor Phillips, FL',
        'Eustis, FL',
        'Fairview Shores, FL',
        'Four Corners, FL',
        'Goldenrod, FL',
        'Horizon West, FL',
        "Hunter's Creek, FL",
        'Lake Butler, FL',
        'Lake Mary, FL',
        'Lockhart, FL',
        'Longwood, FL',
        'Maitland, FL',
        'Meadow Woods, FL',
        'Mount Dora, FL',
        'Oak Ridge, FL',
        'Ocoee, FL',
        'Oviedo, FL',
        'Pine Castle, FL',
        'Pine Hills, FL',
        'Poinciana, FL',
        'Saint Cloud, FL',
        'Southchase, FL',
        'Tavares, FL',
        'University, FL',
        'Wekiva Springs, FL',
        'Winter Garden, FL',
        'Winter Park, FL',
        'Winter Springs, FL',
        'Bay Lake, FL',
        'Bay Hill, FL',
        'Bithlo, FL',
        'Belle Isle, FL',
        'Campbell, FL',
        'Celebration, FL',
        'Chuluota, FL',
        'Eatonville, FL',
        'Edgewood, FL',
        'Ferndale, FL',
        'Fern Park, FL',
        'Geneva, FL',
        'Gotha, FL',
        'Groveland, FL',
        'Heathrow, FL',
        'Holden Heights, FL',
        'Lake Buena Vista, FL',
        'Lake Hart, FL',
        'Midway, FL',
        'Minneola, FL',
        'Montverde, FL',
        'Mount Plymouth, FL',
        'Oakland, FL',
        'Okahumpka, FL',
        'Orlo Vista, FL',
        'Paradise Heights, FL',
        'Sky Lake, FL',
        'Sorrento, FL',
        'South Apopka, FL',
        'Taft, FL',
        'Tangelo Park, FL',
        'Tangerine, FL',
        'Tildenville, FL',
        'Union Park, FL',
        'Vineland, FL',
        'Wedgefield, FL',
        'Williamsburg, FL',
        'Windermere, FL',
        'Zellwood, FL'
    ],
    "Seminole County, FL": [
        "Altamonte Springs, FL",
        "Casselberry, FL",
        "Lake Mary, FL",
        "Longwood, FL",
        "Oviedo, FL",
        "Sanford, FL",
        "Winter Springs, FL",
        "Black Hammock, FL",
        "Chuluota, FL",
        "Fern Park, FL",
        "Forest City, FL",
        "Geneva, FL",
        "Goldenrod, FL",
        "Heathrow, FL",
        "Midway, FL",
        "Wekiwa Springs, FL",
        "Bertha, FL",
        "Indian Mound Village, FL",
        "Lake Monroe, FL",
        "Slavia, FL",
        "Sanlando Springs, FL",
        "Taintsville, FL",
        "Tuskawilla, FL"
    ],
    "St. Johns County, FL": [
        "St. Augustine, FL",
        "St. Augustine Beach, FL",
        "Butler Beach, FL",
        "Crescent Beach, FL",
        "Flagler Estates, FL",
        "Fruit Cove, FL",
        "Nocatee, FL",
        "Palm Valley, FL",
        "Sawgrass, FL",
        "St. Augustine Shores, FL",
        "St. Augustine South, FL",
        "Villano Beach, FL",
        "World Golf Village, FL",
        "Bakersville, FL",
        "Elkton, FL",
        "Hastings, FL",
        "Julington Creek Plantation, FL",
        "Mill Creek, FL",
        "Ponte Verdra Beach, FL",
        "St. Johns, FL",
        "Spuds, FL",
        "Summer Haven, FL",
        "Switzerland, FL",
        "Vermont Heights, FL"
    ],
    "Atlanta, GA": [
        'Brookhaven, GA',
        'Peachtree Corners, GA',
        'Cumberland, GA',
        'Perimeter Center, GA',
        'Gwinnett Place, GA',
        'Sugarloaf, GA',
        'East Cobb, GA',
        'Roswell, GA',
        'Atlanta, GA',
        'South Fulton, GA',
        'Sandy Springs, GA',
        'Roswell, GA',
        'Johns Creek, GA',
        'Alpharetta, GA',
        'Marietta, GA',
        'Stonecrest, GA',
        'Smyrna, GA',
        'Dunwoody, GA',
        'Mableton, GA',
        'Peachtree City, GA',
        'Gainesville, GA',
        'East Point, GA',
        'Tucker, GA',
        'Newnan, GA',
        'Redan, GA',
        'Milton, GA',
        'Douglasville, GA',
        'Kennesaw, GA',
        'Chamblee, GA',
        'Lawrenceville, GA',
        'Duluth, GA',
        'Stockbridge, GA',
        'Carrollton, GA',
        'Woodstock, GA',
        'Griffin, GA',
        'Candler-McAfee, GA',
        'Canton, GA',
        'McDonough, GA',
        'Acworth, GA',
        'Cartersville, GA',
        'Union City, GA',
        'Decatur, GA',
        'North Druid Hills, GA',
        'Sugar Hill, GA',
        'Forest Park, GA',
        'Snellville, GA',
        'North Decatur, GA',
        'Fayetteville, GA',
        'Lithia Springs, GA',
        'Suwanee, GA',
        'Conyers, GA',
        'Belvedere Park, GA',
        'Riverdale, GA',
        'Druid Hills, GA',
        'Winder, GA',
        'Villa Rica, GA',
        'College Park, GA',
        'Powder Springs, GA',
        'Monroe, GA',
        'Covington, GA',
        'Fairburn, GA',
        'Buford, GA',
        'Lilburn, GA',
        'Mountain Park (Gwinnett), GA',
        'Dallas, GA',
        'Loganville, GA',
        'Panthersville, GA',
        'Vinings, GA',
        'Tyrone, GA',
        'Thomaston, GA',
        'Norcross, GA',
        'Doraville, GA',
        'Clarkston, GA',
        'Braselton, GA',
        'Irondale, GA',
        'Centerville, GA',
        'Hampton, GA',
        'Auburn, GA',
        'Barnesville, GA',
        'Austell, GA',
        'Morrow, GA',
        'Lovejoy, GA',
        'Hapeville, GA',
        'Conley, GA',
        'Stone Mountain, GA',
        'Flowery Branch, GA',
        'Cumming, GA',
        'Locust Grove, GA',
        'Jonesboro, GA',
        'Palmetto, GA',
        'Dacula, GA',
        'Bonanza, GA',
        'Avondale Estates, GA',
        'Lakeview Estates, GA',
        'Grayson, GA',
        'Lake City, GA',
        'Chattahoochee Hills, GA',
        'Lithonia, GA',
        'Berkeley Lake, GA'
    ],
    "Tampa, FL": [
        "Tampa, FL"
    ],
    "Pocatello, ID": [
        "Arimo, ID",
        "Chubbuck, ID",
        "Downey, ID",
        "Inkom, ID",
        "Lava Hot Springs, ID",
        "McCammon, ID",
        "Pocatello, ID",
        "Fort Hall, ID",
        "Tyhee, ID",
        "Blackrock, ID",
        "Portneuf, ID",
        "Red Rock Junction, ID",
        "Robin, ID",
        "Swanlake, ID",
        "Virginia, ID",
        "Zenda, ID"
    ],
    "Rockford, IL": [
        "Loves Park, IL",
        "Rockford, IL",
        "South Beloit, IL",
        "Cherry Valley, IL",
        "Durand, IL",
        "Machesney Park, IL",
        "New Milford, IL",
        "Pecatonica, IL",
        "Rockton, IL",
        "Roscoe, IL",
        "Winnebago, IL",
        "Alworth, IL",
        "Argyle, IL",
        "Harlem, IL",
        "Harrison, IL",
        "Kishwaukee, IL",
        "Latham Park, IL",
        "Seward, IL",
        "Shirland, IL",
        "Wempletown, IL",
        "Westfield Corners, IL",
        "Burritt, IL",
        "Harrison, IL",
        "Laona, IL",
        "Owen, IL",
        "Camp Grant, IL"
    ],
    "Springfield, KY": [
        "Bear Wallow, KY",
        "Brush Grove, KY",
        "Fredericktown, KY",
        "Mackville, KY",
        "Manton, KY",
        "Pleasant Grove, KY",
        "Saint Catharine, KY",
        "Springfield, KY",
        "Thompsonville, KY",
        "Willisburg, KY",
        "Mooresville, KY",
        "Maud, KY"
    ],
    "Minneapolis, MN": [
        'Bloomington, MN',
        'Brooklyn Center, MN',
        'Brooklyn Park, MN',
        'Champlin, MN',
        'Chanhassen, MN',
        'Corcoran, MN',
        'Crystal, MN',
        'Dayton, MN',
        'Deephaven, MN',
        'Eden Prairie, MN',
        'Edina, MN',
        'Excelsior, MN',
        'Golden Valley, MN',
        'Greenfield, MN',
        'Greenwood, MN',
        'Hanover, MN',
        'Hopkins, MN',
        'Independence, MN',
        'Long Lake, MN',
        'Loretto, MN',
        'Maple Grove, MN',
        'Maple Plain, MN',
        'Medicine Lake, MN',
        'Medina, MN',
        'Minneapolis, MN',
        'Minnetonka, MN',
        'Minnetonka Beach, MN',
        'Minnetrista, MN',
        'Mound, MN',
        'New Hope, MN',
        'Orono, MN',
        'Osseo, MN',
        'Plymouth, MN',
        'Richfield, MN',
        'Robbinsdale, MN',
        'Rockford, MN',
        'Rogers, MN',
        'Shorewood, MN',
        'Spring Park, MN',
        'St. Anthony, MN',
        'St. Bonifacius, MN',
        'St. Louis Park, MN',
        'Tonka Bay, MN',
        'Wayzata, MN',
        'Woodland, MN'
    ],
    "Kansas City, MO": [
        "Blue Springs, MO",
        "Buckner, MO",
        "Grain Valley, MO",
        "Grandview, MO",
        "Greenwood, MO",
        "Independence, MO",
        "Kansas City, MO",
        "Lake Lotawana, MO",
        "Lake Tapawingo, MO",
        "Lee's Summit, MO",
        "Levasy, MO",
        "Lone Jack, MO",
        "Oak Grove, MO",
        "Pleasant Hill, MO",
        "Raytown, MO",
        "Sugar Creek, MO",
        "River Bend, MO",
        "Sibley, MO",
        "Unity Village, MO",
        "Blue Summit, MO",
        "Tarsney Lakes, MO",
        "Atherton, MO",
        "Blue Mills, MO",
        "Blue Summit, MO",
        "Cockrell, MO",
        "Courtney, MO",
        "Hiler, MO",
        "Hicks County, MO",
        "Oakland, MO",
        "Pink Hill, MO",
        "Sni Mills, MO",
        "Tarsney, MO",
        "Camden Point, MO",
        "Dearborn, MO",
        "Edgerton, MO",
        "Houston Lake, MO",
        "Lake Waukomis, MO",
        "Northmoor, MO",
        "Parkville, MO",
        "Platte City, MO",
        "Platte Woods, MO",
        "Riverside, MO",
        "Smithville, MO",
        "Tracy, MO",
        "Weatherby Lake, MO",
        "Weston, MO",
        "Farley, MO",
        "Ferrelview, MO",
        "Iatan, MO",
        "Ridgely, MO",
        "Carroll, MO,",
        "Flair, MO",
        "Fox, MO",
        "Green, MO",
        "Kickapoo, MO",
        "Lee, MO",
        "Marshall, MO",
        "May, MO",
        "Pawnee, MO",
        "Pettis, MO",
        "Preston, MO",
        "Sioux, MO",
        "Waldron, MO",
        "Weston, MO",
        "Beverly, MO",
        "Dye, MO",
        "East Leavenworth, MO",
        "Edgerton Junction, MO",
        "Hoover, MO",
        "Kerrville, MO",
        "New Market, MO",
        "Stillings, MO",
        "Stubbs, MO",
        "Waldron, MO",
        "West Platte, MO",
        "Woodruff, MO",
        "Avondale, MO",
        "Birmingham, MO",
        "Claycomo, MO",
        "Excelsior Estates, MO",
        "Excelsior Springs, MO",
        "Gladstone, MO",
        "Glenaire, MO",
        "Holt, MO",
        "Kearney, MO",
        "Lawson, MO",
        "Liberty, MO",
        "Missouri County, MO",
        "Mosby, MO",
        "North Kansas City, MO",
        "Oaks, MO",
        "Oakview, MO",
        "Oakwood, MO",
        "Oakwood Park, MO",
        "Pleasant Valley, MO",
        "Prathersville, MO",
        "Randolph, MO",
        "Smithville, MO",
        "Sugar Creek, MO",
        "Arley, MO",
        "Chandler, MO",
        "Claysville, MO",
        "Clevenger, MO",
        "Ectonville, MO",
        "Miltondale, MO",
        "Roosterville, MO",
        "Stockdale, MO",
        "Winner, MO",
        "Archie, MO",
        "Belton, MO",
        "Cleveland, MO",
        "Creighton, MO",
        "Drexel, MO",
        "East Lynne, MO",
        "Freeman, MO",
        "Garden City, MO",
        "Harrisonville, MO",
        "Lake Annette, MO",
        "Lake Winnebago, MO",
        "Peculiar, MO",
        "Pleasant Hill, MO",
        "Raymore, MO",
        "Strasburg, MO",
        "Baldwin Park, MO",
        "Gunn City, MO",
        "Riverview Estates, MO",
        "West Line, MO",
        "Lock Lloyd, MO",
        "Martin City, MO",
        "Austin, MO",
        "Coleman, MO",
        "Daugherty, MO",
        "Dayton, MO",
        "Everett, MO",
        "Jaudon, MO",
        "Lisle, MO",
        "Lone Tree, MO",
        "Main City, MO",
        "Wingate, MO"
    ],
    "Charlotte, NC": [
        "Charlotte, NC",
        "Cornelius, NC",
        "Davidson, NC",
        "Huntersville, NC",
        "Matthews, NC",
        "Mint Hill, NC",
        "Pineville, NC",
        "Stallings, NC",
        "Weddington, NC",
        "Caldwell, NC",
        "Hopewell, NC",
        "Mountain Island, NC",
        "Newell, NC",
        "Prosperity Village Area, NC",
        "Sterling, NC",
        "Berryhill, NC",
        "Charlotte, NC",
        "Clear Creek, NC",
        "Crab Creek, NC",
        "Crab Orchard, NC",
        "Deweese, NC",
        "Huntersville, NC",
        "Lemley, NC",
        "Long Creek, NC",
        "Mallard Creek, NC",
        "Morning Star, NC",
        "Paw Creek, NC",
        "Pineville, NC",
        "Providence, NC",
        "Sharon, NC",
        "Steele Creek, NC"
    ],
    "Durham, NC": [
        "Durham, NC",
        "Raleigh, NC",
        "Chapel Hill, NC",
        "Morrisville, NC",
        "Carr, NC",
        "Lebanon, NC",
        "Mangum, NC",
        "Oak Grove, NC",
        "Triangle, NC",
        "Gorman, NC",
        "Rougemont, NC",
        "Bahama, NC",
        "Bethesda, NC",
        "Genlee, NC",
        "Lowe's Grove, NC",
        "Nelson, NC",
        "Braggtown, NC"
    ],
    "Wake County, NC": [
        "Durham, NC",
        "Raleigh, NC",
        "Apex, NC",
        "Cary, NC",
        "Fuquay-Varina, NC",
        "Garner, NC",
        "Holly Springs, NC",
        "Knightdale, NC",
        "Morrisville, NC",
        "Rolesville, NC",
        "Wake Forest, NC",
        "Wendell, NC",
        "Zebulon, NC",
        "Bartons Creek, NC",
        "Buckhorn, NC",
        "Cedar Fork, NC",
        "House Creek, NC",
        "Leesville, NC",
        "Little River, NC",
        "Marks Creek, NC",
        "Meredith, NC",
        "Middle Creek, NC",
        "Neuse, NC",
        "New Light, NC",
        "Panther Branch, NC",
        "St. Mary's, NC",
        "St. Matthew's, NC",
        "Swift Creek, NC",
        "White Oak, NC",
        "Asbury, NC",
        "Auburn, NC",
        "Banks, NC",
        "Barham, NC",
        "Bayleaf, NC",
        "Bonsai, NC",
        "Carpenter, NC",
        "Clegg, NC",
        "Eagle Rock, NC",
        "Falls, NC",
        "Feltonville, NC",
        "Five Points, NC",
        "Forestville, NC",
        "Fowlers Crossroads, NC",
        "Friendship, NC",
        "Green Level, NC",
        "Holland, NC",
        "Hollemans Crossroads, NC",
        "Hopkins, NC",
        "Kennebec, NC",
        "Lassiter, NC",
        "Leesville, NC",
        "Lizard Lick, NC",
        "Macks Village, NC",
        "McCullers, NC",
        "McCullers Crossroads, NC",
        "Medfield, NC",
        "Mount Pleasant, NC",
        "Neuse, NC",
        "New Hill, NC",
        "New Hope, NC",
        "New Light, NC",
        "Purnell, NC",
        "Riley Hill, NC",
        "Sandy Plain, NC",
        "Shotwell, NC",
        "Six Forks, NC",
        "Stony Hill, NC",
        "Swift Creek, NC",
        "Wake Crossroads, NC",
        "Walkers Crossroad, NC",
        "Westover, NC",
        "Wilborn, NC",
        "Williams Crossroads, NC",
        "Willow Spring, NC",
        "Wyatt, NC"
    ],
    "Winston-Salem, NC": [
        "Winston-Salem, NC",
        "High Point, NC",
        "King, NC",
        "Bethania, NC",
        "Kernersville, NC",
        "Lewisville, NC",
        "Rural Hall, NC",
        "Walkertown, NC",
        "Clemmons, NC",
        "Tobaccoville, NC",
        "Germantown, NC",
        "Abbots Creek, NC",
        "Belews Creek, NC",
        "Bethania, NC",
        "Broadbay, NC",
        "Clemmonsville, NC",
        "Kernersville, NC",
        "Lewisville, NC",
        "Middle Fork I, NC",
        "Middle Fork II Township, NC",
        "Old Richmond, NC",
        "Old Town, NC",
        "Salem Chapel, NC",
        "South Fork, NC",
        "Vienna, NC",
        "Winston, NC",
        "Bethabara, NC",
        "Donnaha, NC",
        "Dozier, NC",
        "Pfafftown, NC",
        "Seward, NC",
        "Stanleyville, NC",
        "Union Cross, NC",
    ],
    "Lincoln, NE": [
        "Lincoln, NE",
        "Hickman, NE",
        "Milford, NE",
        "Seward, NE",
        "Waverly, NE",
        "Bennet, NE",
        "Firth, NE",
        "Utica, NE",
        "Walton, NE",
        "Hallam, NE",
        "Malcolm, NE",
        "Panama, NE",
        "Staplehurst, NE",
        "Bee, NE",
        "Cordova, NE",
        "Davey, NE",
        "Denton, NE",
        "Garland, NE",
        "Goehner, NE",
        "Pleasant Dale, NE",
        "Raymond, NE",
        "Roca, NE",
        "Sprague, NE"
    ],
    "Omaha, NE": [
        "Bennington, NE",
        "Omaha, NE",
        "East Omaha, NE",
        "North Omaha, NE",
        "South Omaha, NE",
        "West Omaha, NE",
        "Ralston, NE",
        "Valley, NE",
        "Boys Town, NE",
        "Waterloo, NE",
        "King Lake, NE",
        "Venice, NE",
        "Briggs, NE",
        "Debolt, NE",
        "Elk City, NE",
        "Irvington, NE",
        "Lane, NE"
    ],
    "Burlington County, NJ": [
        "Bass River Township, NJ",
        "Beverly, NJ",
        "Bordentown, NJ",
        "Bordentown Township, NJ",
        "Burlington, NJ",
        "Burlington Township, NJ",
        "Chesterfield, NJ",
        "Cinnaminson Township, NJ",
        "Delanco Township, NJ",
        "Delran Township, NJ",
        "Easthampton Township, NJ",
        "Edgewater Park, NJ",
        "Evesham Township, NJ",
        "Fieldsboro, NJ",
        "Florence Township, NJ",
        "Hainsport Township, NJ",
        "Lumberton Township, NJ",
        "Mansfield Township, NJ",
        "Maple Shade Township, NJ",
        "Medford, NJ",
        "Medford Lakes, NJ",
        "Moorestown Township, NJ",
        "Mount Holly, NJ",
        "Mount Laurel, NJ",
        "New Hanover Township, NJ",
        "North Hanover Township, NJ",
        "Palmyra, NJ",
        "Pemberton, NJ",
        "Pemberton Township, NJ",
        "Riverside Township, NJ",
        "Riverton, NJ",
        "Shamong Township, NJ",
        "Southampton Township, NJ",
        "Springfield Township, NJ",
        "Tabernacle Township, NJ",
        "Washington Township, NJ",
        "Westampton Township, NJ",
        "Willingboro Township, NJ",
        "Woodland Township, NJ",
        "Wrightstown, NJ"
    ],
    "Albuquerque, NM": [
        "Albuquerque, NM",
        "Belen, NM",
        "Moriarty, NM",
        "Rio Communities, NM",
        "Rio Rancho, NM",
        "Bernalillo, NM",
        "Estancia, NM",
        "Mountainair, NM",
        "Peralta, NM",
        "Bosque Farms, NM",
        "Corrales, NM",
        "Cuba, NM",
        "Encino, NM",
        "Jemez Springs, NM",
        "Los Lunas, NM",
        "Los Ranchos de Albuquerque, NM",
        "San Ysidro, NM",
        "Tijeras, NM",
        "Willard, NM",
        "Algodones, NM",
        "Carnuel, NM",
        "Casa Colorada, NM",
        "Cedar Crest, NM",
        "Chilili, NM",
        "Cochiti, NM",
        "El Cerro-Monterey Park, NM",
        "Isleta Village Proper, NM",
        "Jarales, NM",
        "Jemez Pueblo, NM",
        "La Jara, NM",
        "Los Chavez, NM",
        "Los Trujillos-Gabaldon, NM",
        "Manzano, NM",
        "Meadow Lake, NM",
        "North Valley, NM",
        "Paradise Hills, NM",
        "Pena Blanca, NM",
        "Placitas, NM",
        "Ponderosa, NM",
        "Pueblo of Sandia Village, NM",
        "Regina, NM",
        "Rio Communities North, NM",
        "Rio Communities, NM",
        "San Felipe Pueblo, NM",
        "Santa Ana Pueblo, NM",
        "Santo Domingo Pueblo, NM",
        "South Valley, NM",
        "Tajique, NM",
        "Tome Adelino, NM",
        "Torreon, NM",
        "Valencia, NM",
        "Zia Pueblo, NM",
        "Edgewood, NM",
        "Barton, NM",
        "Carnuel, NM",
        "Cedar Crest, NM",
        "Cedro, NM",
        "Chilili, NM",
        "Edith Endave, NM",
        "Isleta, NM",
        "Kirtland AFB, NM",
        "Manzano Springs, NM",
        "North Valley, NM",
        "Paa-Ko, NM",
        "Pajarito Mesa, NM",
        "Paradise Hills, NM",
        "Ponderosa Pine, NM",
        "San Antonito, NM",
        "Sandia Heights, NM",
        "Sandia Knolls, NM",
        "Sandia Park, NM",
        "Sedillo, NM",
        "South Valley, NM",
        "Alameda, NM",
        "Isleta Pueblo, NM",
        "Laguna Pueblo, NM",
        "Sandia Pueblo, NM",
        "Zuzax, NM"
    ],
    "Las Vegas, NV": [
        "Las Vegas, NV",
        "Boulder City, NV",
        "Enterprise, NV",
        "Henderson, NV",
        "Lone Mountain, NV",
        "North Las Vegas, NV",
        "Paradise, NV",
        "Spring Valley, NV",
        "Summerlin South, NV",
        "Sunrise Manor, NV",
        "Whitney, NV",
        "Winchester, NV",
        "Mesquite, NV",
        "North Las Vegas, NV",
        "Blue Diamond, NV",
        "Bunkerville, NV",
        "Cal-Nev-Ari, NV",
        "Goodsprings, NV",
        "Indian Springs, NV",
        "Laughlin, NV",
        "Moapa Town, NV",
        "Moapa Valley, NV",
        "Mount Charleston, NV",
        "Nelson, NV",
        "Sandy Valley, NV",
        "Searchlight, NV",
        "Spring Valley, NV",
        "Creech AFB, NV",
        "Nellis AFB, NV",
        "Arden, NV",
        "Cactus Springs, NV",
        "Cottonwood Cove, NV",
        "Coyote Springs, NV",
        "Crystal, NV",
        "Fort Mojave Indian Reservation, NV",
        "Glendale, NV",
        "Jean, NV",
        "Logandale, NV",
        "Las Vages Indian Colony, NV",
        "Moapa River Indian Reservation, NV",
        "Mountain Springs, NV",
        "Overton, NV",
        "Primm, NV",
        "Roach, NV",
        "Sloan, NV",
        "Summerlin, NV",
        "Sutor, NV",
        "Vegas Creek, NV"
    ],
    "Reno, NV": [
        "Reno, NV",
        "Sparks, NV",
        "Cold Springs, NV",
        "Crystal Bay, NV",
        "Empire, NV",
        "Gerlach, NV",
        "Golden Valley, NV",
        "Incline Village, NV",
        "Lemmon Valley, NV",
        "Mogul, NV",
        "Nixon, NV",
        "Spanish Springs, NV",
        "Sun Valley, NV",
        "Sutcliffe, NV",
        "Verdi, NV",
        "Virginia City, NV",
        "Wadsworth, NV",
        "Gold Hill, NV",
        "New Washoe City, NV",
        "Pleasant Valley, NV",
        "Poeville, NV",
        "Pryamid, NV",
        "Vya, NV"
        "Reno, NV",
        "Sparks, NV",
        "Cold Springs, NV",
        "Crystal Bay, NV",
        "Empire, NV",
        "Gerlach, NV",
        "Golden Valley, NV",
        "Incline Village, NV",
        "Lemmon Valley, NV",
        "Mogul, NV",
        "Nixon, NV",
        "Spanish Springs, NV",
        "Sun Valley, NV",
        "Sutcliffe, NV",
        "Verdi, NV",
        "Wadsworth, NV",
        "Washoe Valley, NV",
        "Anderson, NV",
        "Antelope Valley, NV",
        "Arrowcreek, NV",
        "Bartley Ranch, NV",
        "Beulah, NV",
        "Border Town, NV",
        "Bronco, NV",
        "Buffalo Ranch, NV",
        "Caughlin Ranch, NV",
        "Copperfield, NV",
        "Damonte Ranch, NV",
        "Deep Hole, NV",
        "Diessner, NV",
        "Dodge, NV",
        "Flanigan, NV",
        "Franktown, NV",
        "Galena, NV",
        "Glendale, NV",
        "Grand View Terrace, NV",
        "Heinz, NV",
        "Hidden Valley, NV",
        "Hot Springs, NV",
        "Huffaker, NV",
        "Jumbo, NV",
        "Lawton, NV",
        "Mayberry-Highland Park, NV",
        "McCarran, NV",
        "Mira Loma, NV",
        "Montrêux, NV",
        "Mustang, NV",
        "New Washoe City, NV",
        "North Valleys, NV",
        "Northeast Reno, NV",
        "Northwest Reno, NV",
        "Olinghouse, NV",
        "Palomino Valley, NV",
        "Panther Valley, NV",
        "Phil, NV",
        "Poeville, NV",
        "Pleasant Valley, NV",
        "Pyramid, NV",
        "Raleigh Heights, NV",
        "Rancho Haven, NV",
        "Red Hawk, NV",
        "Red Rock, NV",
        "Reederville, NV",
        "Saddlehorn, NV",
        "Sand Pass, NV",
        "Sano, NV",
        "Steamboat Springs, NV",
        "Upper Pyramid, NV",
        "Virginia Foothills, NV",
        "Vya, NV",
        "Washoe City, NV",
        "Washoe Summit, NV",
        "Wedekind, NV",
        "Winnemucca Ranch, NV"
    ],
    "Long Island": [
        'Brooklyn, NY', 
        'Queens, NY', 
        'Nassau County, NY', 
        'Glen Cove, NY', 
        'Long Beach, NY', 
        'Hempstead, NY',  
        'Atlantic Beach, NY', 
        'Bellerose, NY', 
        'Cedarhurst, NY', 
        'East Rockaway, NY', 
        'Freeport, NY', 
        'Garden City, NY', 
        'Hempstead, NY', 
        'Hewlett Bay Park, NY', 
        'Hewlett Harbor, NY', 
        'Hewlett Neck, NY', 
        'Island Park, NY', 
        'Lawrence, NY', 
        'Lynbrook, NY', 
        'Malverne, NY', 
        'Rockville Centre, NY', 
        'South Floral Park, NY', 
        'Stewart Manor, NY', 
        'Valley Stream, NY', 
        'Woodsburgh, NY', 
        'Baldwin, NY', 
        'Baldwin Harbor, NY', 
        'Barnum Island, NY', 
        'Bay Park, NY', 
        'Bellerose Terrace, NY', 
        'Bellmore, NY', 
        'East Atlantic Beach, NY', 
        'East Garden City, NY', 
        'East Meadow, NY', 
        'Elmont, NY', 
        'Franklin Square, NY', 
        'Garden City South, NY', 
        'Harbor Isle, NY', 
        'Hewlett, NY', 
        'Inwood, NY', 
        'Lakeview, NY', 
        'Levittown, NY', 
        'Lido Beach, NY', 
        'Malverne Park Oaks, NY', 
        'Merrick, NY', 
        'North Bellmore, NY', 
        'North Lynbrook, NY', 
        'North Merrick, NY', 
        'North Valley Stream, NY', 
        'North Wantagh, NY', 
        'North Woodmere, NY', 
        'Oceanside, NY', 
        'Point Lookout, NY', 
        'Roosevelt, NY', 
        'Salisbury, NY', 
        'Seaford, NY', 
        'South Hempstead, NY', 
        'South Valley Stream, NY', 
        'Uniondale, NY', 
        'Wantagh, NY', 
        'West Hempstead, NY', 
        'Woodmere, NY', 
        'Floral Park, NY', 
        'Garden City, NY', 
        'Mineola, NY', 
        'New Hyde Park, NY', 
        'North Hempstead, NY',  
        'Baxter Estates, NY', 
        'East Williston, NY', 
        'Flower Hill, NY', 
        'Great Neck, NY', 
        'Great Neck Estates, NY', 
        'Great Neck Plaza, NY', 
        'Kensington, NY', 
        'Kings Point, NY', 
        'Lake Success, NY', 
        'Manorhaven, NY', 
        'Munsey Park, NY', 
        'North Hills, NY', 
        'Plandome, NY', 
        'Plandome Heights, NY', 
        'Plandome Manor, NY', 
        'Port Washington North, NY', 
        'Roslyn, NY', 
        'Roslyn Estates, NY', 
        'Russell Gardens, NY', 
        'Saddle Rock, NY', 
        'Sands Point, NY', 
        'Thomaston, NY', 
        'Westbury, NY', 
        'Williston Park, NY', 
        'Albertson, NY', 
        'Carle Place, NY', 
        'Garden City Park, NY', 
        'Glenwood Landing, NY', 
        'Great Neck Gardens, NY', 
        'Greenvale, NY', 
        'Harbor Hills, NY', 
        'Herricks, NY', 
        'Manhasset, NY', 
        'Manhasset Hills, NY', 
        'New Cassel, NY', 
        'North New Hyde Park, NY', 
        'Port Washington, NY', 
        'Roslyn Heights, NY', 
        'Saddle Rock Estates, NY', 
        'Searingtown, NY',
        'University Gardens, NY', 
        'East Hills, NY', 
        'Old Westbury, NY', 
        'Roslyn Harbor, NY', 
        'Oyster Bay, New York, NY',
        'Bayville, NY', 
        'Brookville, NY', 
        'Centre Island, NY', 
        'Cove Neck, NY', 
        'Farmingdale, NY', 
        'Lattingtown, NY', 
        'Laurel Hollow, NY', 
        'Massapequa Park, NY', 
        'Matinecock, NY', 
        'Mill Neck, NY', 
        'Muttontown, NY', 
        'Old Brookville, NY', 
        'Oyster Bay Cove, NY', 
        'Sea Cliff, NY', 
        'Upper Brookville, NY', 
        'Bethpage, NY', 
        'East Massapequa, NY', 
        'East Norwich, NY', 
        'Glen Head, NY', 
        'Glenwood Landing, NY', 
        'Greenvale, NY', 
        'Hicksville, NY', 
        'Jericho, NY', 
        'Locust Valley, NY', 
        'Massapequa, NY', 
        'North Massapequa, NY', 
        'Old Bethpage, NY', 
        'Oyster Bay, NY', 
        'Plainedge, NY', 
        'Plainview, NY', 
        'South Farmingdale, NY', 
        'Syosset, NY', 
        'Woodbury, NY', 
        'East Hills, NY', 
        'Old Westbury, NY', 
        'Roslyn Harbor, NY',
        'Suffolk County, NY',  
        'Babylon, NY', 
        'Amityville, NY', 
        'Babylon, NY', 
        'Lindenhurst, NY', 
        'Copiague, NY', 
        'Deer Park, NY', 
        'East Farmingdale, NY', 
        'Gilgo, NY', 
        'North Amityville, NY', 
        'North Babylon, NY', 
        'North Lindenhurst, NY', 
        'Oak Beach, NY', 
        'Captree, NY', 
        'West Babylon, NY', 
        'Wheatley Heights, NY', 
        'Wyandanch, NY', 
        'Copiague Harbor, NY',  
        'Huntington, New York, NY', 
        'Asharoken, NY', 
        'Huntington Bay, NY', 
        'Lloyd Harbor, NY', 
        'Northport, NY', 
        'Centerport, NY', 
        'Cold Spring Harbor, NY', 
        'Dix Hills, NY', 
        'East Northport, NY', 
        'Eatons Neck, NY', 
        'Elwood, NY', 
        'Greenlawn, NY', 
        'Halesite, NY', 
        'Huntington, NY', 
        'Huntington Station, NY', 
        'Melville, NY', 
        'South Huntington, NY', 
        'Vernon Valley, NY',
        'West Hills, NY', 
        'Wincoma, NY', 
        'Commack, NY', 
        'Fort Salonga, NY',  
        'Islip, NY', 
        'Brightwaters, NY', 
        'Islandia, NY', 
        'Ocean Beach, NY', 
        'Saltaire, NY', 
        'Bay Shore, NY', 
        'Bayport, NY', 
        'Baywood, NY', 
        'Bohemia, NY', 
        'Brentwood, NY', 
        'Central Islip, NY', 
        'East Islip, NY', 
        'Great River, NY', 
        'Islip, NY', 
        'Islip Terrace, NY', 
        'North Bay Shore, NY', 
        'North Great River, NY', 
        'Oakdale, NY', 
        'Ronkonkoma, NY', 
        'Sayville, NY', 
        'West Bay Shore, NY', 
        'West Islip, NY', 
        'West Sayville, NY', 
        'Holbrook, NY', 
        'Holtsville, NY', 
        'Hauppauge, NY',
        'Smithtown, NY', 
        'Head of the Harbor, NY', 
        'Nissequogue, NY', 
        'Village of the Branch, NY', 
        'Kings Park, NY', 
        'Nesconset, NY', 
        'Smithtown, NY', 
        'St. James, NY', 
        'Lake Ronkonkoma, NY', 
        'Commack, NY', 
        'Fort Salonga, NY', 
        'Hauppauge, NY', 
        'Brookhaven, NY', 
        'Belle Terre, NY', 
        'Bellport, NY', 
        'Lake Grove, NY', 
        'Old Field, NY', 
        'Patchogue, NY', 
        'Poquott, NY', 
        'Port Jefferson, NY', 
        'Shoreham, NY', 
        'Blue Point, NY', 
        'Brookhaven, NY', 
        'Canaan Lake, NY', 
        'Center Moriches, NY', 
        'Centereach, NY', 
        'Cherry Grove, NY', 
        'Coram, NY', 
        'Crystal Brook, NY', 
        'Cupsogue Beach, NY', 
        'Davis Park, NY', 
        'East Moriches, NY', 
        'East Patchogue, NY', 
        'East Setauket, NY', 
        'East Shoreham, NY', 
        'East Yaphank, NY', 
        'Farmingville, NY', 
        'Fire Island Pines, NY', 
        'Gordon Heights, NY', 
        'Hagerman, NY', 
        'Manor Park, NY', 
        'Manorville, NY', 
        'Mastic, NY', 
        'Mastic Acres, NY', 
        'Mastic Beach, NY', 
        'Medford, NY', 
        'Middle Island, NY', 
        'Miller Place, NY', 
        'Moriches, NY', 
        'Mount Sinai, NY', 
        'North Bellport, NY', 
        'North Patchogue, NY', 
        'Ocean Bay Park, NY', 
        'Old Mastic, NY', 
        'Point of Woods, NY', 
        'Port Jefferson Station, NY', 
        'Ridge, NY', 
        'Rocky Point, NY', 
        'Selden, NY', 
        'Setauket, NY', 
        'Shirley, NY', 
        'South Haven, NY', 
        'Sound Beach, NY', 
        'Stony Brook, NY', 
        'Strongs Neck, NY', 
        'Terryville, NY', 
        'Upton, NY', 
        'Water Island, NY', 
        'West Manor, NY', 
        'Yaphank, NY', 
        'Holbrook, NY', 
        'Holtsville, NY', 
        'Ronkonkoma, NY', 
        'Calverton, NY', 
        'Lake Ronkonkoma, NY', 
        'Eastport, NY', 
        'Lake Grove, NY', 
        'Southampton, NY', 
        'North Haven, NY', 
        'Quogue, NY', 
        'Sagaponack, NY', 
        'Southampton, NY', 
        'Westhampton Beach, NY', 
        'West Hampton Dunes, NY', 
        'Sag Harbor, NY', 
        'Bridgehampton, NY', 
        'East Quogue, NY', 
        'Flanders, NY', 
        'Hampton Bays, NY', 
        'Northampton, NY', 
        'North Sea, NY', 
        'Noyack, NY', 
        'Noyac, NY',
        'Quiogue, NY', 
        'Remsenburg, NY', 
        'Riverside, NY', 
        'Shinnecock Hills, NY', 
        'Speonk, NY', 
        'Tuckahoe, NY', 
        'Water Mill, NY', 
        'Watermill, NY',
        'Westhampton, NY', 
        'Eastport, NY', 
        'Riverhead, NY', 
        'Aquebogue, NY', 
        'Baiting Hollow, NY', 
        'Jamesport, NY', 
        'Northville, NY', 
        'Riverhead, NY', 
        'Wading River, NY', 
        'Calverton, NY', 
        'East Hampton, NY', 
        'East Hampton, NY', 
        'Sag Harbor, NY', 
        'Amagansett, NY', 
        'East Hampton North, NY', 
        'Montauk, NY', 
        'Napeague, NY', 
        'Northwest Harbor, NY', 
        'Springs, NY', 
        'Wainscott, NY',
        'Shelter Island, NY', 
        'Dering Harbor, NY', 
        'Shelter Island, NY', 
        'Shelter Island Heights, NY', 
        'Southold, NY', 
        'Greenport, NY', 
        'Cutchogue, NY', 
        'East Marion, NY', 
        'Fishers Island, NY', 
        'Greenport West, NY', 
        'Laurel, NY', 
        'Mattituck, NY', 
        'Orient, NY', 
        'New Suffolk, NY', 
        'Peconic, NY', 
        'Southold, NY', 
        'Fire Island, NY', 
        'Ocean Beach, NY', 
        'Saltaire, NY', 
        'Cherry Grove, NY', 
        'Fire Island Pines, NY', 
        'Davis Park, NY', 
        'Dunewood, NY', 
        'Fair Harbor, NY', 
        'Kismet, NY', 
        'Lonelyville, NY', 
        "Point o' Woods, NY", 
        'Water Island, NY', 
        'Atlantique, NY', 
        'Bayberry Dunes, NY', 
        'Corneille Estates, NY', 
        'Long Cove, NY', 
        'Ocean Bay Park, NY', 
        'Robbins Rest, NY', 
        'Seaview, NY', 
        'Watch Hill, NY', 
        'West Fire Island, NY'
    ],
    "Akron, OH": [],
    "Cincinnati, OH": [],
    "Mount Vernon, OH": [],
    "Bucks County, PA": [],
    "Centre County, PA": [],
    "Chester County, PA": [],
    "Delaware County, PA": [],
    "Montgomery County, PA": [],
    "Philadephia County, PA": [],
    "Pittsburgh, PA": [
        "Clairton, PA",
        "Duquesne, PA",
        "McKeesport, PA",
        "Pittsburgh, PA",
        "Aspinwall, PA",
        "Avalon, PA",
        "Baldwin, PA",
        "Bell Acres, PA",
        "Bellevue, PA",
        "Ben Avon, PA",
        "Ben Avon Heights, PA",
        "Bethel Park, PA",
        "Blawnox, PA",
        "Brackenridge, PA",
        "Braddock, PA",
        "Braddock Hills, PA",
        "Bradford Woods, PA",
        "Brentwood, PA",
        "Bridgeville, PA",
        "Carnegie, PA",
        "Castle Shannon, PA",
        "Chalfant, PA",
        "Cheswick, PA",
        "Churchhill, PA",
        "Coraopolis, PA",
        "Crafton, PA",
        "Dormont, PA",
        "Dravosburg, PA",
        "East McKeesport, PA",
        "East Pittsburgh, PA",
        "Edgewood, PA",
        "Edgeworth, PA",
        "Elizabeth, PA",
        "Emsworth, PA",
        "Etna, PA",
        "Forest Hills, PA",
        "Fox Chapel, PA",
        "Franklin Park, PA",
        "Glassport, PA",
        "Glen Osborne, PA",
        "Glenfield, PA",
        "Green Tree, PA",
        "Haysville, PA",
        "Heidelberg, PA",
        "Homestead, PA",
        "Ingram, PA",
        "Jefferson Hills, PA",
        "Leetsdale, PA",
        "Liberty, PA",
        "Lincoln, PA",
        "McDonald, PA",
        "McKees Rocks, PA",
        "Millvale, PA",
        "Monroeville, PA",
        "Mount Oliver, PA",
        "Munhall, PA",
        "North Braddock, PA",
        "Oakdale, PA",
        "Oakmont, PA",
        "Pennsbury, PA",
        "Pitcairn, PA",
        "Pleasant Hills, PA",
        "Plum, PA",
        "Port Vue, PA",
        "Rankin, PA",
        "Rosslyn Farms, PA",
        "Sewickley, PA",
        "Sewickley Heights, PA",
        "Sewickley Hills, PA",
        "Sharpsburg, PA",
        "Springdale, PA",
        "Swissvale, PA",
        "Tarentum, PA",
        "Thornburg, PA",
        "Trafford, PA",
        "Turtle Creek, PA",
        "Verona, PA",
        "Versailles, PA",
        "Wall, PA",
        "West Elizabeth, PA",
        "West Homestead, PA",
        "West Mifflin, PA",
        "West View, PA",
        "Whitaker, PA",
        "White Oak, PA",
        "Whitehall, PA",
        "Wilkinsburg, PA",
        "Wilmerding, PA",
        "Aleppo, PA",
        "Baldwin, PA",
        "Collier, PA",
        "Crescent, PA",
        "East Deer, PA",
        "Elizabeth, PA",
        "Fawn, PA",
        "Findlay, PA",
        "Forward, PA",
        "Frazer, PA",
        "Hampton, PA",
        "Harmar, PA",
        "Harrison, PA",
        "Indiana, PA",
        "Kennedy, PA",
        "Kilbuck, PA",
        "Leet, PA",
        "Marshall, PA",
        "McCandless, PA",
        "Moon, PA",
        "Mt. Lebanon, PA",
        "Neville, PA",
        "North Fayette, PA",
        "North Versailles, PA",
        "O'Hara, PA",
        "Ohio, PA",
        "Penn Hills, PA",
        "Pine, PA",
        "Reserve, PA",
        "Richland, PA",
        "Robinson, PA",
        "Ross, PA",
        "Scott, PA",
        "Shaler, PA",
        "South Fayette, PA",
        "South Park, PA",
        "South Versailles, PA",
        "Springdale, PA",
        "Stowe, PA",
        "Upper Saint Clair, PA",
        "West Deer, PA",
        "Wilkins, PA"
        "Allison, PA",
        "Bairdford, PA",
        "Bakerstown, PA",
        "Boston, PA",
        "Carnot-Moon, PA",
        "Clinton, PA",
        "Curtisville, PA",
        "Enlow, PA",
        "Gibsonia, PA",
        "Glenshaw, PA",
        "Greenock, PA",
        "Harwick, PA",
        "Imperial, PA",
        "Noblestown, PA",
        "Rennerdale, PA",
        "Russellton, PA",
        "Sturgeon, PA".
        "Acmetonia, PA",
        "Alpsville, PA",
        "Blackridge, PA",
        "Blanchard, PA",
        "Broughton, PA",
        "Bruceton, PA",
        "Buena Vista, PA",
        "Creighton, PA",
        "Cubbage Hill, PA",
        "Cuddy, PA",
        "Dorseyville, PA",
        "Ewingsville, PA",
        "Harmarville, PA",
        "Hickory Heights, PA",
        "Indianola, PA",
        "Ingomar, PA",
        "Karns, PA",
        "Keown Station, PA",
        "Kirwan Heights, PA",
        "Library, PA",
        "McKnight, PA",
        "Moon Run, PA",
        "Mount Vernon, PA",
        "Natrona, PA",
        "Natrona Heights, PA",
        "Nevillewood, PA",
        "Presto, PA",
        "Regent Square, PA",
        "Rural Ridge, PA",
        "Sheraden, PA",
        "Sherman, PA",
        "Treveskyn, PA",
        "Warrendale, PA",
        "Wexford, PA",
        "Wildwood, PA"
    ],
    "York, PA": [],
    "Beaufort County, SC": [],
    "Charleston, SC": [],
    "Sioux Falls, SD": [],
    "Nashville, TN": [],
    "Amarillo, TX": [],
    "Austin, TX": [],
    "Beaumont, TX": [],
    "Dallas, TX": [],
    "El Paso, TX": [],
    "Houston, TX": [],
    "McAllen, TX": [],
    "San Antonio, TX": [],
    "Fairfax, VA": [],
    "Loudon County, VA": [],
    "Appleton, WI": [],
    "Green Bay, WI": [],
    "Milwaukee, WI": []
}
