# used to make changes to large city/town lists more efficient
towns = [
    'Milwaukee', 'edit', 'Racine', 'Waukesha', 'edit', 'Beaver Dam', 'Brookfield', 'Brown Deer', 'Burlington', 'Caledonia', 'Cedarburg', 'Cudahy', 'Delavan', 'Elkhorn', 'Fort Atkinson', 'Franklin', 'Germantown', 'Glendale', 'Grafton', 'Greendale', 'Greenfield', 'Hartford', 'Menomonee Falls', 'Mequon', 'Mount Pleasant', 'Muskego', 'New Berlin', 'Oak Creek', 'Oconomowoc', 'Pewaukee', 'Port Washington', 'Richfield', 'Shorewood', 'South Milwaukee', 'Sussex', 'Watertown', 'Wauwatosa', 'West Allis', 'West Bend', 'Whitefish Bay', 'Whitewater', 'edit', 'Addison', 'Barton', 'Bayside', 'Belgium', 'Big Bend', 'Bohners Lake', 'Browns Lake', 'Brownsville', 'Butler', 'Chenequa', 'Clyman', 'Darien', 'Delafield (city)', 'Delafield (town)', 'Dousman', 'Dover', 'Eagle', 'Eagle Lake', 'East Troy', 'Elkhorn', 'Elm Grove', 'Elmwood Park', 'Erin', 'Farmington', 'Fox Lake', 'Fox Point', 'Franksville', 'Fredonia', 'Genesee', 'Germantown (town)', 'Hales Corners', 'Hartland', 'Herman', 'Horicon', 'Hustisford', 'Ixonia', 'Iron Ridge', 'Jackson', 'Jefferson', 'Johnson Creek', 'Juneau', 'Kekoskee', 'Kewaskum', 'Lac La Belle', 'Lake Geneva', 'Lake Mills', 'Lannon', 'Leroy', 'Lisbon', 'Lomira', 'Lowell', 'Mayville', 'Merton', 'Mukwonago', 'Nashotah', 'Neosho', 'Newburg', 'North Bay', 'North Prairie', 'Norway', 'Oconomowoc Lake', 'Okauchee Lake', 'Ottawa', 'Palmyra', 'Pewaukee(village)', 'Polk', 'Randolph', 'Raymond', 'Reeseville', 'River Hills', 'Rochester', 'Rubicon', 'Saukville', 'Slinger', 'St. Francis', 'Sturtevant', 'Sullivan', 'Summit', 'Theresa', 'Thiensville', 'Trenton', 'Union Grove', 'Vernon', 'Wales', 'Walworth', 'Waterford', 'Waterloo', 'Waupun', 'Wayne', 'West Milwaukee', 'Williams Bay', 'Wind Lake', 'Wind Point', 'Yorkville', 'edit', 'Allenton', 'Boltonville', 'Cheeseville', 'Colgate', 'Ebenezer', 'Farmersville', 'Fillmore', 'Genesee Depot', 'Herman Center', 'Hubertus', 'Kansasville', 'Kohlsville', 'Lake Church', 'Lakefield', 'Myra', 'Nabob', 'Nenno', 'North Cape', 'Oak Hill', 'Pipersville', 'Pike Lake', 'Rockfield', 'Saint Michaels', 'Saylesville', 'Saylesville', 'Stone Bank', 'Thompson', 'Tichigan', 'Ulao', 'Waubeka', 'Woodland'
]

new_towns = []
for town in towns:
    new_towns.append(town + ", WI")
print(new_towns)
