from constants.states.hawaii import (
    HAWAII_HAWAII_ISLAND,
    HAWAII_MAUI_ISLAND,
    HAWAII_OAHU_ISLAND,
    HAWAII_KAUAI_ISLAND,
    HAWAII_MOLOKAI_ISLAND,
    HAWAII_LANAI_ISLAND,
    # HAWAII_NIIHAU_ISLAND,
    # HAWAII_KAHOOLAWE_ISLAND
)

HAWAII_ISLANDS_AND_CITIES = {
    "Hawai'i, HI": HAWAII_HAWAII_ISLAND,
    "Maui, HI": HAWAII_MAUI_ISLAND,
    "O'ahu, HI": HAWAII_OAHU_ISLAND,
    "Kaua'i, HI": HAWAII_KAUAI_ISLAND,
    "Moloka'i, HI": HAWAII_MOLOKAI_ISLAND,
    "Lāna'i, HI": HAWAII_LANAI_ISLAND,
    # "Ni'ihau, HI": HAWAII_NIIHAU_ISLAND,
    # "Kaho'olawe, HI": HAWAII_KAHOOLAWE_ISLAND
}
