HAWAII_HAWAII_ISLAND = [
    # Districts
    "Puna",
    "South Hilo",
    "North Hilo",
    "Hāmākua",
    "North Kohala",
    "South Kohala",
    "North Kona",
    "South Kona",
    "Kaʻū"
    # Census-designated places
    "Ainaloa",
    "Black Sands",
    "Captain Cook",
    "Discovery Harbour",
    "Eden Roc",
    "Fern Acres",
    "Fern Forest",
    "Halaula",
    "Hawaiian Acres",
    "Hawaiian Beaches",
    "Hawaiian Ocean View",
    "Hawaiian Paradise Park",
    "Hawi",
    "Hilo",
    "Holualoa",
    "Honalo",
    "Honaunau-Napoopoo",
    "Honokaa",
    "Honomu",
    "Kahaluu-Keauhou",
    "Kailua",
    "Kaiminani",
    "Kalaoa",
    "Kalapana",
    "Kaloko",
    "Kamaili",
    "Kapaau",
    "Keaau",
    "Kealakekua",
    "Kukuihaele",
    "Kurtistown",
    "Laupahoehoe",
    "Leilani Estates",
    "Mauna Loa Estates",
    "Mountain View",
    "Naalehu",
    "Nanawale Estates",
    "Orchidlands Estates",
    "Paauilo",
    "Pahala",
    "Pahoa",
    "Papaikou",
    "Paukaa",
    "Pepeekeo",
    "Puako",
    "Royal Hawaiian Estates",
    "Seaview",
    "Tiki Gardens",
    "Volcano",
    "Volcano Golf Course",
    "Waikoloa Beach Resort",
    "Waikoloa Village",
    "Waimea",
    "Wainaku",
    "Waiohinu",
    # Other communities
    "Ahualoa",
    "Ha'ena",
    "Hakalau",
    "Kawaihae",
    "Keauhou",
    "Keokea",
    "Miloli'i",
    "Nīnole"
    "ʻŌʻōkala"
    "Paauhau",
    "Pāpaʻaloa"
]

HAWAII_MAUI_ISLAND = [
    # Census-designated places
    "Haiku-Pauwela",
    "Haliimaile",
    "Hana",
    "Kaanapali",
    "Kahului",
    "Kapalua",
    "Kaunakakai",
    "Keokea",
    "Kihei",
    "Kualapuu",
    "Kula",
    "Lahaina",
    "Lanai City",
    "Launiupoko",
    "Maalaea",
    "Mahinahina",
    "Makawao",
    "Makena",
    "Manele",
    "Maunaloa",
    "Napili-Honokowai",
    "Olowalu",
    "Paia",
    "Pukalani",
    "Ualapue",
    "Waihee-Waiehu",
    "Waikapu",
    "Wailea",
    "Wailuku",
    # Unincorporated communities
    "Haiku",
    "Kaumalapau",
    "Keʻanae",
    "Kīpahulu",
    "Napili",
    "Olinda",
    "Puʻunēnē",
    "Spreckelsville",
    "Waihee",
    "Wailua",
    # Former communities
    "Waikola"
]

HAWAII_OAHU_ISLAND = [
    # Census-designated places
    "ʻĀhuimanu",
    "ʻAiea",
    "East Honolulu",
    "ʻEwa Beach",
    "ʻEwa Gentry",
    "ʻEwa Villages",
    "Hālawa",
    "Haleʻiwa",
    "Hauʻula",
    "Heʻeia",
    "Hickam Housing",
    "Honolulu",
    "Iroquois Point",
    "Kaʻaʻawa",
    "Kahaluʻu",
    "Kahuku",
    "Kailua",
    "Kalaeloa",
    "Kāneʻohe",
    "Kaneohe Station",
    "Marine Corps Base Hawaiʻi",
    "Kapolei",
    "Kawela Bay",
    "Ko Olina",
    "Lāʻie",
    "Māʻili",
    "Mākaha",
    "Mākaha Valley",
    "Makakilo",
    "Maunawili",
    "Mililani Mauka",
    "Mililani Town",
    "Mokulēʻia",
    "Nānākuli",
    "Ocean Pointe",
    "Pearl City",
    "Punaluʻu",
    "Pūpūkea",
    "Royal Kunia",
    "Village Park",
    "Schofield Barracks",
    "Urban Honolulu",
    "Wahiawā",
    "Waiāhole",
    "Waialua",
    "Waiʻanae",
    "Waikāne",
    "Waikele",
    "Waimalu",
    "Waimānalo",
    "Waimānalo Beach",
    "Waipahu",
    "Waipiʻo",
    "Waipiʻo Acres",
    "West Loch Estate",
    "Wheeler Army Airfield",
    "Whitmore Village",
    # Other places
    "ʻĀina Haina",
    "Hawaiʻi Kai",
    "Pauoa"
]

HAWAII_KAUAI_ISLAND = [
    # Census-designated places
    "Anahola",
    "Eleele",
    "Haena",
    "Hanalei",
    "Hanamaulu",
    "Hanapepe",
    "Kalaheo",
    "Kalihiwai",
    "Kapa'a",
    "Kaumakani",
    "Kekaha",
    "Kilauea",
    "Koloa",
    "Lawai",
    "Lihue",
    "Omao",
    "Pakala Village",
    "Poipu",
    "Princeville",
    "Puhi",
    "Wailua",
    "Wailuā Homesteads",
    "Waimea",
    "Wainiha",
    # Other unincorporated places
    "Puuwai",
    "Kealia"
]

HAWAII_MOLOKAI_ISLAND = [
    "Hoʻolehua",
    "Kalaupapa",
    "Kalawao",
    "Kaunakakai",
    "Kualapuʻu",
    "Maunaloa",
    "Ualapu'e",
    "Halawa"
]

HAWAII_LANAI_ISLAND = [
    "Kaa",
    "Paomai",
    "Mahana",
    "Maunalei",
    "Kalulu",
    "Kaunolu",
    "Palawai",
    "Pawili",
    "Kaohai",
    "Kamao",
    "Kealia Aupuni",
    "Kealia Kapu",
    "Kamoku"
]

# HAWAII_NIIHAU_ISLAND = [
#   Not very populated
# ]

# HAWAII_KAHOOLAWE_ISLAND = [
#   Not very populated
# ]
