ILLINOIS_ROCKFORD = [
    "Loves Park",
    "Rockford",
    "South Beloit",
    "Cherry Valley",
    "Durand",
    "Machesney Park",
    "New Milford",
    "Pecatonica",
    "Rockton",
    "Roscoe",
    "Winnebago",
    "Alworth",
    "Argyle",
    "Harlem",
    "Harrison",
    "Kishwaukee",
    "Latham Park",
    "Seward",
    "Shirland",
    "Wempletown",
    "Westfield Corners",
    "Burritt",
    "Harrison",
    "Laona",
    "Owen",
    "Camp Grant"
]
