PENNSYLVANIA_BUCKS_COUNTY = [
    "Bristol",
    "Chalfont",
    "Doylestown",
    "Dublin",
    "Hulmeville",
    "Ivyland",
    "Langhorne",
    "Langhorne Manor",
    "Morrisville",
    "New Britain",
    "New Hope",
    "Newtown",
    "Penndel",
    "Perkasie",
    "Quakertown",
    "Richlandtown",
    "Riegelsville",
    "Sellersville",
    "Silverdale",
    "Telford",
    "Trumbauersville",
    "Tullytown",
    "Yardley",
    "Bedminster",
    "Bensalem",
    "Bridgeton",
    "Bristol",
    "Buckingham",
    "Doylestown",
    "Durham",
    "East Rockhill",
    "Falls",
    "Haycock",
    "Hilltown",
    "Lower Makefield",
    "Lower Southampton",
    "Middletown",
    "Milford",
    "New Britain",
    "Newtown",
    "Nockamixon",
    "Northampton",
    "Plumstead",
    "Richland",
    "Solebury",
    "Springfield",
    "Tinicum",
    "Upper Makefield",
    "Upper Southampton",
    "Warminster",
    "Warrington",
    "Warwick",
    "West Rockhill",
    "Wrightstown",
    "Brittany Farms-The Highlands",
    "Churchville",
    "Cornwells Heights",
    "Croydon",
    "Eddington",
    "Fairless Hills",
    "Feasterville",
    "Levittown",
    "Milford Square",
    "Newtown Grant",
    "Plumsteadville",
    "Richboro",
    "Spinnerstown",
    "Trevose",
    "Village Shires",
    "Warminster Heights",
    "Woodbourne",
    "Woodside",
    "Almont",
    "Andalusia",
    "Applebachsville",
    "Aquetong",
    "Argus",
    "Bedminster",
    "Blooming Glen",
    "Brick Tavern",
    "Bryn Gweled",
    "Buckingham",
    "Bucksville",
    "California",
    "Carversville",
    "Center Bridge",
    "Danboro",
    "Dolington",
    "Durham",
    "Elephant",
    "Erwinna",
    "Eureka",
    "Fallsington",
    "Ferndale",
    "Finland",
    "Forest Grove",
    "Fountainville",
    "Furlong",
    "Gallows Hill",
    "Gardenville",
    "Geryville",
    "Hagersville",
    "Harriman",
    "Harrow",
    "Hartsville",
    "Highland Park",
    "Highton",
    "Hilltop",
    "Hilltown",
    "Hinkletown",
    "Holicong",
    "Holland",
    "Hood",
    "Jamison",
    "Johnsville",
    "Kintnersville",
    "Kulps Corner",
    "Lahaska",
    "Line Lexington",
    "Lodi",
    "Hilltown",
    "Loux Corner",
    "Lumberville",
    "Maple Beach",
    "Mechanicsville",
    "Mount Pleasant",
    "Neshaminy Falls",
    "Newville",
    "Oakford",
    "Ottsville",
    "Oxford Valley",
    "Paletown",
    "Passer",
    "Penns Park",
    "Pineville",
    "Pipersville",
    "Pleasant Valley",
    "Point Pleasant",
    "Revere",
    "Rushland",
    "Shelly",
    "Solebury",
    "Southampton",
    "Springtown",
    "Strawntown",
    "Uhlerstown",
    "Unionville",
    "Upper Black Eddy",
    "Washington Crossing",
    "White Horse",
    "Wrightstown",
    "Wycombe",
    "Zionhill",
    "Hillside Village"
]

PENNSYLVANIA_CENTRE_COUNTY = [
    "Happy Valley",
    "Ferguson Township",
    "State College",
    "Bellefonte",
    "Centre Hall",
    "Howard",
    "Milesburg",
    "Millheim",
    "Philipsburg",
    "Port Matilda",
    "Snow Shoe",
    "Unionville",
    "Benner",
    "Boggs",
    "Burnside",
    "College",
    "Curtin",
    "Ferguson",
    "Gregg",
    "Haines",
    "Halfmoon",
    "Harris",
    "Howard",
    "Huston",
    "Liberty",
    "Marion",
    "Miles",
    "Patton",
    "Penn",
    "Potter",
    "Rush",
    "Snow Shoe",
    "Spring",
    "Taylor",
    "Union",
    "Walker",
    "Worth",
    "Aaronsburg",
    "Baileyville",
    "Blanchard",
    "Boalsburg",
    "Casanova",
    "Clarence",
    "Coburn",
    "Continental Courts",
    "Eagle Creek",
    "Eagleville",
    "Holters Crossing",
    "Houserville",
    "Hublersburg",
    "Jacksonville",
    "Julian",
    "Lemont",
    "Madisonburg",
    "Mingoville",
    "Monument",
    "Moose Run",
    "Moshannon",
    "Mount Eagle",
    "Nittany",
    "North Philipsburg",
    "Orviston",
    "Park Forest Village",
    "Peru",
    "Pine Glen",
    "Pine Grove Mills",
    "Pleasant Gap",
    "Potters Mills",
    "Ramblewood",
    "Rebersburg",
    "Runville",
    "Sandy Ridge",
    "Snydertown",
    "South Philipsburg",
    "Spring Mills",
    "Stormstown",
    "Toftrees",
    "Woodward",
    "Yarnell",
    "Zion",
    "Axemann",
    "Colyer",
    "Graysdale",
    "Gum Stump",
    "Ingleby",
    "Martha Furnace",
    "Struble",
    "Tusseyville",
    "University Park",
    "Waddle"
]

PENNSYLVANIA_CHESTER_COUNTY = [
    "Coatesville",
    "Atglen",
    "Avondale",
    "Downingtown",
    "Elverson",
    "Honey Brook",
    "Kennett Square",
    "Malvern",
    "Modena",
    "Oxford",
    "Parkesburg",
    "Phoenixville",
    "South Coatesville",
    "Spring City",
    "West Chester",
    "West Grove",
    "Birmingham",
    "Caln",
    "Charlestown",
    "East Bradford",
    "East Brandywine",
    "East Caln",
    "East Coventry",
    "East Fallowfield",
    "East Goshen",
    "East Marlborough",
    "East Nantmeal",
    "East Nottingham",
    "East Pikeland",
    "East Vincent",
    "East Whiteland",
    "Easttown",
    "Elk",
    "Franklin",
    "Highland",
    "Honey Brook",
    "Kennett",
    "London Britain",
    "London Grove",
    "Londonderry",
    "Lower Oxford",
    "New Garden",
    "New London",
    "Newlin",
    "North Coventry",
    "Penn",
    "Pennsbury",
    "Pocopson",
    "Sadsbury",
    "Schuylkill",
    "South Coventry",
    "Thornbury",
    "Tredyffrin",
    "Upper Oxford",
    "Upper Uwchlan",
    "Uwchlan",
    "Valley",
    "Wallace",
    "Warwick",
    "West Bradford",
    "West Brandywine",
    "West Caln",
    "West Fallowfield",
    "West Goshen",
    "West Marlborough",
    "West Nantmeal",
    "West Nottingham",
    "West Pikeland",
    "West Sadsbury",
    "West Vincent",
    "West Whiteland",
    "Westtown",
    "Willistown",
    "Berwyn",
    "Caln",
    "Chadds Ford",
    "Delaware County",
    "Chesterbrook",
    "Cheyney University",
    "Cochranville",
    "Devon",
    "Dilworthtown",
    "Eagle",
    "Eagleview",
    "Exton",
    "Frazer",
    "Glenmoore",
    "Hamorton",
    "Hayti",
    "Kenilworth",
    "Kimberton",
    "Lincoln University",
    "Lionville",
    "Marshallton",
    "Nottingham",
    "Paoli",
    "Pomeroy",
    "Pughtown",
    "Sadsburyville",
    "South Pottstown",
    "Thorndale",
    "Toughkenamon",
    "Unionville",
    "Westwood",
    "Birchrunville",
    "Black Horse",
    "Brandamore",
    "Bucktown",
    "Byers Station",
    "Cedarville",
    "Chatham",
    "Chester Springs",
    "Chesterville",
    "Compass",
    "Coventryville",
    "Cromby",
    "Darlington Corners",
    "Daylesford",
    "Devault",
    "Doe Run",
    "Dorlan",
    "Embreeville",
    "Ercildoun",
    "Faggs Manor",
    "Glenloch",
    "Goshenville",
    "Hallman",
    "Harmony Hill",
    "Harmonyville",
    "Hayesville",
    "Hephzibah",
    "Hickory Hill",
    "Hiestand",
    "Homeville",
    "Humphreyville",
    "Icedale",
    "Ironsides",
    "Isabella",
    "Jennersville",
    "Kaolin",
    "Kelton",
    "Kemblesville",
    "Knauertown",
    "Landenberg",
    "Lenape",
    "Lewisville",
    "London Grove",
    "Longwood",
    "Lower Hopewell",
    "Ludwigs Corner",
    "Lyndell",
    "Mendenhall",
    "Milford Mills",
    "Mortonville",
    "Morstein",
    "Nantmeal Village",
    "Parker Ford",
    "Pocopson",
    "Russellville",
    "Saint Peters",
    "Siousca",
    "Springdell",
    "Steelville",
    "Strafford",
    "Strickersville",
    "Sugartown",
    "Suplee",
    "Valley Forge",
    "Wagontown",
    "Warwick",
    "West Goshen",
    "Whitford",
    "Willowdale",
    "Yellow Springs",
    "Barnestown"
]

PENNSYLVANIA_DELAWARE_COUNTY = [
    "Chester",
    "Aldan",
    "Brookhaven",
    "Chester Heights",
    "Clifton Heights",
    "Collingdale",
    "Colwyn",
    "Darby",
    "East Lansdowne",
    "Eddystone",
    "Folcroft",
    "Clenolden",
    "Lansdowne",
    "Marcus Hook",
    "Media",
    "Millbourne",
    "Morton",
    "Norwood",
    "Parkside",
    "Prospect Park",
    "Ridley Park",
    "Rose Valley",
    "Rutledge",
    "Sharon Hill",
    "Swarthmore",
    "Trainer",
    "Upland",
    "Yeadon",
    "Aston",
    "Bethel",
    "Chadds Ford",
    "Chester",
    "Concord",
    "Darby",
    "Edgmont",
    "Haverford",
    "Lower Chichester",
    "Marple",
    "Middletown",
    "Nether Providence",
    "Newtown",
    "Radnor",
    "Ridley",
    "Springfield",
    "Thornbury",
    "Tinicum",
    "Upper Chichester",
    "Upper Darby",
    "Upper Providence",
    "Ardmore",
    "Boothwyn",
    "Broommall",
    "Cheyney University",
    "Drexel Hill",
    "Folsom",
    "Haverford College",
    "Lima",
    "Linwood",
    "Village Green-Green Ridge",
    "Woodlyn",
    "Garrett Hill",
    "Glen Mills",
    "Havertown",
    "Radnor",
    "Riddlewood",
    "Rosemont",
    "Secane",
    "Thornton",
    "Villanova",
    "Wallingford",
    "Wawa",
    "Wayne"
]

PENNSYLVANIA_MONTGOMERY_COUNTY = [
    "Bryn Athyn",
    "Cheltenham Township",
    "Horsham Township",
    "Norristown",
    "Plymouth Township",
    "Whitemarsh Township",
    "Ambler",
    "Bridgeport",
    "Collegeville",
    "Conshohocken",
    "East Greenville",
    "Green Lane",
    "Hatboro",
    "Hatfield",
    "Jenkintown",
    "Lansdale",
    "Narberth",
    "North Wales",
    "Pennsburg",
    "Pottstown",
    "Red Hill",
    "Rockledge",
    "Royersford",
    "Schwenksville",
    "Souderton",
    "Telford",
    "Trappe",
    "West Conshohocken",
    "Abington",
    "Douglass",
    "East Norriton",
    "Franconia",
    "Hatfield",
    "Limerick",
    "Lower Frederick",
    "Lower Gwynedd",
    "Lower Merion",
    "Lower Moreland",
    "Lower Pottsgrove",
    "Lower Providence",
    "Lower Salford",
    "Marlborough",
    "Montgomery",
    "New Hanover",
    "Perkiomen",
    "Plymouth",
    "Salford",
    "Skippack",
    "Springfield",
    "Towamencin",
    "Upper Dublin",
    "Upper Frederick",
    "Upper Gwynedd",
    "Upper Hanover",
    "Upper Merion",
    "Upper Moreland",
    "Upper Pottsgrove",
    "Upper Providence",
    "Upper Salford",
    "West Norriton",
    "West Pottsgrove",
    "Whitemarsh",
    "Whitpain",
    "Worcester",
    "Arcadia University",
    "Ardmore",
    "Audubon",
    "Blue Bell",
    "Bryn Mawr",
    "Eagleville",
    "Evansburg",
    "Flourtown",
    "Fort Washington",
    "Gilbertsville",
    "Glenside",
    "Halfway House",
    "Harleysville",
    "Haverford College",
    "Horsham",
    "King of Prussia",
    "Kulpsville",
    "Maple Glen",
    "Montgomeryville",
    "Oreland",
    "Penn Wynne",
    "Plymouth Meeting",
    "Pottsgrove",
    "Sanatoga",
    "Skippack",
    "Spring House",
    "Spring Mount",
    "Stowe",
    "Trooper",
    "Willow Grove",
    "Woxall",
    "Wyncote",
    "Wyndmoor",
    "Ardsley",
    "Bala Cynwyd",
    "Bethayres",
    "Dresher",
    "Elkins Park",
    "Frederick",
    "Graterford",
    "Gladwyne",
    "Gwynedd",
    "Gwynedd Valley",
    "Huntingdon Valley",
    "Lafayette Hill",
    "Lederach",
    "Linfield",
    "Melrose Park",
    "Merion",
    "Mont Clare",
    "Oaks",
    "Port Providence",
    "Rosemont",
    "Villanova",
    "Wynnewood",
    "Meadowbrook"
]

PENNSYLVANIA_PHILADELPHIA_COUNTY = [
    "Philadelphia",
    "Center City",
    "South Philadelphia",
    "Southwest Philadelphia",
    "West Philadelphia",
    "Lower North Philadelphia",
    "Upper North Philadelphia",
    "Bridesburg-Kensington-Port Richmond",
    "Roxborough-Manayunk",
    "Germantown-Chestnut Hill",
    "Olney-Oak Lane",
    "Near Northeast Philadelphia",
    "Far Northeast Philadelphia",
    "Avenue of the Arts",
    "Callowhill",
    "Chinatown",
    "Elfreth's Alley",
    "French Quarter",
    "Logan Square",
    "Naval Square",
    "Jewelers' Row",
    "Market East",
    "Old City",
    "Museum District",
    "Penn Center",
    "Rittenhouse Square",
    "Fitler Square",
    "Penn's Landing",
    "Society Hill",
    "South Street",
    "Washington Square West",
    "Washington Square",
    "Midtown Village",
    "The Gayborhood",
    "Bella Vista",
    "Central South Philadelphia",
    "Devil's Pocket",
    "Dickinson Square West",
    "East Passyunk Crossing",
    "Frankling Delano Roosevelt Park",
    "Girard Estate",
    "Grays Ferry",
    "Hawthorne",
    "Italian Market",
    "Little Saigon",
    "Lower Moyamensing",
    "Marconi Plaza",
    "Moyamensing",
    "Newbold",
    "Packer Park",
    "Passyunk Square",
    "Pennsport",
    "Point Breeze",
    "Queen Village",
    "Schuylkill",
    "Sports Complex",
    "Tasker",
    "Wharton",
    "Whitman",
    "Wilson Park",
    "West Passyunk",
    "Southwark",
    "Graduate Hospital",
    "Angora",
    "Bartram village",
    "Clearview",
    "Kingsessing",
    "Eastwick",
    "Elmwood Park",
    "Hedgerow",
    "Mount Moriah",
    "Paschall",
    "Penrose",
    "Near the airportSouthwest Schuylkill",
    "Hog Island",
    "Belmont District",
    "Belmont Village",
    "Carroll Park",
    "Cathedral Park",
    "Cedar Park",
    "Centennial District",
    "Dunlap",
    "Garden Court",
    "Haddington",
    "Haverford North",
    "Mantua",
    "Mill Creek",
    "Overbrook",
    "Overbrook Park",
    "Overbrook Farms",
    "Parkside",
    "Powelton Village",
    "Saunders Park",
    "Spruce Hill",
    "Squirrel Hill",
    "University City",
    "Walnut Hill",
    "Woodland Terrace",
    "Wynnefield Heights",
    "Cobbs Creek",
    "Wynnefield",
    "Fairmount Park",
    "Brewerytown",
    "Cecil B. Moore",
    "Hartranft",
    "Ludlow",
    "Poplar",
    "Sharswood",
    "Spring Garden",
    "Stanton",
    "Strawberry Mansion",
    "Yorktown",
    "Fairmount",
    "Northern Liberties",
    "Allegheny West",
    "Fairhill",
    "Glenwood",
    "Hunting Park",
    "Nicetown-Tioga",
    "Bridesburg",
    "Fishtown",
    "Harrowgate",
    "Kensington",
    "South Kensington",
    "East Kensington",
    "West Kensington",
    "Port Richmond",
    "Andorra",
    "East Falls",
    "Wissahickon",
    "Roxborough",
    "Manayunk",
    "Chestnut Hill",
    "Mount Airy",
    "Cedarbrook",
    "Germantown",
    "Morton",
    "Wister",
    "East Oak Lane",
    "Feltonville",
    "Fern Rock",
    "Koreatown",
    "Logan",
    "Melrose Park",
    "Ogontz",
    "Olney",
    "West Oak Lane",
    "Burholme",
    "Castor Gardens",
    "Crescentville",
    "Fox Chase",
    "Frankford",
    "Holmesburg",
    "Juniata",
    "Lawncrest",
    "Lawndale",
    "Lexington Park",
    "Mayfair",
    "Northwood",
    "Oxford Circle",
    "Rhawnhurst",
    "Ryers",
    "Tacony",
    "Wissinoming",
    "Academy Gardens",
    "Ashton-Woodenbridge",
    "Bustleton",
    "Byberry",
    "Crestmont Farms",
    "Krewstown",
    "Millbrook",
    "Modena Park",
    "Morrell Park",
    "Normandy",
    "Parkwood",
    "Pennypack",
    "Somerton",
    "Torresdale",
    "Upper Holmesburg",
    "Winchester Park",
    "Walton Park",
    "Aramingo Borough",
    "Belmont District",
    "Blockley Township",
    "Bridesburg Borough",
    "Bristol Township",
    "Byberry Township",
    "Delaware Township",
    "Frankford Borough",
    "Germantown Borough",
    "Germantown Township",
    "Kensington District",
    "Kingsessing Township",
    "Lower Dublin Township",
    "Manayuk Borough",
    "Moreland Township",
    "Moyamensing District",
    "Northern Liberties District",
    "Northern Liberties Township",
    "Oxford Township",
    "Passyunk Township",
    "Penn District",
    "Penn Township",
    "Richmond District",
    "Roxborough Township",
    "Southwark District",
    "Spring Garden District",
    "West Philadelphia Borough",
    "Whitehall Borough"
]

PENNSYLVANIA_PITTSBURGH = [
    "Allegheny Center",
    "Allegheny West",
    "Allentown",
    "Arlington",
    "Arlington Heights",
    "Banksville",
    "Bedford Dwellings",
    "Beechview",
    "Beltzhoover",
    "Bloomfield",
    "Bluff",
    "Bon Air",
    "Brighton Heights",
    "Brookline",
    "California-Kirkbride",
    "Carrick",
    "Central Business District",
    "Chinatown",
    "Cultural District",
    "Central Lawrenceville",
    "Central Northside",
    "Mexican War Streets",
    "Central Oakland",
    "Chartiers",
    "Chateau",
    "Crafton Heights",
    "Crawford-Roberts",
    "Duquesne Heights",
    "East Allegheny",
    "East Carnegie",
    "East Hills",
    "East Liberty",
    "Elliott",
    "Esplen",
    "Fairywood",
    "Fineview",
    "Friendship",
    "Garfield",
    "The Valley",
    "Hilltop",
    "Glen Hazel",
    "Greenfield",
    "Four Mile Run",
    "Hays",
    "Hazelwood",
    "Highland Park",
    "Homewood North",
    "Homewood South",
    "Homewood West",
    "Knoxville",
    "Larimer",
    "Lincoln–Lemington–Belmar",
    "Lincoln Place",
    "Lower Lawrenceville",
    "Manchester",
    "Marshall-Shadeland",
    "Brunot Island",
    "Middle Hill",
    "Morningside",
    "Mount Oliver",
    "Mount Washington",
    "Chatham Village",
    "New Homestead",
    "North Oakland",
    "North Point Breeze",
    "North Shore",
    "Northview Heights",
    "Oakwood",
    "Overbrook",
    "Perry North",
    "Perry South",
    "Point Breeze",
    "Park Place",
    "Polish Hill",
    "Regent Square",
    "Ridgemont",
    "Saint Clair",
    "Shadyside",
    "Sheraden",
    "South Oakland",
    "Panther Hollow",
    "Southshore",
    "Station Square",
    "South Side Flats",
    "SouthSide Works",
    "South Side Slopes",
    "Spring Garden",
    "Spring Hill–City View",
    "Squirrel Hill North",
    "Squirrel Hill South",
    "Summerset",
    "Stanton Heights",
    "Strip District",
    "Summer Hill",
    "Swisshelm Park",
    "Duck Hollow",
    "Terrace Village",
    "Troy Hill",
    "Washington's Landing",
    "Upper Hill",
    "Upper Lawrenceville",
    "West End",
    "West Oakland",
    "Westwood",
    "Windgap",
    "Central",
    "East End",
    "North Side",
    "South Side",
    "West End",
    "Uptown",
    "Soho",
    "Downtown",
    "Golden Triangle",
    "Deutschtown",
    "Brightwood",
    "Woods Run",
    "Observatory Hill",
    "Perry Hilltop",
    "Clairton",
    "Duquesne",
    "McKeesport",
    "Pittsburgh",
    "Aspinwall",
    "Avalon",
    "Baldwin",
    "Bell Acres",
    "Bellevue",
    "Ben Avon",
    "Ben Avon Heights",
    "Bethel Park",
    "Blawnox",
    "Brackenridge",
    "Braddock",
    "Braddock Hills",
    "Bradford Woods",
    "Brentwood",
    "Bridgeville",
    "Carnegie",
    "Castle Shannon",
    "Chalfant",
    "Cheswick",
    "Churchhill",
    "Coraopolis",
    "Crafton",
    "Dormont",
    "Dravosburg",
    "East McKeesport",
    "East Pittsburgh",
    "Edgewood",
    "Edgeworth",
    "Elizabeth",
    "Emsworth",
    "Etna",
    "Forest Hills",
    "Fox Chapel",
    "Franklin Park",
    "Glassport",
    "Glen Osborne",
    "Glenfield",
    "Green Tree",
    "Haysville",
    "Heidelberg",
    "Homestead",
    "Ingram",
    "Jefferson Hills",
    "Leetsdale",
    "Liberty",
    "Lincoln",
    "McDonald",
    "McKees Rocks",
    "Millvale",
    "Monroeville",
    "Mount Oliver",
    "Munhall",
    "North Braddock",
    "Oakdale",
    "Oakmont",
    "Pennsbury",
    "Pitcairn",
    "Pleasant Hills",
    "Plum",
    "Port Vue",
    "Rankin",
    "Rosslyn Farms",
    "Sewickley",
    "Sewickley Heights",
    "Sewickley Hills",
    "Sharpsburg",
    "Springdale",
    "Swissvale",
    "Tarentum",
    "Thornburg",
    "Trafford",
    "Turtle Creek",
    "Verona",
    "Versailles",
    "Wall",
    "West Elizabeth",
    "West Homestead",
    "West Mifflin",
    "West View",
    "Whitaker",
    "White Oak",
    "Whitehall",
    "Wilkinsburg",
    "Wilmerding",
    "Aleppo",
    "Baldwin",
    "Collier",
    "Crescent",
    "East Deer",
    "Elizabeth",
    "Fawn",
    "Findlay",
    "Forward",
    "Frazer",
    "Hampton",
    "Harmar",
    "Harrison",
    "Indiana",
    "Kennedy",
    "Kilbuck",
    "Leet",
    "Marshall",
    "McCandless",
    "Moon",
    "Mt. Lebanon",
    "Neville",
    "North Fayette",
    "North Versailles",
    "O'Hara",
    "Ohio",
    "Penn Hills",
    "Pine",
    "Reserve",
    "Richland",
    "Robinson",
    "Ross",
    "Scott",
    "Shaler",
    "South Fayette",
    "South Park",
    "South Versailles",
    "Springdale",
    "Stowe",
    "Upper Saint Clair",
    "West Deer",
    "Wilkins",
    "Allison",
    "Bairdford",
    "Bakerstown",
    "Boston",
    "Carnot-Moon",
    "Clinton",
    "Curtisville",
    "Enlow",
    "Gibsonia",
    "Glenshaw",
    "Greenock",
    "Harwick",
    "Imperial",
    "Noblestown",
    "Rennerdale",
    "Russellton",
    "Sturgeon",
    "Acmetonia",
    "Alpsville",
    "Blackridge",
    "Blanchard",
    "Broughton",
    "Bruceton",
    "Buena Vista",
    "Creighton",
    "Cubbage Hill",
    "Cuddy",
    "Dorseyville",
    "Ewingsville",
    "Harmarville",
    "Hickory Heights",
    "Indianola",
    "Ingomar",
    "Karns",
    "Keown Station",
    "Kirwan Heights",
    "Library",
    "McKnight",
    "Moon Run",
    "Mount Vernon",
    "Natrona",
    "Natrona Heights",
    "Nevillewood",
    "Presto",
    "Regent Square",
    "Rural Ridge",
    "Sheraden",
    "Sherman",
    "Treveskyn",
    "Warrendale",
    "Wexford",
    "Wildwood"
]

PENNSYLVANIA_YORK = [
    "York",
    "Cross Roads",
    "Dallastown",
    "Delta",
    "Dillsburg",
    "Dover",
    "East Prospect",
    "Fawn Grove",
    "Felton",
    "Franklintown",
    "Glen Rock",
    "Goldsboro",
    "Hallam",
    "Hanover",
    "Jacobus",
    "Jefferson",
    "Lewisberry",
    "Loganville",
    "Manchester",
    "Mount Wolf",
    "New Freedom",
    "New Salem",
    "North York",
    "Railroad",
    "Red Lion",
    "Seven Valleys",
    "Shrewsbury",
    "Spring Grove",
    "Stewartstown",
    "Wellsville",
    "West York",
    "Windsor",
    "Winterstown",
    "Wrightsville",
    "Yoe",
    "York Haven",
    "Yorkana",
    "Carroll",
    "Chanceford",
    "Codorus",
    "Conewago",
    "Dover",
    "East Hopewell",
    "East Manchester",
    "Fairview",
    "Fawn",
    "Franklin",
    "Heidelberg",
    "Hellam",
    "Hopewell",
    "Jackson",
    "Lower Chanceford",
    "Lower Windsor",
    "Manchester",
    "Manheim",
    "Monaghan",
    "Newberry",
    "North Codorus",
    "North Hopewell",
    "Paradise",
    "Peach Bottom",
    "Penn",
    "Shrewsbury",
    "Spring Garden",
    "Springettsbury",
    "Springfield",
    "Warrington",
    "Washington",
    "West Manchester",
    "West Manheim",
    "Windsor",
    "York",
    "East York",
    "Emigsville",
    "Grantley",
    "New Market",
    "Parkville",
    "Pennville",
    "Pleasureville",
    "Queens Gate",
    "Shiloh",
    "Spry",
    "Stonybrook",
    "Susquehanna Trails",
    "Tyler Run",
    "Valley Green",
    "Valley View",
    "Weigelstown",
    "Yorklyn",
    "Accomac",
    "Admire",
    "Airville",
    "Ambau",
    "Andersontown",
    "Bandanna",
    "Bermudian",
    "Big Mountain",
    "Blackrock",
    "Bridgeville",
    "Brogue",
    "Bryansville",
    "Cly",
    "Craley",
    "Codorus Furnace",
    "Conewago Heights",
    "Davidsburg",
    "Detters Mill",
    "Etters",
    "Fayfield",
    "Fireside Terrace",
    "Foustown",
    "Fuhrmans Mill",
    "Gatchellville",
    "Glades",
    "Glenville",
    "Gnatstown",
    "Hametown",
    "Hanover Junction",
    "Hopewell Center",
    "Kralltown",
    "Leaders Heights",
    "Leibharts Corner",
    "Lockport",
    "Mackey Ford",
    "Mount Royal",
    "Muddy Creek Forks",
    "New Bridgeville",
    "New Park",
    "Nauvoo",
    "Ore Valley",
    "Porters Sideling",
    "Reesers Summit",
    "Rossville",
    "Saginaw",
    "Shenks Ferry",
    "Siddonsburg",
    "Spring Forge",
    "Starview",
    "Stoverstown",
    "Strickler",
    "Strinestown",
    "Sunnyburn",
    "Thomasville",
    "Tolna",
    "Valley Forge",
    "Violet Hill",
    "Wago Junction",
    "Woodbine",
    "Yocumtown",
    "York Furnace"
]
